const elvishDictionary = {
  // --- A ---
  "a": "a, ah, ar",
  "abandon": "awartha-",
  "abandons": "awartha-",
  "abandoned": "awartha-",
  "abandoning": "awartha-",
  "abandonment": "awarth",
  "abhor": "fuia-",
  "abhors": "fuia-",
  "abhorred": "fuia-",
  "abhorring": "fuia-",
  "abhorrence fear horror dread detestation loathing": "delos",
  "abhorrent": "thaur, thoren",
  "abiding": "him, thand",
  "able-bodied men (troop of), manhood, manpower, host, regiment, people, region, wilderness": "gwaith",
  "abominable": "thaur, thoren",
  "abyss chasm void gulf": "dath, iâ",
  "according to": "be, ben",
  "account": "trenarn",
  "accounts": "trenarn",
  "across": "athra-, thar-",
  "across beyond": "athar",
  "action, readiness for, vigour, fiery spirit": "hûr",
  "acute, keen, sharp": "laeg",
  "admiration exclamation of": "elo!",
  "adventure": "bandath",
  "adventures": "bandath",
  "affection, love, kindness": "mîl",
  "affliction heavy burden": "caul",
  "after": "ab",
  "again": "ad",
  "again back second": "ad-",
  "against": "dan",
  "against again": "ad",
  "age": "andrann",
  "ages": "andrann",
  "age cycle": "andrann",
  "aged, long-lived": "iphant",
  "agile swift": "celeg",
  "ah": "alae!",
  "air": "gwaeth",
  "air (as substance)": "gwelu",
  "air (as a region)": "gwelwen, gwilith",
  "air (of music), song, tune, singer": "lind",
  "alive": "cuin",
  "all": "pân",
  "alone first single": "eriol, erui",
  "alphabet": "tiwdi",
  "alphabet runic": "certhas",
  "also": "sen",
  "always": "ui",
  "am": "im",
  "anchorage, haven, harbour, quiet water": "lorn",
  "and": "a, ah, ar",
  "anger": "rûth, ruith",
  "angle": "bennas",
  "angles": "bennas",
  "animal (quadrupedal mammal)": "lavan",
  "animals": "lavan",
  "annals": "ínias",
  "anniversary day": "edinor",
  "answer reply": "dangweth",
  "answer response": "dambeth",
  "ant": "nedrui",
  "ants": "nedrui",
  "anybody": "pen",
  "apostrophe": "gasdil",
  "apparition": "auth",
  "approach": "anglenna-",
  "approaches": "anglenna-",
  "approached": "anglenna-",
  "approaching": "anglenna-",
  "april": "gwirith",
  "arch bow crescent": "cû",
  "are": "nar",
  "armor": "harnath",
  "arrange": "partha-",
  "arranges": "partha-",
  "arranged": "partha-",
  "arranging": "partha-",
  "arrow": "pilin",
  "arrows": "pilin",
  "art, craft, handcraft": "maenas",
  "article for exchange": "bach",
  "as": "sui",
  "ash": "lith",
  "ashes": "lith",
  "ash, sand, dust": "lith",
  "ashen, ashy": "lith",
  "assembly": "hûd",
  "at": "na",
  "august": "úrui",
  "autumn": "iavas, dannas, firith, lasbelin",
  "awakening": "echui",
  "away": "gwachae",
  "awe": "anwar",
  "axe, axe blade": "hathol",
  "axes": "hathol",
  "axe-stroke": "hast",

  // --- B ---
  "babble": "glavra",
  "babbles": "glavra",
  "babbled": "glavra",
  "babbling": "glavrol, glavra",
  "babe, also used in children's play as the name of the little finger": "laes",
  "baby, little finger": "gwinig",
  "back": "ad-",
  "bad": "ulug, um",
  "bad poor mean": "faeg",
  "badly": "faeg",
  "ball globe mound": "coron",
  "ban prohibit": "boda-",
  "bane": "dagnir",
  "bank shore": "esgar",
  "barrow": "gorthad",
  "battle": "dagor",
  "battles": "dagor",
  "battle of two or a few": "maeth",
  "be": "na",
  "being": "na",
  "been": "na",
  "be alive": "cuina-",
  "be off": "ego!",
  "beach": "falas",
  "beaches": "falas",
  "beach shore coast strand line of surf foaming shore": "falas",
  "bear": "brôg, graw, medli, mug",
  "bears": "brôg, graw, medli, mug",
  "bear carry": "col-",
  "beard": "fang, mo",
  "beards": "fang, mo",
  "bearish, of bear": "medlin",
  "beat": "dringa-",
  "beats": "dringa-",
  "beating": "dringa-",
  "beaten": "dringa-",
  "beat wings": "blab-",
  "beautiful fair": "bain",
  "beauty": "bain, baneth",
  "because": "an",
  "bed": "haust",
  "beds": "haust",
  "bedridden sick": "caeleb",
  "bee": "niben",
  "bees": "niben",
  "beech": "brethil",
  "beech mast": "fêr",
  "begun again new": "eden",
  "beget": "edonna-",
  "begets": "edonna-",
  "begot": "edonna-",
  "begotten": "edonna-",
  "begetting": "edonna-",
  "beginning": "ested",
  "behind": "adel",
  "beneath in under": "dî",
  "bent bow shaped": "cûn",
  "beryl elf stone": "edhelharn",
  "betray, cheat": "gweria",
  "betray": "gweria",
  "betrays": "gweria",
  "betrayed": "gweria",
  "betraying": "gweria",
  "betrayer": "gwarth",
  "between": "im",
  "between, within": "im, im-",
  "beyond": "athan, thar-",
  "birch": "hwinn",
  "birch tree": "brethil",
  "bird": "aew",
  "birds": "aew",
  "bird small": "aew, fileg",
  "birth": "onneth",
  "bitter": "saer",
  "bitterly cold": "helch",
  "black": "morn, donn, môr, nibin, nogor, núrod, nusûl, nyr",
  "black metal": "galvorn",
  "black swart swarty shady shadowy": "donn",
  "blackness": "nûr",
  "blackness, darkness": "nûrsûl",
  "blackness, shadow": "nythlûn",
  "blade (of a broadsword or axe)": "hathel",
  "blazing fire": "ruin",
  "blessing": "galu",
  "blocked": "tafnen",
  "blood": "iâr, iûr, sereg",
  "bloodstain": "agarwaen",
  "blossom": "edlothia-, gwaloth, loth",
  "blossoms": "edlothia-, gwaloth, loth",
  "blossomed": "edlothia-",
  "blossoming": "edlothia-",
  "blossom, flower": "loth",
  "blow heavy stroke": "dram",
  "blue": "luin",
  "board": "pân",
  "boards": "pân",
  "boat": "lunt",
  "boats": "lunt",
  "body": "rhaw",
  "bodies": "rhaw",
  "bogey": "urug",
  "bold": "beren, cand",
  "bond": "gwaedh",
  "bonds": "gwaedh",
  "bond of friendship": "gwend",
  "bond, bond of loyalty": "gwedh",
  "book": "parf",
  "books": "parf",
  "border": "edrain, glân",
  "borders": "edrain, glân",
  "born after": "abonnen ebennin",
  "boss round knob": "dolt",
  "both": "ui-",
  "bound": "naud, glenia",
  "boundary": "gland, taeg",
  "boundaries": "gland, taeg",
  "boundary line": "taeg",
  "boundary marker": "glandagol",
  "boundary, lest, girdle": "lest",
  "bow": "cû, peng",
  "bows": "cû, peng",
  "bowstring": "tang",
  "braided tress of hair": "finnel",
  "branch": "golf",
  "branches": "golf",
  "brand": "ylf",
  "bread": "bass",
  "bread giver feminine": "bassoneth, bessain",
  "break out suddenly": "breitha-",
  "breaker foam": "falf",
  "breath": "thûl",
  "breathe": "thuia-",
  "breathes": "thuia-",
  "breathed": "thuia-",
  "breathing": "thuia-",
  "bride": "dineth, dîs",
  "brides": "dineth, dîs",
  "bride lady": "dî",
  "bridegroom": "daer",
  "bridge": "iant, ianu",
  "bridges": "iant, ianu",
  "brilliance": "glaw",
  "brilliant": "celair",
  "bring": "tog-",
  "brings": "tog-",
  "brought": "tog-",
  "bringing": "tog-",
  "brooch": "tachol",
  "brother": "muindor, hanar, tôr",
  "brothers": "muindor, hanar, tôr",
  "broth": "salph",
  "brown swart dark": "baran",
  "bud": "tui, tuiw",
  "buds": "tui, tuiw",
  "build make do": "car-",
  "build": "car-",
  "builds": "car-",
  "built": "car-",
  "building": "car-",
  "builder": "thavron",
  "building house": "adab, car",
  "burial mound, barrow, grave, tomb": "haudh",
  "burn": "dosta-",
  "burns": "dosta-",
  "burned": "dosta-",
  "burnt": "dosta-",
  "burning": "ruin, dosta-",
  "bush (low-growing)": "toss",
  "but": "dan",
  "but however": "dan",
  "butterfly": "gwilwileth, gwiwileth",
  "butterflies": "gwilwileth, gwiwileth",
  "by": "od",

  // --- C ---
  "cairn": "sarnas",
  "cake": "cram",
  "cakes": "cram",
  "call name": "esta-",
  "call out": "ialla",
  "call": "can-",
  "calls": "can-",
  "called": "can-",
  "calling": "can-",
  "call shout cry": "can-",
  "calligrapher": "tegilbor",
  "can": "pol-, gar",
  "canopy": "daedelu",
  "captain": "hest",
  "captains": "hest",
  "carpenter": "thavron",
  "cat": "meoi",
  "cats": "meoi",
  "catch": "gad-",
  "catches": "gad-",
  "caught": "gad-",
  "catching": "gad-",
  "causeway": "gondrath",
  "cave": "fela, gathrod, grôd",
  "caves": "fela, gathrod, grôd",
  "cave, delving, large excavation": "groth",
  "cavern": "gath",
  "center core middle": "enedh",
  "century": "andrann",
  "centuries": "andrann",
  "chain iron bond": "angwedh",
  "chair": "ham",
  "chairs": "ham",
  "chamber": "sam",
  "chambers": "sam",
  "chant, sing": "linna-",
  "charm, enchant": "lûth",
  "charm, enchantment, magic": "lûth",
  "child": "hên",
  "children": "hên",
  "choking gasping thirsty": "faug",
  "choose": "cil-",
  "chooses": "cil-",
  "chose": "cil-",
  "chosen": "cil-",
  "choosing": "cil-",
  "circle": "corn",
  "circles": "corn",
  "circular round globed": "corn",
  "city": "ost",
  "cities": "ost",
  "city with watchtower": "minas",
  "clamour outcry": "caun",
  "clasp": "taew",
  "claw, hook, crook": "gamp",
  "clean": "puig",
  "clear": "glân, glanna",
  "clear, sparkling": "lim",
  "clear, sparkling, light": "hâl",
  "cleared, plain, flat, wide, open": "laden",
  "clearing in forest": "lant",
  "cleaver sword": "crist",
  "cleft": "thanc",
  "cleft cutting pass": "cirith",
  "cleft gulf ravine": "criss",
  "cleft pass between hills": "cîl",
  "cleft ravine": "falch",
  "clenched fist blow with fist": "drambor",
  "climb high pass": "andrath",
  "cloak": "coll",
  "cloaks": "coll",
  "close": "hol, sol-",
  "closes": "hol, sol-",
  "closed": "hollen, sollen, tafnen, uidafnen",
  "closing": "hol, sol-",
  "clot, blood-clot": "môrtha",
  "clothe": "hab, hamma",
  "clothes": "hab",
  "clothing": "hammad",
  "cloud": "fain, faun, nef",
  "clouds": "fain, faun, nef",
  "cloud veil manifested body of a vala": "fân",
  "cloudy": "fanui, nefrin",
  "club": "grond",
  "coat": "helf",
  "cobweb, spider, spider's web": "lhing",
  "cold": "ring",
  "cold pool, lake": "hoth",
  "collection of leaves, foliage": "golas",
  "come": "tol, tol-",
  "comes": "tol, tol-",
  "came": "tol, tol-",
  "coming": "tol, tol-",
  "commanding": "conui",
  "community": "govannas",
  "compact, contract, treaty": "gowest",
  "complete": "pant",
  "compose": "partha-",
  "compulsion": "thang",
  "conceal": "delia-, doltha-, gor",
  "conceals": "delia-, doltha-, gor",
  "concealed": "delia-, doltha-, gor",
  "concealing": "delia-, doltha-, gor",
  "confirm": "tangada-",
  "constrain oppress": "baugla-",
  "constrainer oppressor tyrant": "bauglir, baugron",
  "continually": "him",
  "control": "tortha-, tûr",
  "controls": "tortha-, tûr",
  "controlled": "tortha-, tûr",
  "controlling": "tortha-, tûr",
  "cooked food": "aes",
  "cool": "him",
  "copper": "rust",
  "corn (not maize)": "iaw",
  "corpse": "daen",
  "corpses": "daen",
  "corrupt": "thaw",
  "count": "genediad, gonod",
  "counts": "genediad, gonod",
  "counted": "genediad, gonod",
  "counting": "genediad, gonod",
  "countless innumerable": "aronoded",
  "country": "ardh",
  "countries": "ardh",
  "couplet": "linnod",
  "course": "ýr",
  "courtyard": "pand",
  "cover veil screen": "escal",
  "creature": "ûn",
  "creatures": "ûn",
  "creature powerful, hostile and terrible": "graug",
  "crescent moon": "cúron",
  "crest of helmet": "amloth",
  "cross": "athra-, trevad-",
  "crosses": "athra-, trevad-",
  "crossed": "athra-, trevad-",
  "crossing": "athra-, trevad-",
  "crossing ford": "athrad",
  "crossway": "tharbad",
  "crow": "corch, craban",
  "crows": "corch, craban",
  "crown": "rî",
  "crowns": "rî",
  "cruel": "balch",
  "cry": "nîr",
  "cries": "nîr",
  "cried": "nîr",
  "crying": "nîr",
  "cry of encouragement in battle": "hûl",
  "crystal": "ivor",
  "cunning device": "curu",
  "custody prison": "band",
  "custom, habit": "haew",
  "cutlass, sword": "lang",

  // --- D ---
  "daddy": "ada edai",
  "dagger": "sigil",
  "daggers": "sigil",
  "daily": "ilaurui",
  "daisy": "eirien",
  "dance": "lilth, liltha-",
  "dances": "lilth, liltha-",
  "danced": "lilth, liltha-",
  "dancing": "lilth, liltha-",
  "dangle": "glinga",
  "dare": "bertha-",
  "dark": "dûr, morn, múrn, nûrû, núthûn, nyr",
  "dark dusky misty obscure": "doll",
  "dark sorcery": "guldur",
  "dark, black": "nûrû, nyr",
  "dark, shadowy": "nûrûn",
  "darkness": "môr, dú, múra, nod, nûr, nûrsûl, nûtho, nythlûn",
  "darkness gloom night dead of night": "fuin",
  "darkness night nightfall dusk": "dû",
  "daughter": "sell",
  "daughters": "sell",
  "daughter, girl, maid": "iell",
  "dauntless": "thalion",
  "day": "aur, calan, arad",
  "days": "aur, calan, arad",
  "day morning": "aur",
  "dazzling white, white as snow": "gloss",
  "dead": "fern, gorth, gwann",
  "dead dead person": "fern",
  "dead person": "gorth",
  "deadly fear": "gorgor",
  "deadly hateful fell": "delu",
  "deal with, handle, wield, manage": "maetha-",
  "dear": "mail, mell",
  "death": "gurth, gûr, guruth",
  "deaths": "gurth, gûr, guruth",
  "death (act of dying)": "gwanath",
  "death by fading": "gwanu",
  "death-horror, dread of death": "guruthos",
  "debate": "athrabeth",
  "decay": "thaw",
  "december": "girithon",
  "declivity": "pend",
  "deed house building": "cardh",
  "deep": "núr, tofn",
  "deep vale, dell": "im",
  "deep valley": "tûm",
  "deer": "aras",
  "defeat": "dangen",
  "defeats": "dangen",
  "defeated": "dangen",
  "defeating": "dangen",
  "defend": "gartha",
  "defends": "gartha",
  "defended": "gartha",
  "defending": "gartha",
  "defile pass between high walls": "aglonn",
  "defined or bounded place": "gardh",
  "deformed": "ulunn",
  "delight": "gella",
  "denial": "ubed",
  "depart": "gwanna",
  "departs": "gwanna",
  "departed": "gwanwen, gwanna",
  "departing": "gwanna",
  "departed spirit": "mân",
  "descendant, son": "iôn",
  "descendant, son (coll. pl)": "ionnath",
  "desert": "eryn",
  "deserts": "eryn",
  "desire": "aníra-, íra",
  "destiny": "manadh",
  "detestable": "thaur, thoren",
  "device": "gaud",
  "dew": "midh",
  "die": "fir",
  "dies": "fir",
  "died": "fir",
  "dying": "fir",
  "die fade": "fir-",
  "different": "edraith",
  "difficulty": "tarias",
  "dim, overshadow, veil, obscure": "gwathra",
  "dim, shadowy": "gwathren",
  "din, uproar, tumult, shouting, confused noise, a body of orcs": "glam",
  "dire, terrible, fell": "goeol",
  "dirty": "gwaur",
  "dirty, soiled": "gwaur",
  "disease, sickness": "lhîw",
  "disgust": "dêl",
  "distance": "haered",
  "distant, far, on the other side, further": "hae",
  "distinct, unique, single": "mîn",
  "divine": "bâl",
  "divinity divine power": "bâl",
  "do": "car",
  "does": "car",
  "did": "car",
  "done": "car",
  "doing": "car, cared",
  "do battle make war": "dagra-",
  "doer maker": "ceredir",
  "dog": "hû",
  "dogs": "hû",
  "dog (hunt)": "huan",
  "doing making": "cared",
  "dome": "telu",
  "dont": "avo!",
  "dont do": "av-",
  "doom": "amarth, bartha-",
  "doomed": "barad",
  "door": "annon, and",
  "doors": "annon, and",
  "door threshold": "fend",
  "dot": "peg",
  "double": "edaid, tadol",
  "doubt": "trass",
  "dough": "maeas",
  "dove": "cugu",
  "down": "dad, torn",
  "dragon": "amlug",
  "dragons": "amlug",
  "dragon, snake, serpent": "lhûg",
  "drain": "sautha-",
  "dread fear": "achas, gae",
  "dreadful fearful holy": "gaer",
  "dream": "ôl, múran",
  "dreams": "ôl, múran",
  "dreamed": "ôl, múran",
  "dreaming": "ôl, múran",
  "drink": "sog, soga",
  "drinks": "sog, soga",
  "drank": "sog, soga",
  "drunk": "sogannen, sog, soga",
  "drinking": "sog, soga",
  "drinking vessel": "ylf",
  "driven under compulsion": "horn",
  "dry": "parch",
  "dull": "thafn",
  "duress": "thang",
  "dusk": "mothron, tinnu",
  "dust sand ash": "ast",
  "dwarf": "nogoth, hadhod",
  "dwarves": "nogoth, hadhod",
  "dwarfs (people)": "hadhodrim",
  "dwell": "dortha-",
  "dwells": "dortha-",
  "dwelt": "dortha-",
  "dwelled": "dortha-",
  "dwelling": "dortha-",
  "dwelling house home family land earth": "bâr",

  // --- E ---
  "eagle": "thoron, thôr",
  "eagles": "thoron, thôr",
  "ear": "lhewig",
  "ears": "lhewig",
  "earth": "ceven, cae",
  "earthen": "cefn",
  "earthenware": "cefnas",
  "east": "rhûn",
  "eat": "mad, mad-",
  "eats": "mad, mad-",
  "ate": "mad, mad-",
  "eaten": "mad, mad-",
  "eating": "mad, mad-",
  "eavesdrop": "lathra-",
  "eavesdropper (fem)": "lethril",
  "ebb": "dannen",
  "echo": "glamor, lamath",
  "echoing": "glamren",
  "eclipse": "neffon",
  "eddy": "hwind",
  "eight": "toloth",
  "eighth": "tollui, tolothen",
  "elda": "calben",
  "elder": "einior",
  "eldest": "iarwain",
  "elephant": "annabon",
  "elf": "edhel, elen",
  "elves": "edhel, elen",
  "elf friend": "elvellon",
  "elf man": "ellon",
  "elf of aman": "gwanwel",
  "elf of beleriand": "avar",
  "elf of beleriand west elf including noldor and sindar": "dúnedhel",
  "elf woman": "elleth",
  "elve of aman": "gwanwen",
  "elves people": "eledhrim, elrim",
  "elvish": "edhellen",
  "elm": "lalf",
  "elm tree": "lalf, lalorn, lalven, lalwen",
  "embrace": "gwaedh",
  "embraces": "gwaedh",
  "embraced": "gwaedh",
  "embracing": "gwaedh",
  "embers": "iûl",
  "empty": "lost, cofn",
  "empty, void": "lost",
  "encampment": "echad, estolad",
  "enchantment": "galadhremmin",
  "enchantress": "luithien",
  "enclose": "glenia",
  "enclosed": "thaur",
  "enclosed dwelling": "gobel",
  "enclosed grassland": "parth",
  "enclosure": "pêl",
  "encircling fence outer fence": "ephel",
  "end": "meth, tele",
  "ends": "meth, tele",
  "ended": "meth, tele",
  "ending": "meth, tele",
  "endure": "brenia-",
  "endure stay wait remain last": "dartha-",
  "endurance": "bronwe",
  "enduring": "bronadui",
  "enemy": "goth",
  "enemies": "goth",
  "enfold": "gwaeda",
  "enlarge": "panna-",
  "enmity enemy": "coth",
  "enriched": "moden",
  "entangle": "gonathra",
  "entanglement": "gonathras",
  "especially": "edregol",
  "establish": "tangada-",
  "estuary mouth or outflow of a river": "ethir",
  "eternal": "ui, uireb",
  "eternity": "uir",
  "evening": "aduial",
  "evenings": "aduial",
  "evening twilight": "aduial",
  "everlasting": "ui, uireb",
  "evil": "úgar, um, ulug",
  "evil creature": "uruk",
  "evil knowledge, magic, sorcery, necromancy": "gûl",
  "exact": "taer",
  "exalted lofty noble": "arth",
  "exalted, high": "hall",
  "excavation": "torech",
  "exceedingly very": "dae",
  "exiled": "edlenn",
  "expression": "thîr",
  "eye": "hen, hend",
  "eyes": "hen, hend",
  "eyed": "heneb",

  // --- F ---
  "face": "thîr",
  "faces": "thîr",
  "fade": "pel-",
  "fades": "pel-",
  "faded": "pel-",
  "fading": "pelin, pel-",
  "fair-minded just generous": "fael",
  "faith hope trust": "estel",
  "faithful": "thenid",
  "fall": "danna-, lant",
  "falls": "danna-, lant",
  "fell": "danna-, lant",
  "fallen": "dannen, danna-, lant",
  "falling": "talt, danna-, lant",
  "fall falling": "dant",
  "fallow, pale": "malu",
  "false": "gog",
  "fane, holy place, sanctuary": "iaun",
  "fang": "carch",
  "fangs": "carch",
  "fantastic": "hwiniol",
  "far": "haer",
  "far off": "palan-",
  "far, distant": "haeron",
  "far, remote, distant": "haer",
  "farthing fourth part": "canath",
  "fashion make shape": "echad-",
  "fast": "laeg",
  "fasten": "taetha-",
  "fat": "tûg",
  "fate": "amarth",
  "fated": "amarthan",
  "father": "adar",
  "fathers": "adar",
  "father of men": "adanadar",
  "fear": "gorgor, gosta, groga",
  "fears": "gorgor, gosta, groga",
  "feared": "gorgor, gosta, groga",
  "fearing": "gorgor, gosta, groga",
  "feast, festival": "mereth",
  "feel, stroke, handle, wield": "matha-",
  "feel": "matha-",
  "feels": "matha-",
  "felt": "matha-",
  "feeling": "matha-",
  "female": "inu",
  "fence": "iâth, thora-",
  "fences": "iâth, thora-",
  "fence with spikes": "cail",
  "fenced": "thoren",
  "festive, joyous": "meren",
  "fetch": "toltha-",
  "few": "ark, sun",
  "field": "parth, sant",
  "fields": "parth, sant",
  "fierce wild": "braig",
  "fierceness": "bregolas",
  "fiery red": "ruin",
  "fifth": "lefnui",
  "filament, spider filament": "lhê",
  "fill": "panna-",
  "fills": "panna-",
  "filled": "panna-",
  "filling": "panna-",
  "final end, fate, fortune": "manadh",
  "find": "hir, tov-",
  "finds": "hir, tov-",
  "found": "hir, tov-",
  "finding": "hir, tov-",
  "fine high lofty noble": "brand",
  "fine pierced hole": "tess",
  "finger": "leber",
  "fingers": "leber",
  "fire": "naur, ûr",
  "fires": "naur, ûr",
  "fire demon": "balrog",
  "fire-dragon": "urlug",
  "firm": "tanc, thala, tarias",
  "fish": "lim, gail, hâl",
  "fist": "dond, paur",
  "fists": "dond, paur",
  "fit, useful, good": "maer",
  "five": "leben",
  "fix": "penia-",
  "flame": "lach, lacha, ngaur, than-",
  "flames": "lach, lacha, ngaur, than-",
  "flame, fire": "ngauru",
  "flame-eyed, elf who has lived in the blessed realm": "lachenn",
  "flat surface": "talath",
  "flat": "talu",
  "flatlands": "talath",
  "flee": "dreg-, drega-, drego!",
  "flees": "dreg-, drega-, drego!",
  "fled": "dreg-, drega-, drego!",
  "fleeing": "dreg-, drega-, drego!",
  "fleurs": "goloth",
  "float": "loda-",
  "floats": "loda-",
  "floated": "loda-",
  "floating": "loda-",
  "flood-water, wash": "iôl",
  "floor": "panas, talaf, talan",
  "flower": "loth, edlothia-",
  "flowers": "loth, edlothia-",
  "flower of gold": "mallos",
  "flowering": "edlothiad",
  "flowering valley": "imloth",
  "flow": "siria-",
  "flows": "siria-",
  "flowed": "siria-",
  "flowing": "cell, sirith, siria-",
  "foal, young horse": "mûl",
  "foam": "faltha-, gwing",
  "fog": "mith",
  "fog, mist": "hîth, hithu",
  "foggy": "hithui",
  "follow": "aphada-",
  "follows": "aphada-",
  "followed": "aphada-",
  "following": "aphada-",
  "follower": "aphadon, echil",
  "followers": "aphadrim",
  "food": "aes, mann",
  "foot": "tâl",
  "feet": "tâl",
  "footprint": "ruin",
  "footstool": "tharas",
  "for": "an, an-",
  "for me": "anim",
  "forest": "taur, eryn, tawar",
  "forests": "taur, eryn, tawar",
  "forest fire": "erynaur",
  "forest people (silvan elves)": "tawarwaith",
  "forester": "tauron",
  "forge": "tamin",
  "forgive": "dihena-, gohena",
  "forgives": "dihena-, gohena",
  "forgave": "dihena-, gohena",
  "forgiven": "dihena-, gohena",
  "forgiving": "dihena-, gohena",
  "forked": "thanc",
  "formed shaped": "cadu",
  "forsaken": "eglan",
  "forsaken sindar falathrim": "egladhrim",
  "forth out away": "e-, ed-",
  "fortress fort tower": "barad",
  "foul": "thaur",
  "four": "canad",
  "fourth": "cannui, canthui",
  "fox": "rusc",
  "foxes": "rusc",
  "free release": "adleitha-",
  "free, freed": "lain",
  "freeing, release": "leithian",
  "frequent, many": "laew",
  "fresh": "laeb, cîw",
  "fresh green": "laeg",
  "friend": "mellon, meldir, seron",
  "friends": "mellon, meldir, seron",
  "friend (fem.)": "meldis",
  "friendly, loving, kind": "milui",
  "frog": "cabor",
  "frogs": "cabor",
  "from": "o",
  "frown": "nifrad",
  "frowns": "nifrad",
  "frowned": "nifrad",
  "frowning": "nifrad",
  "frozen": "helegnen",
  "fruit": "fêr, mirda-",
  "fruits": "fêr, mirda-",
  "full": "pant",
  "fullness": "pathred",
  "fungus, sponge": "hwand",
  "fur": "heleth",
  "fury": "gruith",

  // --- G ---
  "gap opening mountain pass": "dîn",
  "garden": "sant",
  "gardens": "sant",
  "garment": "hamp",
  "garments": "hamp",
  "garth": "pêl",
  "gate": "annon",
  "gates": "annon",
  "gateway door": "fennas",
  "gaze": "tir-, tiria-",
  "gazes": "tir-, tiria-",
  "gazed": "tir-, tiria-",
  "gazing": "tir-, tiria-",
  "germ seed": "eredh",
  "girl": "sell, wen",
  "girls": "sell, wen",
  "give": "anna, anna-",
  "gives": "anna, anna-",
  "gave": "anna, anna-",
  "given": "anna, anna-",
  "giving": "anneth, anna, anna-",
  "glance": "glind, glinna, henn, tîr",
  "glances": "glind, glinna, henn, tîr",
  "glanced": "glind, glinna, henn, tîr",
  "glancing": "glind, glinna, henn, tîr",
  "glass": "heledh",
  "gleaming brilliance": "fael",
  "glen, deep valley": "imlad",
  "glint": "tinna-",
  "glint of light": "glîn",
  "glisten": "thilia-",
  "glistens": "thilia-",
  "glistened": "thilia-",
  "glistening": "thilia-",
  "glitter brilliance glory": "aglar",
  "glittering pale": "gael",
  "glittering white": "silivren",
  "gloom nighttime": "daw",
  "gloom, night": "maur",
  "gloomy sad": "dem",
  "glorify praise": "egleria-",
  "glorious": "aglareb",
  "glory brilliance glitter": "agar",
  "go": "ped, bad-",
  "goes": "ped, bad-",
  "went": "ped, bad-",
  "gone": "ped, bad-",
  "going": "ped, bad-",
  "go to exile": "edledh-, edledhia-",
  "go up": "dol-",
  "goblet": "sûl",
  "goblets": "sûl",
  "god the one": "eru",
  "going up": "am-",
  "gold": "malt, glawar",
  "gold (color?)": "mall",
  "gold (metal)": "malad",
  "gold metal": "côl",
  "golden": "mallen, malthen",
  "golden light": "glaur",
  "golden tree": "mallorn",
  "good": "maer",
  "goose": "gwaun",
  "geese": "gwaun",
  "gorse": "aeglos",
  "grasp, seize": "mab-",
  "grass": "sass, glae",
  "grave": "sarch",
  "graves": "sarch",
  "gravel": "brith",
  "great fear, dread": "goe",
  "great hall": "thamas",
  "great large": "dae",
  "great mighty": "beleg",
  "great number": "lae",
  "great ocean": "gaearon",
  "great sea ocean": "aearon",
  "greedy": "melch",
  "green": "calen",
  "green elf": "laegel",
  "green elves (people)": "laegrim",
  "grey": "thind",
  "grey-elf": "send",
  "gross (144)": "host",
  "grow": "gala-",
  "grows": "gala-",
  "grew": "gala-",
  "grown": "gala-",
  "growing": "gala-",
  "grow toward evening": "thinna-",
  "growth": "galas",
  "guard": "tir-, tiria-",
  "guards": "tir-, tiria-",
  "guarded": "thoren, tir-, tiria-",
  "guarding": "tir-, tiria-",
  "guess, idea, notion": "inc",
  "guest": "althol",
  "guests": "althol",
  "guesthouse": "sennas",
  "guilty wily sinister": "crumguru",
  "gull": "gwael, maew",
  "gulls": "gwael, maew",
  "gulp": "yll",

  // --- H ---
  "hack through": "hasta",
  "hail": "ai, suil",
  "hair lock of hair tress": "fîn",
  "half": "per-",
  "half-elf": "peredhel",
  "halfling": "perian",
  "hall": "tham",
  "halls": "tham",
  "halt stop": "dar-",
  "hammer": "dam, damma-, dring",
  "hammers": "dam, damma-, dring",
  "hand": "cam, mâb",
  "hands": "cam, mâb",
  "hands palm": "camlann",
  "handy, skilled": "maed",
  "hang": "glinga",
  "hangs": "glinga",
  "hung": "glinga",
  "hanging": "gling, glinga",
  "harass": "trasta-",
  "harborage": "hobas",
  "harbour, haven, small landlocked bay": "hûb",
  "hard": "norn",
  "hare": "laboth",
  "harp, play a harp": "ganna, gannada",
  "harp": "gannel",
  "harps": "gannel",
  "harper": "talagan",
  "hasp": "taew",
  "hassock": "tharas",
  "hasty, vigorous, impetuous": "gorn",
  "hat": "carab",
  "hate": "delos",
  "hates": "delos",
  "hated": "delos",
  "hating": "delos",
  "have": "gar",
  "has": "gar",
  "had": "gar",
  "having": "gar",
  "have an impulse, begin suddenly and vigorously": "heria",
  "have knowledge": "ista",
  "haven": "círbann",
  "having willows": "tathren",
  "hawk": "heledir",
  "he": "e, hon",
  "head": "dôl",
  "heads": "dôl",
  "head hill": "dôl",
  "headland cape": "cast",
  "healer": "nestad",
  "healers": "nestad",
  "health": "nestas",
  "hear": "lhaw",
  "hears": "lhaw",
  "heard": "lhaw",
  "hearing": "lhaw",
  "heart": "gûr, hûn",
  "hearts": "gûr, hûn",
  "hearth": "naus",
  "heat": "ûr",
  "heaven": "menel",
  "heavy": "long",
  "hedge": "cai",
  "hedge of spikes": "caraes",
  "height": "taen",
  "heir": "hîl",
  "hell": "udûn",
  "hello": "ae",
  "helm": "thôl",
  "helmet": "thôl, harn",
  "helmets": "thôl, harn",
  "her": "dîn",
  "herb": "salab",
  "herbs": "salab",
  "hero": "callon, thalion",
  "heroes": "callon, thalion",
  "hers": "dîn",
  "herself": "he-chim",
  "hew": "drava-",
  "hewn log": "drafn",
  "hidden": "múrauth, thoren, thurin",
  "hidden secret": "dolen",
  "hidden, veiled, shadowed": "hall",
  "hideous": "uanui, ul-",
  "hideous creature": "ulunn",
  "high": "taur",
  "hill": "amon, moeth",
  "hills": "amon, moeth",
  "hill steep sided mount": "amon",
  "himself": "e-chim",
  "hindmost part": "tele",
  "his": "dîn",
  "historical": "gobenathren",
  "history": "gobennas, pennas",
  "hobbit": "perian",
  "hobbits": "perian",
  "holder": "taew",
  "hole": "gas, torech",
  "holes": "gas, torech",
  "holly": "ereg, eregdos",
  "hollow": "coll",
  "home": "bar",
  "homes": "bar",
  "honey": "glî",
  "hop": "laba",
  "hope": "estel, hartha, harthad",
  "hopes": "estel, hartha, harthad",
  "hoped": "estel, hartha, harthad",
  "hoping": "estel, hartha, harthad",
  "hope based on reason": "amdir",
  "horizon": "tiriw",
  "horn": "till",
  "horns": "till",
  "horrible": "gortheb",
  "horrible loathsome": "deleb",
  "horror": "angos, girith, gorog, goroth",
  "horror, fear, dread": "gôr",
  "horse": "roch, lobor",
  "horses": "roch, lobor",
  "hot": "úr, born, úrui",
  "hound of chase": "rýn",
  "hour": "lú",
  "hours": "lú",
  "house": "adab",
  "houses": "adab",
  "household, troop under a lord": "herth",
  "how": "man",
  "how many": "lim",
  "how much": "man",
  "howl": "gawa",
  "howls": "gawa",
  "howled": "gawa",
  "howling": "gawad, gawa",
  "human": "firen",
  "hummock": "gwastar",
  "hundred": "mimp",
  "hunt": "fara-",
  "hunts": "fara-",
  "hunted": "fara-",
  "hunting": "fara-",
  "hunt hunting": "farad, faras",
  "hunter": "faron, feredir",
  "hunters": "faroth",
  "hunters people": "faradrim",
  "hurl": "had",
  "husband": "hervenn",
  "husbands": "hervenn",
  "hymn": "aerlinn",

  // --- I ---
  "i": "ni, im",
  "ice": "heleg",
  "icicle": "aeglos",
  "if": "ae",
  "ill deed": "úgarth",
  "ill, sick, sickly": "lhaew",
  "immortal name of flower": "alfirin",
  "impetuous rushing": "alag",
  "impetus": "gorf",
  "in": "mi, vi",
  "incite": "meltha-",
  "incline": "talad",
  "index finger": "lebdas",
  "inner mind, heart": "gûr",
  "inner thought, mind, meaning, heart": "ind",
  "insecure": "talt",
  "instead": "sennui",
  "insult": "eithad",
  "insult prick with sharp point": "eitha-",
  "intelligent": "hand",
  "intend": "thel-",
  "intention": "thelion",
  "iron": "ang",
  "is": "na",
  "island": "tol, toll",
  "islands": "tol, toll",
  "isolated lonely": "ereb",
  "issue of water spring well": "eithel",
  "it": "ta",
  "its": "tîn",
  "itself": "te-chim",

  // --- J ---
  "jaw": "ank",
  "jaws": "ank",
  "jaw row of teeth": "anc, carach",
  "jewel": "mîr, miriel",
  "jewels": "mîr, miriel",
  "journey": "lend",
  "journeys": "lend",
  "journey, way": "lend",
  "joy": "glass, gell",
  "jubilation": "gellam",
  "judge": "badhor, badhron",
  "judgment sentence": "baudh",
  "juice": "paich, saw",
  "july": "cerveth",

  // --- K ---
  "keep, retain": "heb",
  "keep": "heb",
  "keeps": "heb",
  "kept": "heb",
  "keeping": "heb",
  "khuzdûl": "hadhodren",
  "kindler (fem.)": "thoniel",
  "king": "aran, taur",
  "kings": "aran, taur",
  "kingfisher (bird)": "heledir",
  "kingdom": "aranarth, arnad",
  "kingdoms": "aranarth, arnad",
  "kingdom realm": "aranarth",
  "kingsfoil": "athelas",
  "kinsman, kinswoman": "gwanur",
  "kiss": "mîb, mib-",
  "kisses": "mîb, mib-",
  "kissed": "mîb, mib-",
  "kissing": "mîb, mib-",
  "knife": "sigil",
  "knives": "sigil",
  "knock": "tamma-",
  "knocks": "tamma-",
  "knocked": "tamma-",
  "knocking": "tamma-",
  "know": "ista",
  "knows": "ista",
  "knew": "ista",
  "known": "ista",
  "knowing": "ista",
  "knowledge": "ist",
  "knowledge, lore": "ist",

  // --- L ---
  "lady": "brennil, heryn, hiril",
  "ladies": "brennil, heryn, hiril",
  "lair": "caew, torech",
  "lake": "aelin",
  "lakes": "aelin",
  "lake pool": "ael",
  "lake, pool": "lîn",
  "lamp": "calar, naur",
  "lamps": "calar, naur",
  "lampwright": "calardan",
  "land": "dôr",
  "lands": "dôr",
  "land dwelling place region": "dôr",
  "lands of middle earth": "ennorath",
  "large": "daer",
  "last": "medui",
  "last day of the year": "penninor",
  "last survive": "brona-",
  "laugh": "gladh, gladha",
  "laughs": "gladh, gladha",
  "laughed": "gladh, gladha",
  "laughing": "gladh, gladha",
  "laughter": "lalaith",
  "lead": "tog-",
  "leads": "tog-",
  "led": "tog-",
  "leading": "tog-",
  "leaf": "lass",
  "leaves": "lass", // (as in tree leaves)
  "leave": "gwanna", // (verb)
  "left (verb)": "gwanna",
  "leaving": "gwanna",
  "league pause stop": "daur",
  "lean, thin, meager": "lhain",
  "leap": "cab-, cabed",
  "leaps": "cab-, cabed",
  "leapt": "cab-, cabed",
  "leaped": "cab-, cabed",
  "leaping": "cab-, cabed",
  "leaping down": "thôr",
  "learn": "gelia",
  "learns": "gelia",
  "learned": "istui, gelia",
  "learnt": "gelia",
  "learning": "gelia",
  "learned in deep arts, wise": "golwen",
  "least": "alacha",
  "left": "crom, hair",
  "left (direction)": "hâr",
  "left behind": "lefn",
  "left hand": "crum, hair",
  "left hand, left side": "harvo",
  "left-handed": "crumui, hargam",
  "less": "aksa",
  "letter": "têw",
  "letters": "têw",
  "level, open space": "land",
  "lick": "lav-",
  "licks": "lav-",
  "licked": "lav-",
  "licking": "lav-",
  "lie": "gwaur",
  "lies": "gwaur",
  "lied": "gwaur",
  "lying": "gwaur",
  "lie on the ground": "caeda-",
  "life": "cuin, cuil",
  "lives (noun)": "cuin, cuil",
  "lift": "hal",
  "lifts": "hal",
  "lifted": "hal",
  "lifting": "hal",
  "light": "calad, gail, gal-, naur, naurim",
  "lights": "calad, gail, gal-, naur, naurim",
  "light bright": "gail",
  "light bright sunlight brilliance radiance glittering reflection": "galad",
  "light, lantern": "naur",
  "lightning": "glawar",
  "like": "sui",
  "like silver": "celebren",
  "limit": "taeg, glenia",
  "limits": "taeg, glenia",
  "line": "tê, tî",
  "lines": "tê, tî",
  "line, row": "lîr",
  "link, articulation": "lîf",
  "listen": "lasta-",
  "listens": "lasta-",
  "listened": "lasta-",
  "listening": "lasta-",
  "little": "tithen",
  "little brother, also the name of the middle finger": "honeg",
  "little kiss": "mib",
  "live": "cuina, cuia-",
  "lives (verb)": "cuina, cuia-",
  "lived": "cuina, cuia-",
  "living": "cuina, cuia-",
  "lively sudden quick": "brêg",
  "loaf round bread": "basgorn",
  "load": "cûl",
  "loads": "cûl",
  "local": "trannail",
  "lock of hair": "fing",
  "lock of hair tress": "find",
  "lofty": "taur",
  "lone alone one": "er-",
  "long": "and",
  "long and thin": "taen",
  "long for a long time": "anann",
  "long mark": "andaith",
  "long year valian year": "ennin",
  "longbeard tribe of dwarves": "anfang",
  "longbeards people": "anfangrim",
  "look": "thîr",
  "looks": "thîr",
  "looked": "thîr",
  "looking": "tîr, thîr",
  "look toward": "tiria-",
  "lord": "brannon, tûr",
  "lords": "brannon, tûr",
  "lord, master": "hîr",
  "love": "mîl, mel-, meleth",
  "loves": "mîl, mel-, meleth",
  "loved": "mîl, mel-, meleth",
  "loving": "mîl, mel-, meleth",
  "lover": "seron",
  "lovers": "seron",
  "lover (fem.)": "melethril",
  "lover (masc.)": "melethron",
  "low": "dad, tofn",
  "low gloomy": "dofn",
  "low, flat field": "talf",
  "low-lying": "tofn",
  "loyal": "thenid",
  "lust": "mael",
  "lustful": "maelui",
  "lying in bed sickness": "cael",

  // --- M ---
  "magic": "gûl, mul",
  "magic deep lore": "angol",
  "magic metal that only mirrors starlight and moonlight": "ithildin",
  "maid": "sell",
  "maids": "sell",
  "maiden": "gwend, wen",
  "maidens": "gwend, wen",
  "make": "car, tan-",
  "makes": "car, tan-",
  "made": "car, tan-",
  "making": "car, tan-",
  "make come": "toltha-",
  "make firm": "tangada-",
  "maker": "tân?",
  "male": "anu",
  "male adult male": "dîr",
  "man": "adan",
  "men": "adan",
  "man husband": "benn",
  "man spearhead": "dírnaith",
  "many": "laew",
  "maple": "lalorn",
  "march": "gwaeron",
  "mark": "tagol, taith",
  "marks": "tagol, taith",
  "marking (a boundary)": "taig",
  "mass of ice": "gochel",
  "master": "herdir, heron, tûr",
  "masters": "herdir, heron, tûr",
  "master of stone, dwarf": "gonhir",
  "mastery": "tûr",
  "may": "lothron",
  "mayor": "condir",
  "me": "nin",
  "mean": "thel-",
  "means": "thel-",
  "meant": "thel-",
  "meaning": "thel-",
  "meat": "rhaw",
  "meet": "govad",
  "meets": "govad",
  "met": "govannen, govad",
  "meeting": "govad",
  "memory": "rîn",
  "memories": "rîn",
  "merry": "gelir",
  "metal": "tinc",
  "metals": "tinc",
  "middle earth": "ennor",
  "middle finger": "lebenedh, toleg",
  "midnight": "dúath",
  "midyear": "enedhin",
  "milk": "glûth",
  "mind": "ind",
  "minds": "ind",
  "mine": "nín",
  "minute": "anrand",
  "minutes": "anrand",
  "mirror": "cenedril",
  "mirrors": "cenedril",
  "mirrors, seeing": "ming",
  "mist": "hîth",
  "mist, fog": "hithu",
  "mocking, scorn": "iaew",
  "moisten": "limmida-",
  "monster": "úan, ulunn, urug",
  "monsters": "úan, ulunn, urug",
  "monstrous": "uanui",
  "month": "astar, mis",
  "months": "astar, mis",
  "moon": "ithil, murth",
  "moons": "ithil, murth",
  "more": "am",
  "morning": "aur",
  "mornings": "aur",
  "morning twilight": "minuial",
  "mortal": "fíreb, firin",
  "mortals": "fíreb, firin",
  "mortal humains": "firiath",
  "mortal maiden": "fíriel",
  "mortal man": "fair, firion",
  "mortal woman": "edenith",
  "most": "estar",
  "mother": "naneth, emel",
  "mothers": "naneth, emel",
  "mother finger index": "emig",
  "mound": "tund",
  "mounds": "tund",
  "mound enclosure": "cerin",
  "mountain": "orod",
  "mountains": "orod",
  "mountain peak": "aegas",
  "muscle": "tû",
  "muscles": "tû",
  "music": "lind",
  "must": "boe",
  "my": "nín",
  "myself": "imin",
  "mystery": "dolen",
  "mysteries": "dolen",

  // --- N ---
  "nail": "taes",
  "nails": "taes",
  "naked": "hell, lanc",
  "name": "eneth",
  "names": "eneth",
  "nandor": "danwaith, denwaith",
  "narrative poem": "glaer",
  "narrow": "agor",
  "near": "neled",
  "neck": "achad, iaeth",
  "necks": "achad, iaeth",
  "necklace": "sigil",
  "necklaces": "sigil",
  "need": "baur, thang",
  "needs": "baur, thang",
  "needed": "baur, thang",
  "needing": "baur, thang",
  "net, web": "gwî",
  "never": "ú-, ui",
  "new": "dess, eden, gwain, sain",
  "new moon": "cýron",
  "news": "siniath",
  "night": "dû, mor, no, nuin, nusil, nythw",
  "nights": "dû, mor, no, nuin, nusil, nythw",
  "nightingale": "dúlinn, merilin, tinúviel",
  "nightingales": "dúlinn, merilin, tinúviel",
  "nightmare": "fuinôl",
  "nightmares": "fuinôl",
  "nightshade": "mortha, nusiloth, nuthus, nythil",
  "nine": "neder",
  "no": "baw, law",
  "no dont": "baw",
  "no! don't!": "law",
  "noble": "arod, taur",
  "noble high royal": "ar-, ara-",
  "noble lady": "arwen",
  "noble man": "arphen",
  "noble royal": "arn",
  "noldo": "gódhel, golodh",
  "noldo jewel (silmaril)": "golovir",
  "noldor (people)": "gódhellim, golodhrim",
  "noon": "andúnë",
  "north": "forod, fôr",
  "north direction": "forven",
  "north right": "fôr",
  "northern": "fervain",
  "northmen northfolk": "forodrim",
  "northmen northfolk north regions": "forodwaith",
  "not": "ú, al-, ú-",
  "nourished": "mod",
  "novel": "sinnarn",
  "november": "hithui",
  "now": "si",
  "number": "gwanod",
  "numbers": "gwanod",
  "numberless unnumbered": "arnediad",
  "númenórean man of the west": "dúnadan",

  // --- O ---
  "o": "interj.",
  "oak": "doron",
  "oak tree": "doron",
  "oath": "gwest",
  "oaths": "gwest",
  "obscure, foggy, vague": "hethu",
  "obstinate": "tarlanc",
  "ocean": "eär",
  "oceans": "eär",
  "ocean sea": "aear, gaear",
  "odor": "ûl",
  "odors": "ûl",
  "of": "en",
  "of copper": "rustui",
  "of crystal": "ivorcheneb, ivren",
  "of iron": "angren",
  "of silver": "celevon",
  "of stone": "gonui",
  "of the shore": "falathren",
  "of willow": "tathren",
  "of wool": "taw",
  "oiolossë": "uilos",
  "old": "iaur",
  "old worn": "brûn",
  "on": "or, bo",
  "on both sides": "ath-",
  "one": "min, er, mîn, pen",
  "one handed": "erchamion, erchammon",
  "one-handed": "erchammui",
  "oneself": "im",
  "only": "erui",
  "open": "edra-, panna-",
  "opens": "edra-, panna-",
  "opened": "edra-, panna-",
  "opening": "edra-, panna-",
  "oppressive cruel tyrannous": "baug",
  "oppression": "thang",
  "or": "egor",
  "orc": "glamog, urug",
  "orcs": "glamog, urug",
  "orient sunrise east": "amrún",
  "orkish": "erchion",
  "other": "edraith",
  "others": "edraith",
  "our": "vín",
  "ours": "vín",
  "ourselves": "mchim",
  "outlaws": "gaurwaith",
  "outline shape": "cant",
  "outer ring circle": "echor",
  "outside without": "ar-",
  "over": "or, thar-",
  "owl": "cugu",
  "owls": "cugu",
  "own": "ben, garn",

  // --- P ---
  "pain": "naeg",
  "pains": "naeg",
  "pair of ears": "lhaw",
  "pair of twin": "gwanûr, gwenyn",
  "pair of twins": "gwanûn",
  "palantir, seeing stone": "gwachaedir",
  "pale": "thind",
  "pale blue": "elu",
  "pale, fawn": "maidh",
  "palm (hand)": "talf",
  "paradise": "valinor",
  "path": "imrad",
  "paths": "imrad",
  "pathway beaten track": "bâd",
  "peace": "sîdh",
  "peak": "mîn",
  "peaks": "mîn",
  "peak horn": "aeg",
  "pear": "mir",
  "pears": "mir",
  "pebbly": "brithon",
  "pedlar": "bachor",
  "peeble-bank": "serni",
  "pen": "tegil",
  "pens": "tegil",
  "people of doriath": "iathrim",
  "people of the falas": "falathrim",
  "people of the south": "haradrim",
  "people of the trees, elves of lórien": "galadhrim",
  "permission": "dâf",
  "petrel": "paen",
  "physical strength": "tû",
  "pick up, pick out": "leutha-",
  "pile of stones": "sarnas",
  "pillar (wood)": "thafn",
  "pimpernel flower": "elanor",
  "pin": "tachol",
  "pins": "tachol",
  "pine": "thôn",
  "pines": "thôn",
  "pine-tree": "thaun, thôn",
  "pipe-weed": "galenas",
  "pivot": "pelthaes",
  "plain": "talath",
  "plains": "talath",
  "plane": "talath",
  "plank": "pân",
  "plant bush": "aiglos",
  "play": "teilia-, telia-",
  "plays": "teilia-, telia-",
  "played": "teilia-, telia-",
  "playing": "teilia-, telia-",
  "pleasure": "gell",
  "point": "till",
  "points": "till",
  "point of spear": "aith, thela",
  "point spear point": "ecthel",
  "pointe": "ment",
  "poison": "saew",
  "poisons": "saew",
  "pollen, yellow powder": "main",
  "pondering, wise, thoughtful": "idhren",
  "pool": "loeg",
  "pools": "loeg",
  "poplar tree": "tulus",
  "potter": "cennan",
  "power": "bellas, tûr",
  "powers": "bellas, tûr",
  "precious": "miru",
  "prick point stick": "ercha-",
  "prickle": "erch",
  "prince": "cund, ernil",
  "princes": "cund, ernil",
  "prohibition": "ablad eblaid",
  "promise": "vanda",
  "promises": "vanda",
  "promised": "vanda",
  "promising": "vanda",
  "province great region": "ardhon",
  "puddle small pool": "both",
  "purpose": "thel, thelion",
  "purposes": "thel, thelion",

  // --- Q ---
  "quarrel": "cost",
  "quarrels": "cost",
  "queen": "bereth",
  "queens": "bereth",
  "quench": "luithia-",
  "quest": "tûr",
  "quests": "tûr",
  "quickly": "celeg",

  // --- R ---
  "rabbit": "cabor",
  "rabbits": "cabor",
  "radiance": "glaw",
  "radiant": "faen",
  "rain": "ross, eilia-",
  "rains": "ross, eilia-",
  "rained": "ross, eilia-",
  "raining": "ross, eilia-",
  "rainbow": "ninniach, eilian",
  "rainbows": "ninniach, eilian",
  "rainbow bow": "eiliant",
  "range of mountain peaks": "aeglir",
  "ransom": "danwedh",
  "rapid, swift": "legrin",
  "rather": "sennui",
  "raven": "craban",
  "ravens": "craban",
  "reap": "critha-",
  "reaps": "critha-",
  "reaped": "critha-",
  "reaping": "critha-",
  "rear": "tele",
  "recite": "glir",
  "recites": "glir",
  "recited": "glir",
  "reciting": "glir",
  "reckon": "genedia",
  "recount": "trenar-",
  "red": "caran",
  "red scarlet": "coll",
  "reddish copper coloured ruddy": "gaer",
  "reed": "lisc",
  "refusal reluctance": "avad",
  "regional": "trannail",
  "relative, brother": "gwanûr",
  "renewed": "cŷr",
  "renewal": "cîl",
  "repose, rest": "îdh",
  "resolve": "thel-",
  "resonant (of strings)": "tong",
  "rest": "hoda, sedh-",
  "rests": "hoda, sedh-",
  "rested": "hoda, sedh-",
  "resting": "hoda, sedh-",
  "reunion": "aderthad",
  "reunite": "adertha-",
  "ridge": "gondrafn",
  "ridges": "gondrafn",
  "rigid": "tharn",
  "rill": "sîr",
  "ring": "corf",
  "rings": "corf",
  "ring finger": "lebent",
  "ringlet": "laus, loch",
  "rise arise": "eria-",
  "river": "sirion, celon, sîr",
  "rivers": "sirion, celon, sîr",
  "river city": "minas-nim",
  "river large river with current": "duin",
  "riverbank": "duirro",
  "road": "men",
  "roads": "men",
  "road, way": "mên",
  "robust": "tarch",
  "rock": "gond",
  "rocks": "gond",
  "roof": "toba-, tobas",
  "roofs": "toba-, tobas",
  "root": "thond",
  "roots": "thond",
  "root (edible)": "solch",
  "rose": "meril",
  "rotten": "thaw",
  "rough": "raw",
  "row": "tê, tî",
  "rows": "tê, tî",
  "royal": "arnen",
  "ruddy": "gruin",
  "ruddy of face": "crann",
  "rune": "certh",
  "runes": "certh",
  "runic alphabet": "angerthas",
  "run": "pad-", // added generically
  "runs": "pad-",
  "ran": "pad-",
  "running": "pad-",
  "rustling sound, whisper": "lhoss",

  // --- S ---
  "sailor shipman": "cirion",
  "salt": "singol",
  "salve": "glaew",
  "same": "im",
  "sapless": "tharn",
  "saving salvation": "edraith",
  "say": "ped-",
  "says": "ped-",
  "said": "ped-",
  "saying": "ped-",
  "sea": "aear, aer, gaer",
  "seas": "aear, aer, gaer",
  "sea serpent, fish dragon": "limlug",
  "sea-breeze": "mistral",
  "seashell": "half",
  "season of fading autumn": "firith",
  "season of stirring spring": "echuir",
  "season of summer": "laer",
  "seaweed": "aeruil, uil",
  "sea weed": "gaeruil",
  "second": "redein, edwen, tadui",
  "seconds": "redein, edwen, tadui",
  "second in command": "taid",
  "secrecy": "murtha",
  "secret": "thurin",
  "secrets": "thurin",
  "see": "cen, cen-",
  "sees": "cen, cen-",
  "saw": "cen, cen-",
  "seen": "cen, cen-",
  "seeing": "cen, cen-",
  "seed": "cordof",
  "seeds": "cordof",
  "seek": "cest-", // added generically
  "seeks": "cest-",
  "sought": "cest-",
  "seeking": "cest-",
  "seem": "thia-",
  "seems": "thia-",
  "seemed": "thia-",
  "seeming": "thia-",
  "seize": "maba-",
  "seizes": "maba-",
  "seized": "maba-",
  "seizing": "maba-",
  "self": "im",
  "send": "menna-",
  "sends": "menna-",
  "sent": "menna-",
  "sending": "menna-",
  "september": "ivanneth",
  "serve hold allegiance": "buia-",
  "set": "penia-",
  "sets": "penia-",
  "setting": "penia-",
  "set aside": "seidia-",
  "set free, release": "leithia-",
  "seven": "odog",
  "sexual desire": "îr",
  "shade": "nythl",
  "shades": "nythl",
  "shade, dark place": "nyra, nefu",
  "shade, shadow": "nefu",
  "shade, shadow, dim light": "gwâth",
  "shadow": "gwath, dae, lum, moth, núath, nûrath, núrwath, ngaust, núthl, nûthlûn",
  "shadows": "gwath, dae, lum, moth, núath, nûrath, núrwath, ngaust, núthl, nûthlûn",
  "shadow, black": "nûthlûn",
  "shadow, dark place": "nyra",
  "shadowy": "gwathui, nguarûn",
  "shady": "lumren",
  "shady, shadowy": "nefro, núrûn",
  "shaggy hair": "fast",
  "shallow": "tofn",
  "shallow lake": "lô",
  "shapely": "cadwar, maed",
  "shaping": "cannas",
  "sharp": "laeg",
  "sharp edge, sudden end, brink": "lanc",
  "sharp horn": "till",
  "sharp point": "egnas",
  "sharp pointed": "aeg",
  "sharp, penetrating": "maeg",
  "sharp, pointed, piercing": "megor",
  "sharp-eyed": "maecheneb",
  "shaven": "paran",
  "she": "he, hen, hene",
  "shield": "thand",
  "shields": "thand",
  "shield fence": "thangail",
  "shield wall": "amath, thangail",
  "shine white": "síla-",
  "shine": "síla-",
  "shines": "síla-",
  "shone": "síla-",
  "shining": "síla-",
  "ship": "cair",
  "ships": "cair",
  "shipbuilder": "círdan",
  "shire": "trann",
  "shore": "habad",
  "shores": "habad",
  "shore beach": "faur",
  "short": "estent, then, thent",
  "shortness": "thinnas",
  "should": "garo",
  "shout": "caun",
  "shouts": "caun",
  "shouted": "caun",
  "shouting": "caun",
  "shout, cry": "ial",
  "shudder": "gir",
  "shudders": "gir",
  "shuddered": "gir",
  "shuddering": "gir",
  "sickle": "cerch",
  "sickly": "gem",
  "sickness": "lhîw, paw",
  "sight seeing": "cened",
  "sign": "tann, têw",
  "signs": "tann, têw",
  "silence": "dîn",
  "silent": "dínen",
  "silima": "silef",
  "silmaril": "silevril",
  "silver": "celeb, mith, gildin",
  "silver-haired": "mithrils",
  "sin": "úgarth",
  "sins": "úgarth",
  "sinda (of doriath)": "iathron",
  "sinda one of the forsaken": "egol",
  "sindar": "eluwaith",
  "sing": "glir, liria-",
  "sings": "glir, liria-",
  "sang": "glir, liria-",
  "sung": "glir, liria-",
  "singing": "glir, liria-",
  "single first alone": "er",
  "single flower": "elloth, lotheg",
  "sister": "muinthel, gwathel, thêl",
  "sisters": "muinthel, gwathel, thêl",
  "sit": "haf, hav",
  "sits": "haf, hav",
  "sat": "haf, hav",
  "sitting": "haf, hav",
  "six": "eneg, engui",
  "sixth": "enchui",
  "skilled handy": "flâd",
  "sky": "menel",
  "skies": "menel",
  "slant down": "penna-",
  "slant down inclined": "dadbenn",
  "slant slope": "adlanna-",
  "slanting oblique": "adlant",
  "slain": "dangen",
  "slay": "dag-",
  "slays": "dag-",
  "slew": "dag-",
  "slaying": "dag-",
  "sleep": "lor, losta-",
  "sleeps": "lor, losta-",
  "slept": "lor, losta-",
  "sleeping": "lor, losta-",
  "slender": "trîw",
  "slender, fine": "lhind",
  "slim slender": "fim",
  "sling": "hadlath",
  "slipping": "talt",
  "slope": "pend",
  "slopes": "pend",
  "sloping tilted": "adlann, adlod",
  "slot": "ruin",
  "slow": "lorn",
  "slowly": "lorn",
  "small bird": "filigod",
  "small finger": "lebig",
  "small red apple": "cordof",
  "smell": "thost",
  "smells": "thost",
  "smelled": "thost",
  "smelt": "thost",
  "smelling": "thost",
  "smile": "lalaith",
  "smiles": "lalaith",
  "smiled": "lalaith",
  "smiling": "lalaith",
  "smith": "taegor",
  "smiths": "taegor",
  "smoke": "osp",
  "smooth": "path, paran",
  "snake": "lhûg, lýg",
  "snakes": "lhûg, lýg",
  "snake serpent": "amlug",
  "snout nose": "bund",
  "snow": "loss",
  "snow men (people)": "lossoth",
  "snowy": "lossen",
  "soaking wet": "loen",
  "soap": "glûdh",
  "socket": "taew",
  "soft": "moe, mae",
  "soil": "cêf",
  "soil, stain": "gwatha, maw",
  "soldier orkish": "daug",
  "sole of the foot": "telluin",
  "some": "min",
  "somebody": "pen",
  "son": "ion",
  "sons": "ion",
  "song": "glîr, laer",
  "songs": "glîr, laer",
  "sorcery": "morr",
  "sorrow": "naergon",
  "sorrows": "naergon",
  "soul": "fae",
  "souls": "fae",
  "soul spirit": "fae",
  "soup": "salph",
  "source spring": "celu",
  "south": "harad",
  "south, southern": "haradren",
  "southern": "harn",
  "spark": "tint, tinu",
  "sparks": "tint, tinu",
  "sparkling dragon": "faelug",
  "speak": "ped, ped-",
  "speaks": "ped, ped-",
  "spoke": "ped, ped-",
  "spoken": "ped, ped-",
  "speaking": "ped, ped-",
  "spear": "ech",
  "spears": "ech",
  "speech": "peth, mûl",
  "speed, urge on": "hortha",
  "spell": "lûth, luith",
  "spells": "lûth, luith",
  "spider": "ungol",
  "spiders": "ungol",
  "spike": "gondram, till",
  "spikes": "gondram, till",
  "spike tooth of rock": "carag",
  "spine": "ech",
  "spirit": "făe, faer",
  "spirits": "făe, faer",
  "split": "thanc",
  "spoor": "ruin",
  "sport": "teilien",
  "spouse queen": "bereth",
  "spring": "ethuil, tuia-",
  "spring water": "celos",
  "sprout": "tui, tuiw",
  "spy": "ethir",
  "spies": "ethir",
  "stain": "gwass",
  "stains": "gwass",
  "stain, stained": "mael",
  "stained": "gwaen",
  "stair": "dim",
  "stairs": "dim",
  "stairway": "pendrath",
  "stake spike": "ceber",
  "stalwart": "thala",
  "staple": "taew",
  "star": "êl, gîl",
  "stars": "êl, gîl",
  "star sun flower": "elanor",
  "starlight": "gilgalad",
  "staying": "avorn",
  "steadfast": "thalion",
  "steady": "thala",
  "steep": "baradh",
  "steep mountain peak": "tarag",
  "stem": "telch",
  "stems": "telch",
  "stench": "thû",
  "stiff": "tara, tharn",
  "stiff grass": "thâr",
  "stiff tough": "dorn",
  "stiffness": "tarias",
  "stink": "thosta-",
  "stirrup": "talraph",
  "stone": "gond, sarn",
  "stones": "gond, sarn",
  "stonecrop (plant)": "seregon",
  "stop up": "dilia-",
  "stopgap": "gasdil",
  "stopped": "tafnen",
  "stopper stopping": "dîl",
  "stop": "dar-",
  "stops": "dar-",
  "stopping": "dar-",
  "storm": "alagos, gwaew",
  "storms": "alagos, gwaew",
  "storm of wind": "alagos",
  "story": "pent",
  "stories": "pent",
  "straight": "tîr",
  "stranger": "edlon",
  "strangers": "edlon",
  "stream": "celeb",
  "streams": "celeb",
  "stream flowing": "celeth",
  "stream little river": "cel",
  "strength": "bel, bellas",
  "strip": "heltha",
  "strips": "heltha",
  "stripped": "heltha",
  "stripping": "heltha",
  "strong": "bell, thenid",
  "strong in body": "bell",
  "student": "pethron",
  "students": "pethron",
  "sublime": "taur",
  "successor": "dŷr",
  "sudden": "bragol",
  "sudden violent": "bregol",
  "suddenly": "breged",
  "suddenness violence": "breged",
  "suffice": "feiria-",
  "summer": "laer",
  "summers": "laer",
  "summit of high mountain": "taen",
  "sun": "anor",
  "suns": "anor",
  "sunlight": "glawar, malt",
  "sunlight, radiance": "malt",
  "sunset west": "annûn",
  "support": "tulu",
  "supports": "tulu",
  "supported": "tulu",
  "supporting": "taid, tulu",
  "suppose": "inga",
  "supposes": "inga",
  "supposed": "inga",
  "supposing": "inga",
  "surface": "palath",
  "surfaces": "palath",
  "survival": "bronad",
  "swallow": "tuilinn",
  "swallows": "tuilinn",
  "swan": "alph",
  "swans": "alph",
  "sward": "pathu",
  "swear": "gwesta",
  "swears": "gwesta",
  "swore": "gwesta",
  "sworn": "gwesta",
  "swearing": "gwesta",
  "sweet": "melui",
  "swell": "tuia-",
  "swells": "tuia-",
  "swelled": "tuia-",
  "swollen": "tuia-",
  "swelling": "tuia-",
  "swift": "lint",
  "swine": "mur",
  "swooping": "thôr",
  "sword": "megil",
  "swords": "megil",
  "swordsman": "magor",
  "swordsmen": "magor",
  "sworn brother": "gwador",
  "syrup": "paich",

  // --- T ---
  "table": "talfin",
  "tables": "talfin",
  "take": "mab",
  "takes": "mab",
  "took": "mab",
  "taken": "mab",
  "taking": "mab",
  "tale": "sinnarn, trenarn",
  "tales": "sinnarn, trenarn",
  "tall": "tond",
  "tangled": "galadhremmen",
  "tea": "lasguil",
  "teach": "goltha",
  "teaches": "goltha",
  "taught": "goltha",
  "teaching": "goltha",
  "teacher": "istron",
  "teachers": "istron",
  "tear": "nîn",
  "tears": "nîn",
  "teler": "glinnel, teler",
  "teleri (people)": "telerrim",
  "tell": "trenar-",
  "tells": "trenar-",
  "told": "trenar-",
  "telling": "trenar-",
  "tell to end": "trenar-",
  "temptation": "úthaes",
  "ten": "pae, caer",
  "tengwa": "têw",
  "tenth": "paenui",
  "terrify": "gruitha",
  "terrifies": "gruitha",
  "terrified": "gruitha",
  "terrifying": "gruitha",
  "terror": "gost",
  "that": "i, tam, taw?",
  "thatch": "taus",
  "the": "i",
  "the crystal substance of the silmarils": "silef",
  "their": "tîn",
  "theirs": "tîn",
  "them (inanimates)": "hain",
  "themselves": "im",
  "then": "san",
  "there": "ennas",
  "these": "sin",
  "theth": "paenen",
  "they": "hain",
  "thick": "tûg",
  "think": "nauth-", // mapped generic
  "thinks": "nauth-",
  "thought (verb)": "nauth-",
  "thinking": "nauth-",
  "this": "sen",
  "thong": "lath",
  "those": "tai",
  "thought": "nauth", // noun
  "thoughts": "nauth",
  "thoughtfulness": "idhor",
  "thousand": "meneg",
  "thousands": "meneg",
  "three": "nêl",
  "throat": "hell, lanc",
  "throats": "hell, lanc",
  "throne": "hadhod, archam",
  "thrones": "hadhod, archam",
  "through": "tre, godref, trî, tre-",
  "throw": "hador", // generic mapping based on "thrower" hador
  "throws": "hador",
  "threw": "hador",
  "thrown": "hador",
  "throwing": "hador",
  "thrower": "hador",
  "thrower of darts, hurler of darts": "hadron",
  "thumb little father": "atheg",
  "thunder": "rómru",
  "tidings": "siniath",
  "tide": "duinen",
  "tides": "duinen",
  "tie": "taetha-",
  "ties": "taetha-",
  "tied": "taetha-",
  "tying": "taetha-",
  "time": "lû",
  "times": "lû",
  "time, occasion": "lû",
  "tine": "till",
  "to": "na",
  "today": "sír",
  "together": "go, godref, gwa",
  "tomorrow": "ab-ennen",
  "tongue, dialect, language": "lam",
  "too": "aen",
  "top": "caw",
  "tops": "caw",
  "torch": "naurgal",
  "torment": "baul",
  "torments": "baul",
  "torrent": "thórod",
  "touch": "dab",
  "touches": "dab",
  "touched": "dab",
  "touching": "dab",
  "tough": "tara",
  "toughness": "tarias",
  "tower": "minas",
  "towers": "minas",
  "towering": "mîn",
  "town city": "canas, caras",
  "track": "râd, ruin",
  "tracks": "râd, ruin",
  "trade": "banga-",
  "trample": "batha-",
  "tramples": "batha-",
  "trampled": "batha-",
  "trampling": "batha-",
  "traverse cross": "athrada-",
  "trawn folk dwarfs": "dornhoth",
  "tree": "galadh",
  "trees": "galadh",
  "tree (sort of)": "lebethron",
  "tressure hairnet": "cathrae",
  "troll": "torog",
  "trolls": "torog",
  "trouble": "tass, trasta-",
  "troubles": "tass, trasta-",
  "true": "thand",
  "true-silver": "mithril",
  "trust": "bora-",
  "trusts": "bora-",
  "trusted": "bora-",
  "trusting": "bora-",
  "trusty": "tolog",
  "trusty man steadfast man": "bôr",
  "truth": "delw",
  "tuneful, sweet": "lend",
  "twelfth": "yngui",
  "twelve": "ýneg",
  "twi-": "ui-",
  "twilight": "uial, tinnu",
  "twin": "gwanunig",
  "twins": "gwanunig",
  "twirl, whirl, eddy": "hwinia",
  "two": "tâd, ui-",
  "two-legged": "tad-dal",
  "tyranny": "thang",

  // --- U ---
  "ugly": "ul-",
  "under": "nu, di-",
  "understand": "henia",
  "understands": "henia",
  "understood": "henia",
  "understanding": "hannas, henia",
  "union": "erthad",
  "unique": "mîn",
  "unite": "ertha-",
  "universe": "ilúvatar",
  "unquenchable": "uluithiad",
  "uphill": "ambenn",
  "us": "ammen",
  "use": "iuith, iuitha",
  "uses": "iuith, iuitha",
  "used": "iuith, iuitha",
  "using": "iuith, iuitha",

  // --- V ---
  "vala divinity": "balan",
  "valley": "imlad, lât, tûm",
  "valleys": "imlad, lât, tûm",
  "valour": "gorn",
  "vassal follower": "býr",
  "veil screen": "esgal",
  "vengeance": "acharn",
  "verse (poetry)": "tenn",
  "very": "moe",
  "vessel": "calph",
  "vessels": "calph",
  "victor": "tûr",
  "victors": "tûr",
  "victor winner": "degil",
  "victory": "tûr",
  "victories": "tûr",
  "view": "tîr",
  "views": "tîr",
  "vigour": "gôr, tû",
  "village": "gobel",
  "villages": "gobel",
  "vine, wine": "gwîn",
  "violent rushing impetuous": "ascar, asgar",
  "virgin": "wen",
  "virgins": "wen",
  "virginity": "gweneth",
  "vision": "aduial, tírad",
  "visions": "aduial, tírad",
  "voice": "lammen",
  "voices": "lammen",
  "void": "gaw",

  // --- W ---
  "wake": "echuia",
  "wakes": "echuia",
  "woke": "echuia",
  "woken": "echuia",
  "waking": "echuia",
  "wake up": "echuia-",
  "walk": "pada-",
  "walks": "pada-",
  "walked": "pada-",
  "walking": "pada-",
  "wall": "ram",
  "walls": "ram",
  "war": "auth",
  "wars": "auth",
  "war battle": "auth",
  "warm": "laug",
  "warrior": "maethor",
  "warriors": "maethor",
  "was": "ne",
  "waste the one name of god": "eru",
  "waste, wild": "lothren",
  "watch": "tir-, tíra-, tiria-",
  "watches": "tir-, tíra-, tiria-",
  "watched": "tir-, tíra-, tiria-",
  "watching": "tir-, tíra-, tiria-",
  "watcher": "tirn",
  "water": "nen, muin",
  "waters": "nen, muin",
  "waterfall": "lanthir, espalass",
  "waterfalls": "lanthir, espalass",
  "way-bread, journey-bread": "lembas",
  "we": "me",
  "wealth": "mod",
  "weapon": "magor",
  "weapons": "magor",
  "weary": "lom",
  "weep": "nîr-", // generic mapping
  "weeps": "nîr-",
  "wept": "nîr-",
  "weeping": "nîr-",
  "week": "oronor",
  "weeks": "oronor",
  "week of five days": "lefnor",
  "well": "mae",
  "were": "aner",
  "werewolf": "gaur",
  "werewolves": "gaur",
  "werewolf-host": "gaurhoth",
  "west": "annûn, dûn, dúven, annû-",
  "western": "annui",
  "westron": "annúnaid",
  "wet": "loen, mesc, limp",
  "what": "man",
  "when": "îr, ir",
  "where": "mas, ias",
  "which": "man, i",
  "whisper": "hwest, lhoss",
  "whispers": "hwest, lhoss",
  "whispered": "hwest, lhoss",
  "whispering": "hwest, lhoss",
  "white": "nim, fain, glân",
  "white heat": "brass",
  "white hot": "brassen",
  "who": "man, i",
  "who? what?": "man",
  "whole": "pant",
  "whom": "man",
  "whose": "man",
  "why": "man, amman?",
  "wide": "land, pann",
  "wife": "hervess",
  "wives": "hervess",
  "wild man": "drúadan, drû",
  "wild men": "drúath",
  "wilderness": "rhovan",
  "wildfire": "bregedúr",
  "will": "innas, thel",
  "will not": "ava-",
  "willow": "tathar",
  "willows": "tathar",
  "wily cunning": "coru",
  "wind": "gwaew, sûl",
  "winds": "gwaew, sûl",
  "window": "henneth",
  "windows": "henneth",
  "windy": "gwaeren",
  "wine": "gwin",
  "winter": "rhîw",
  "winters": "rhîw",
  "wisdom": "nauth, golu",
  "wise": "idhren, goll",
  "wise man": "gollor",
  "wish": "iest",
  "wishes": "iest",
  "wished": "iest",
  "wishing": "iest",
  "wither": "pel-",
  "withers": "pel-",
  "withered": "tharn, pel-",
  "withering": "peleth, pel-",
  "within": "im",
  "without": "ú, ar-, pen",
  "wizard": "istar, curunír, ithron",
  "wizards": "istar, curunír, ithron",
  "wolf": "draug, araf, garaf",
  "wolves": "draug, araf, garaf",
  "wolf-howl": "gaul",
  "woman": "edenith",
  "women": "edenith",
  "woman wife": "bess",
  "wood": "glad, taw",
  "woods": "glad, taw",
  "wood forest": "eryn",
  "wooden": "tawaren",
  "woodpecker": "tavor",
  "wool": "taw",
  "woolen": "taw",
  "word": "peth",
  "words": "peth",
  "world": "ambar, amar",
  "worlds": "ambar, amar",
  "worn": "gern",
  "worry": "trass",
  "worries": "trass",
  "worried": "trass",
  "worrying": "trass",
  "wound": "harna, haru",
  "wounds": "harna, haru",
  "wounded": "harn, harna, haru",
  "wright": "thavron",
  "write": "teitha-",
  "writes": "teitha-",
  "wrote": "teitha-",
  "written": "teitha-",
  "writing": "teitha-",
  "wrong mistake": "athranna-",

  // --- Y ---
  "yard": "sant",
  "yards": "sant",
  "year": "idhrinn, în",
  "years": "idhrinn, în",
  "year sick, old": "ingem",
  "yelling-horde": "glamhoth",
  "yellow": "malen",
  "yellow bird yellowhammer": "emlin",
  "yes": "mae",
  "yesterday": "tolothen",
  "you": "le",
  "young": "neth",
  "young maiden": "dess",
  "your": "lín",
  "yours": "lín"
};

export default elvishDictionary;