const elvishDictionary = {
        sunlight: "glawar",
        gold: "malt",
        bound: "naud",
        limit: "taeg",
        star: "êl",
        moon: "ithil",
        sun: "anor",
        tree: "galadh",
        water: "nen",
        fire: "naur",
        earth: "ceven",
        air: "gwaeth",
        mountain: "orod",
        forest: "taur",
        river: "sirion",
        sky: "menel",
        cloud: "fain",
        rain: "ross",
        wind: "gwaew",
        stone: "gond",
        sword: "megil",
        bow: "cû",
        arrow: "pilin",
        shield: "thand",
        king: "aran",
        queen: "bereth",
        elf: "edhel",
        man: "adan",
        dwarf: "nogoth",
        wizard: "istar",
        friend: "mellon",
        enemy: "goth",
        love: "mîl",
        hate: "delos",
        beauty: "bain",
        darkness: "môr",
        light: "calad",
        shadow: "gwath",
        night: "dû",
        day: "aur",
        year: "idhrinn",
        sea: "aear",
        hand: "cam",
        eye: "hen",
        heart: "gûr",
        head: "dôl",
        horse: "roch",
        bird: "aew",
        dragon: "amlug",
        silver: "celeb",
        iron: "ang",
        green: "calen",
        blue: "luin",
        red: "caran",
        white: "nim",
        black: "morn",
        house: "adab",
    door: "annon",
    window: "henneth",
    road: "men",
    bridge: "iant",
    city: "ost",
    village: "gobel",
    wall: "ram",
    gate: "annon",
    tower: "minas",
    throne: "hadhod",
    crown: "rî",
    jewel: "mîr",
    song: "glîr",
    music: "lind",
    dance: "lilth",
    book: "parf",
    word: "peth",
    name: "eneth",
    father: "adar",
    mother: "naneth",
    brother: "muindor",
    sister: "muinthel",
    son: "ion",
    daughter: "sell",
    child: "hên",
    warrior: "maethor",
    smith: "taegor",
    healer: "nestad",
    teacher: "istron",
    student: "pethron",
    wise: "idhren",
    strong: "bell",
    fast: "laeg",
    slow: "lorn",
    old: "iaur",
    young: "neth",
    new: "dess",
    good: "maer",
    evil: "úgar",
    true: "thand",
    false: "gog",
    high: "taur",
    low: "dad",
    long: "and",
    short: "estent",
    wide: "land",
    narrow: "agor",
    deep: "núr",
    shallow: "tofn",
    heavy: "long",
    light: "pant",
    hot: "úr",
    cold: "ring",
    wet: "loen",
    dry: "parch",
    hard: "norn",
    soft: "moe",
    sharp: "laeg",
    dull: "thafn",
    smooth: "path",
    rough: "raw",
    clean: "puig",
    dirty: "gwaur",
    empty: "lost",
    full: "pant",
    near: "neled",
    far: "haer",
    east: "rhûn",
    west: "annûn",
    north: "forod",
    south: "harad",
    peace: "sîdh",
    war: "auth",
    battle: "dagor",
    victory: "tûr",
    defeat: "dangen",
    weapon: "magor",
    armor: "harnath",
    helmet: "thôl",
    shield: "thand",
    spear: "ech",
    axe: "hathol",
    hammer: "dam",
    knife: "sigil",
    food: "aes",
    bread: "bass",
    meat: "rhaw",
    fruit: "fêr",
    wine: "gwin",
    water: "nen",
    milk: "glûth",
    honey: "glî",
    salt: "singol",
    tree: "galadh",
    leaf: "lass",
    flower: "loth",
    grass: "sass",
    root: "thond",
    seed: "cordof",
    fruit: "fêr",
    oak: "doron",
    pine: "thôn",
    willow: "tathar",
    beech: "brethil",
    maple: "lalorn",
    ash: "feren",
    elm: "lalf",
    birch: "hwinn",
    horse: "roch",
    dog: "hû",
    cat: "meoi",
    wolf: "draug",
    bear: "brôg",
    deer: "aras",
    fox: "rusc",
    rabbit: "cabor",
    eagle: "thoron",
    hawk: "heledir",
    owl: "cugu",
    raven: "craban",
    swan: "alph",
    fish: "lim",
    snake: "lhûg",
    spider: "ungol",
    butterfly: "gwilwileth",
    bee: "niben",
    ant: "nedrui",
    spring: "ethuil",
    summer: "laer",
    autumn: "iavas",
    winter: "rhîw",
    morning: "aur",
    noon: "andúnë",
    evening: "aduial",
    midnight: "dúath",
    today: "sír",
    yesterday: "tolothen",
    tomorrow: "ab-ennen",
    week: "oronor",
    month: "astar",
    century: "andrann",
    time: "lû",
    hour: "lú",
    minute: "anrand",
    second: "redein",
    age: "andrann",
    dream: "ôl",
    hope: "estel",
    fear: "gorgor",
    joy: "glass",
    sorrow: "naergon",
    anger: "rûth",
    love: "meleth",
    hate: "delos",
    friend: "mellon",
    enemy: "goth",
    stranger: "edlon",
    guest: "althol",
    magic: "gûl",
    spell: "lûth",
    enchantment: "galadhremmin",
    power: "bellas",
    wisdom: "nauth",
    knowledge: "ist",
    secret: "thurin",
    mystery: "dolen",
    truth: "delw",
    lie: "gwaur",
    oath: "gwest",
    promise: "vanda",
    fate: "amarth",
    destiny: "manadh",
    soul: "fae",
    spirit: "făe",
    body: "rhaw",
    mind: "ind",
    thought: "nauth",
    memory: "rîn",
    dream: "ôl",
    nightmare: "fuinôl",
    vision: "aduial",
    voice: "lammen",
    speech: "peth",
    silence: "dîn",
    whisper: "hwest",
    shout: "caun",
    laugh: "gladh",
    cry: "nîr",
    tear: "nîn",
    smile: "lalaith",
    frown: "nifrad",
    kiss: "mîb",
    embrace: "gwaedh",
    touch: "dab",
    pain: "naeg",
    pleasure: "gell",
    health: "nestas",
    sickness: "lhîw",
    life: "cuin",
    death: "gurth",
    birth: "onneth",
    growth: "galas",
    decay: "thaw",
    beginning: "ested",
    end: "meth",
    journey: "lend",
    adventure: "bandath",
    quest: "tûr",
    home: "bar",
    land: "dôr",
    country: "ardh",
    kingdom: "aranarth",
    realm: "ardh",
    world: "ambar",
    universe: "ilúvatar",
    heaven: "menel",
    hell: "udûn",
    paradise: "valinor",
    wilderness: "rhovan",
    desert: "eryn",
    plain: "talath",
    hill: "amon",
    valley: "imlad",
    cave: "fela",
    beach: "falas",
    island: "tol",
    lake: "aelin",
    ocean: "eär",
    stream: "celeb",
    waterfall: "lanthir",
    snow: "loss",
    ice: "heleg",
    storm: "alagos",
    thunder: "rómru",
    lightning: "glawar",
    rainbow: "ninniach",
    mist: "hîth",
    fog: "mith",
    shadow: "gwath",
    flame: "lach",
    smoke: "osp",
    ash: "lith",
    i: "ni",
    me: "nin",
    you: "le",
    he: "e",
    she: "he",
    it: "ta",
    we: "me",
    they: "hain",

    // Prepositions
    in: "mi",
    on: "or",
    at: "na",
    to: "na",
    from: "o",
    with: "as",
    without: "ú",
    for: "an",
    of: "en",
    by: "od",
    under: "nu",
    over: "or",
    through: "tre",
    between: "im",

    // Conjunctions
    and: "a",
    but: "dan",
    or: "egor",
    if: "ae",
    because: "an",
    
    // Basic verbs
    am: "im",
    is: "na",
    are: "nar",
    was: "ne",
    were: "aner",
    be: "na",
    have: "gar",
    do: "car",
    go: "ped",
    come: "tol",
    see: "cen",
    hear: "lhaw",
    speak: "ped",
    eat: "mad",
    drink: "sog",
    sleep: "lor",
    wake: "echuia",
    live: "cuina",
    die: "fir",
    give: "anna",
    take: "mab",
    make: "car",
    
    // Question words
    what: "man",
    who: "man",
    whom: "man",
    whose: "man",
    which: "man",
    when: "îr",
    where: "mas",
    why: "man",
    how: "man",

    // Other common words
    yes: "mae",
    no: "baw",
    not: "ú",
    all: "pân",
    many: "laew",
    some: "min",
    few: "ark",
    other: "edraith",
    same: "im",
    different: "edraith",
    my: "nín",
    mine: "nín",
    your: "lín",
    yours: "lín",
    his: "dîn",
    her: "dîn",
    hers: "dîn",
    its: "tîn",
    our: "vín",
    ours: "vín",
    their: "tîn",
    theirs: "tîn",

    // Related words
    own: "ben",
    self: "im",
    myself: "imin",
    yourself: "lechim",
    himself: "e-chim",
    herself: "he-chim",
    itself: "te-chim",
    ourselves: "mchim",
    themselves: "im",

    // Demonstrative pronouns
    this: "sen",
    that: "tam",
    these: "sin",
    those: "tai",
    one: "min",
    two: "tâd",
    three: "nêl",
    four: "canad",
    five: "leben",
    six: "eneg",
    seven: "odog",
    eight: "toloth",
    nine: "neder",
    ten: "pae",
    hundred: "mimp",
    thousand: "meneg",

    // Comparative and superlative
    more: "am",
    most: "estar",
    less: "aksa",
    least: "alacha",

    // Interrogative particles
    how_many: "lim",
    how_much: "man",

    // Reflexive pronouns (often formed with 'im')
    oneself: "im",

    // Relative pronouns
    who: "i",
    which: "i",
    that: "i",

    // Modal verbs (often expressed through verb inflections)
    can: "pol-",
    must: "boe",
    should: "garo",

    // Adverbs
    quickly: "celeg",
    slowly: "lorn",
    well: "mae",
    badly: "faeg",

    // Negation
    no: "law",
    not: "ú-",
    never: "ú-",

    // Time-related
    now: "si",
    then: "san",
    always: "ui",
    never: "ú-",

    // Other common words
    only: "erui",
    also: "sen",
    very: "moe",
    too: "aen",
    again: "ad",

  O: "interj.",
  and: "conj.",
  after: "ab",
  prohibition: "ablad eblaid",
  bornAfter: "Abonnen Ebennin",
  neck: "achad",
  vengeance: "acharn echern",
  dreadFear: "achas echais",
  againstAgain: "ad",
  againBackSecond: "ad-",
  daddy: "ada edai",
  buildingHouse: "adab edaib",
  Man: "adan",
  FatherOfMen: "adanadar edenedair",
  mortalWoman: "adaneth edenith",
  woman: "edenith",
  father: "adar edair",
  behind: "adel",
  reunite: "adertha-",
  reunion: "aderthad aderthaid",
  slopingTilted: "adlann",
  slantSlope: "adlanna-",
  slantingOblique: "adlant edlaint",
  freeRelease: "adleitha-",
  slopingTilted2: "adlod adloen",
  eveningTwilight: "aduial aduiail",
  if: "ae",
  oceanSea: "aear aeair",
  greatSeaOcean: "Aearon Aearyn? Gaearyn?",
  peakHorn: "aeg aeg",
  sharpPointed: "aeg aeg",
  mountainPeak: "aegas aegais",
  rangeOfMountainPeaks: "aeglir aeglir",
  icicle: "aeglos aeglys",
  gorse: "aeglos aeglys",
  lakePool: "ael aelin",
  sea: "aer aeair",
  hymn: "aerlinn aerlinn",
  seaweed: "aeruil aeruil",
  cookedFood: "aes aes",
  birdSmall: "aew aew",
  gloryBrillianceGlitter: "agar",
  bloodstain: "agarwaen agarwaen",
  glitterBrillianceGlory: "aglar eglair",
  glorious: "aglareb",
  defilePassBetweenHighWalls: "aglonn eglynn",
  narrow: "agor egyr",
  and2: "ah",
  hail: "ai",
  plantBush: "aiglos aiglys",
  pointOfSpear: "aith aith",
  not: "al-",
  Ah: "alae!",
  impetuousRushing: "alag elaig",
  stormOfWind: "alagos elegys",
  immortalNameOfFlower: "alfirin alfirin",
  swan: "alph eilph",
  goingUp: "am-",
  world: "amar emair",
  doom: "amarth emerth",
  fated: "amarthan emerthain",
  shieldWall: "amath emaith",
  uphill: "ambenn",
  hopeBasedOnReason: "amdir amdir",
  crestOfHelmet: "amloth emlyth",
  snakeSerpent: "amlug emlyg",
  why: "amman?",
  us: "ammen",
  hillSteepSidedMount: "amon emyn",
  OrientSunriseEast: "amrún emrŷn",
  for: "an",
  for2: "an-",
  longForALongTime: "anann",
  jawRowOfTeeth: "anc ainc",
  door: "and",
  long: "and",
  longMark: "andaith andaith",
  ageCycle: "andrann endrain",
  climbHighPass: "andrath endraith",
  LongbeardTribeOfDwarves: "Anfang Enfeng",
  LongbeardsPeople: "Anfangrim pl. coll.",
  iron: "ang",
  runicAlphabet: "angerthas",
  approach: "anglenna-",
  magicDeepLore: "angol engyl",
  horror: "angos engyl",
  ofIron: "angren engryn",
  chainIronBond: "angwedh engwidh",
  forMe: "anim",
  desire: "aníra-",
  jaw: "ank enk",
  give: "anna-",
  elephant: "annabon ennebyn",
  giving: "anneth ennith",
  gateDoor: "annon ennyn",
  west: "annû-",
  western: "annui annui",
  SunsetWest: "annûn ennŷn",
  Westron: "Annúnaid",
  Sun: "Anor Anoer",
  gift: "ant aint",
  male: "anu eny",
  awe: "anwar enwair",
  follow: "aphada-",
  follower: "aphadon ephedyn",
  followers: "aphadrim",
  and: "ar",
  outsideWithout: "ar-",
  nobleHighRoyal: "ar-",
  King: "âr êr?",
  nobleHighRoyal2: "ara-",
  day: "arad eraid",
  wolf: "araf eraif",
  king: "aran erain",
  kingdomRealm: "aranarth",
  deer: "aras erais",
  throne: "archam erchaim",
  realmRegion: "ardh erdh",
  provinceGreatRegion: "ardhon erdhyn",
  nobleRoyal: "arn",
  kingdom: "arnad ernaid",
  numberlessUnnumbered: "arnediad arnediaid?",
  royal2: "arnen ernin",
  noble: "arod aroed",
  countlessInnumerable: "aronoded erenedid",
  nobleMan: "arphen erphin",
  exaltedLoftyNoble: "arth erth",
  nobleLady: "arwen erwin",
  violentRushingImpetuous: "ascar escair",
  violentRushingImpetuous2: "asgar",
  dustSandAsh: "ast aist",
  onBothSides: "ath-",
  beyond: "athan",
  acrossBeyond: "athar",
  thumbLittleFather: "atheg ethig",
  kingsfoil: "athelas ethelais",
  cross: "athra-",
  debate: "athrabeth ethrebith",
  crossingFord: "athrad ethraid",
  traverseCross: "athrada-",
  wrongMistake: "athranna-",
  dayMorning: "aur oer",
  warBattle: "auth oeth",
  apparition: "auth oeth",
  dontDo: "av-",
  willNot: "ava-",
  refusalReluctance: "avad evaid",
  ElfOfBeleriand: "avar evair",
  dont: "avo!",
  staying: "avorn evyrn",
  abandonment: "awarth",
  abandon: "awartha-",
  articleForExchange: "bach baich",
  pedlar: "bachor bechyr",
  go: "bad-",
  pathwayBeatenTrack: "bâd baid",
  judge: "badhor bedhyr",
  judge: "badhron bedhryn",
  beautifulFair: "bain bain",
  divinityDivinePower: "bâl bsil",
  divine: "bâl bsil",
  ValaDivinity: "balan belain",
  cruel: "balch boeg",
  fireDemon: "balrog belryg?",
  custodyPrison: "band baind",
  beauty: "baneth",
  trade: "banga-",
  dwellingHouseHomeFamilyLandEarth: "bâr bair",
  eagerFiery: "bara berai",
  doomed: "barad beraid",
  fortressFortTower: "barad beraid",
  steep: "baradh beraidh",
  brownSwartDark: "baran berain",
  doom: "bartha-",
  loafRoundBread: "basgorn besgyrn",
  bread: "bass bais",
  breadGiverFeminine: "bassoneth bassonith",
  trample: "batha-",
  judgmentSentence: "baudh boedh",
  oppressiveCruelTyrannous: "baug boeg",
  constrainOppress: "baugla-",
  constrainerOppressorTyrant: "bauglir bauglir",
  constrainerOppressorTyrant2: "baugron baugryn",
  torment: "baul boel",
  need: "baur boer",
  noDont: "baw",
  accordingTo: "be",
  strength: "bel bil",
  greatMighty: "beleg belig",
  strongInBody: "bell bill",
  strength2: "bellas bellais",
  accordingTo2: "ben",
  manHusband: "benn binn",
  angle: "bennas bennais",
  bold: "beren",
  spouseQueen: "bereth berith",
  protect: "beria-",
  leap: "cab-",
  leap2: "cabed cebid",
  frog: "cabor cebyr",
  formedShaped: "cadu cedy",
  shapely: "cadwar cedwair",
  dare: "bertha-",
  womanWife: "bess biss",
  breadGiverFeminine2: "bessain bessain",
  beatWings: "blab-",
  on: "bo",
  banProhibit: "boda-",
  must: "boe",
  trustyManSteadfastMan: "bôr býr",
  trust: "bora-",
  hot: "born byrn",
  puddleSmallPool: "both byth",
  sudden: "bragol bragoel",
  fierceWild: "braig braig",
  fineHighLoftyNoble: "brand braind",
  lord: "brannon brennyn",
  whiteHeat: "brass brais",
  whiteHot: "brassen",
  livelySuddenQuick: "brêg brîg",
  suddenly: "breged bregid",
  suddennessViolence: "breged bregid",
  wildfire: "bregedúr bregedŷr",
  suddenViolent: "bregol bregoel",
  fierceness: "bregolas bregolais",
  breakOutSuddenly: "breitha-",
  endure: "brenia-",
  lady: "brennil brennil",
  birchTree: "brethil brethil",
  gravel: "brith brith",
  pebbly: "brithon brithoen",
  bear: "brôg brýg",
  lastSurvive: "brona-",
  survival: "bronad brenaid",
  enduring: "bronadui bronadui",
  endurance: "bronwe",
  loudNoisy: "brui brui",
  oldWorn: "brûn bruin",
  serveHoldAllegiance: "buia-",
  snoutNose: "bund bynd",
  vassalFollower: "býr",
  earth: "cae cae",
  lieOnTheGround: "caeda-",
  lyingInBedSickness: "cael cael",
  bedriddenSick: "caeleb caelib",
  ten: "caer",
  lair: "caew",
  hedge: "cai",
  fenceWithSpikes: "cail",
  ship: "cair",
  light: "calad",
  day: "calan",
  lamp: "calar",
  lampwright: "calardan",
  Elda: "calben",
  green: "calen",
  hero: "callon",
  vessel: "calph",
  hand: "cam",
  handsPalm: "camlann",
  callShoutCry: "can-",
  four: "canad",
  townCity: "canas",
  farthingFourthPart: "canath",
  bold: "cand",
  shaping: "cannas",
  fourth: "cannui",
  outlineShape: "cant",
  fourth: "canthui",
  buildMakeDo: "car-",
  buildingHouse: "car",
  hat: "carab",
  jawRowOfTeeth: "carach",
  hedgeOfSpikes: "caraes",
  spikeToothOfRock: "carag",
  red: "caran",
  townCity: "caras",
  fang: "carch",
  deedHouseBuilding: "cardh",
  doingMaking: "cared",
  headlandCape: "cast",
  tressureHairnet: "cathrae",
  afflictionHeavyBurden: "caul",
  clamourOutcry: "caun",
  top: "caw",
  stakeSpike: "ceber",
  soil: "cêf",
  earthen: "cefn",
  earthenware: "cefnas",
  streamLittleRiver: "cel",
  brilliant: "celair",
  silver: "celeb",
  likeSilver: "celebren",
  agileSwift: "celeg",
  streamFlowing: "celeth",
  ofSilver: "celevon",
  flowing: "cell",
  river: "celon",
  springWater: "celos",
  sourceSpring: "celu",
  see: "cen-",
  sightSeeing: "cened",
  mirror: "cenedril",
  potter: "cennan",
  sickle: "cerch",
  doerMaker: "ceredir",
  moundEnclosure: "cerin",
  rune: "certh",
  alphabetRunic: "certhas",
  July: "cerveth",
  earth: "ceven",
  choose: "cil-",
  renewal: "cîl",
  cleftPassBetweenHills: "cîl",
  haven: "círbann",
  shipbuilder: "círdan",
  sailorShipman: "cirion",
  cleftCuttingPass: "cirith",
  freshNew: "cîw",
  splendourGlory: "claur",
  bay: "côf",
  empty: "cofn",
  bearCarry: "col-",
  goldMetal: "côl",
  cloak: "coll",
  hollow: "coll",
  redScarlet: "coll",
  mayor: "condir",
  commanding: "conui",
  crow: "corch",
  smallRedApple: "cordof",
  ring: "corf",
  circle: "corn",
  circularRoundGlobed: "corn",
  ballGlobeMound: "coron",
  wilyCunning: "coru",
  quarrel: "cost",
  enmityEnemy: "coth",
  crow: "craban",
  cake: "caew",
  hedge: "cai",
  fenceWithSpikes: "cail",
  ship: "cair",
  light: "calad",
  day: "calan",
  lamp: "calar",
  lampwright: "calardan",
  Elda: "calben",
  green: "calen",
  hero: "callon",
  vessel: "calph",
  hand: "cam",
  handsPalm: "camlann",
  callShoutCry: "can-",
  four: "canad",
  townCity: "canas",
  farthingFourthPart: "canath",
  bold: "cand",
  shaping: "cannas",
  fourth: "cannui",
  outlineShape: "cant",
  fourth: "canthui",
  buildMakeDo: "car-",
  buildingHouse: "car",
  hat: "carab",
  jawRowOfTeeth: "carach",
  hedgeOfSpikes: "caraes",
  spikeToothOfRock: "carag",
  red: "caran",
  townCity: "caras",
  fang: "carch",
  deedHouseBuilding: "cardh",
  doingMaking: "cared",
  headlandCape: "cast",
  tressureHairnet: "cathrae",
  afflictionHeavyBurden: "caul",
  clamourOutcry: "caun",
  top: "caw",
  stakeSpike: "ceber",
  soil: "cêf",
  earthen: "cefn",
  earthenware: "cefnas",
  streamLittleRiver: "cel",
  brilliant: "celair",
  silver: "celeb",
  likeSilver: "celebren",
  agileSwift: "celeg",
  streamFlowing: "celeth",
  ofSilver: "celevon",
  flowing: "cell",
  river: "celon",
  springWater: "celos",
  sourceSpring: "celu",
  see: "cen-",
  sightSeeing: "cened",
  mirror: "cenedril",
  potter: "cennan",
  sickle: "cerch",
  doerMaker: "ceredir",
  moundEnclosure: "cerin",
  rune: "certh",
  alphabetRunic: "certhas",
  July: "cerveth",
  earth: "ceven",
  choose: "cil-",
  renewal: "cîl",
  cleftPassBetweenHills: "cîl",
  haven: "círbann",
  shipbuilder: "círdan",
  sailorShipman: "cirion",
  cleftCuttingPass: "cirith",
  freshNew: "cîw",
  splendourGlory: "claur",
  bay: "côf",
  empty: "cofn",
  bearCarry: "col-",
  goldMetal: "côl",
  cloak: "coll",
  hollow: "coll",
  redScarlet: "coll",
  mayor: "condir",
  commanding: "conui",
  crow: "corch",
  smallRedApple: "cordof",
  ring: "corf",
  circle: "corn",
  circularRoundGlobed: "corn",
  ballGlobeMound: "coron",
  wilyCunning: "coru",
  quarrel: "cost",
  enmityEnemy: "coth",
  crow: "craban",
  cake: "cram",
  ruddyOfFace: "crann",
  cleftGulfRavine: "criss",
  cleaverSword: "crist",
  reap: "critha-",
  left: "crom",
  leftHand: "crum",
  guiltyWilySinister: "crumguru",
  leftHanded: "crumui",
  archBowCrescent: "cû",
  dove: "cugu",
  live: "cuia-",
  down: "dad",
  slantDownInclined: "dadbenn",
  greatLarge: "dae",
  exceedinglyVery: "dae",
  shadowShade: "dae",
  canopy: "daedelu",
  corpse: "daen",
  bridegroom: "daer",
  large: "daer",
  permission: "dâf",
  slay: "dag-",
  bane: "dagnir",
  battle: "dagor",
  doBattleMakeWar: "dagra-",
  hammer: "dam",
  answerResponse: "dambeth",
  hammer: "damma-",
  butHowever: "dan",
  against: "dan",
  soundNoise: "dang",
  slain: "dangen",
  answerReply: "dangweth",
  fall: "danna-",
  autumn: "dannas",
  fallen: "dannen",
  ebb: "dannen",
  fallFalling: "dant",
  Nandor: "Danwaith",
  life: "cuil",
  alive: "cuin",
  beAlive: "cuina-",
  load: "cûl",
  heapMound: "cûm",
  bentBowShaped: "cûn",
  prince: "cund",
  crescentMoon: "cúron",
  cunningDevice: "curu",
  wizard: "curunír",
  bearer: "cyll",
  renewed: "cŷr",
  newMoon: "cýron",
  ransom: "danwedh",
  haltStop: "dar-",
  endureStayWaitRemainLast: "dartha-",
  abyssChasmVoidGulf: "dath",
  soldierOrkish: "daug",
  leaguePauseStop: "daur",
  gloomNighttime: "daw",
  victorWinner: "degil",
  disgust: "dêl",
  horribleLoathsome: "deleb",
  conceal: "delia-",
  abhorrenceFearHorrorDreadDetestationLoathing: "delos",
  deadlyHatefulFell: "delu",
  gloomySad: "dem",
  Nandor: "Denwaith",
  youngMaiden: "dess",
  under: "di-",
  brideLady: "dî",
  beneathInUnder: "dî",
  forgive: "dihena-",
  stopperStopping: "dîl",
  stopUp: "dilia-",
  stair: "dim",
  sadnessGloom: "dim",
  gapOpeningMountainPass: "dîn",
  silent: "dínen",
  bride: "dineth",
  maleAdultMale: "dîr",
  manSpearhead: "dírnaith",
  bride: "dîs",
  lowGloomy: "dofn",
  goUp: "dol-",
  headHill: "dôl",
  hiddenSecret: "dolen",
  darkDuskyMistyObscure: "doll",
  bossRoundKnob: "dolt",
  conceal: "doltha-",
  fist: "dond",
  blackSwartSwartyShadyShadowy: "donn",
  landDwellingPlaceRegion: "dôr",
  stiffTough: "dorn",
  TrawnFolkDwarfs: "Dornhoth",
  oakTree: "doron",
  dwell: "dortha-",
  burn: "dosta-",
  hewnLog: "drafn",
  blowHeavyStroke: "dram",
  clenchedFistBlowWithFist: "drambor",
  wolf: "draug",
  hew: "drava-",
  forthOutAway: "e-",
  spine: "ech",
  fashionMakeShape: "echad-",
  encampment: "echad",
  follower: "echil",
  outerRingCircle: "echor",
  awakening: "echui",
  wakeUp: "echuia-",
  seasonOfStirringSpring: "echuir",
  pointSpearPoint: "ecthel",
  forthOutAway: "ed-",
  double: "edaid",
  begunAgainNew: "eden",
  Elf: "edhel",
  berylElfStone: "edhelharn",
  elvish: "edhellen",
  anniversaryDay: "edinor",
  goToExile: "edledh-",
  flee: "dreg-",
  flee: "drega-",
  flee: "drego!",
  hammer: "dring",
  beat: "dringa-",
  WildMan: "Drúadan",
  WildMen: "Drúath",
  darknessNightNightfallDusk: "dû",
  riverLargeRiverWithCurrent: "duin",
  tide: "duinen",
  riverbank: "duirro",
  nightingale: "dúlinn",
  West: "dûn",
  NúmenóreanManOfTheWest: "dúnadan",
  ElfOfBeleriandWestElfIncludingNoldorAndSindar: "dúnedhel",
  dark: "dûr",
  west: "dúven",
  successor: "dŷr",
  goToExile: "edledhia-",
  Exiled: "Edledhron",
  exiled: "edlenn",
  blossom: "edlothia-",
  flower: "edlothia-",
  flowering: "edlothiad",
  beget: "edonna-",
  open: "edra-",
  border: "edrain",
  savingSalvation: "edraith",
  especially: "edregol",
  second: "edwen",
  thorn: "êg",
  ForsakenSindarFalathrim: "Egladhrim",
  forsaken: "eglan",
  manSpearhead: "dírnaith",
  bride: "dîs",
  lowGloomy: "dofn",
  goUp: "dol-",
  headHill: "dôl",
  hiddenSecret: "dolen",
  darkDuskyMistyObscure: "doll",
  bossRoundKnob: "dolt",
  conceal: "doltha-",
  fist: "dond",
  blackSwartSwartyShadyShadowy: "donn",
  landDwellingPlaceRegion: "dôr",
  stiffTough: "dorn",
  TrawnFolkDwarfs: "Dornhoth",
  oakTree: "doron",
  dwell: "dortha-",
  burn: "dosta-",
  hewnLog: "drafn",
  blowHeavyStroke: "dram",
  clenchedFistBlowWithFist: "drambor",
  wolf: "draug",
  hew: "drava-",
  forthOutAway: "e-",
  spine: "ech",
  fashionMakeShape: "echad-",
  encampment: "echad",
  follower: "echil",
  outerRingCircle: "echor",
  awakening: "echui",
  wakeUp: "echuia-",
  seasonOfStirringSpring: "echuir",
  pointSpearPoint: "ecthel",
  forthOutAway: "ed-",
  double: "edaid",
  begunAgainNew: "eden",
  Elf: "edhel",
  berylElfStone: "edhelharn",
  elvish: "edhellen",
  anniversaryDay: "edinor",
  goToExile: "edledh-",
  flee: "dreg-",
  flee: "drega-",
  flee: "drego!",
  hammer: "dring",
  beat: "dringa-",
  wildMan: "drû",
  WildMan: "Drúadan",
  WildMen: "Drúath",
  darknessNightNightfallDusk: "dû",
  riverLargeRiverWithCurrent: "duin",
  tide: "duinen",
  riverbank: "duirro",
  nightingale: "dúlinn",
  West: "dûn",
  NúmenóreanManOfTheWest: "dúnadan",
  ElfOfBeleriandWestElfIncludingNoldorAndSindar: "dúnedhel",
  dark: "dûr",
  west: "dúven",
  successor: "dŷr",
  goToExile: "edledhia-",
  Exiled: "Edledhron",
  exiled: "edlenn",
  blossom: "edlothia-",
  flower: "edlothia-",
  flowering: "edlothiad",
  beget: "edonna-",
  open: "edra-",
  border: "edrain",
  savingSalvation: "edraith",
  especially: "edregol",
  second: "edwen",
  thorn: "êg",
  ForsakenSindarFalathrim: "Egladhrim",
  forsaken: "eglan",
  glorifyPraise: "egleria-",
  sharpPoint: "egnas",
  beOff: "ego!",
  SindaOneOfTheForsaken: "egol",
  or: "egor",
  rain: "eilia-",
  rainbow: "eilian",
  rainBow: "eiliant",
  elder: "einior",
  daisy: "eirien",
  insultPrickWithSharpPoint: "eitha-",
  insult: "eithad",
  issueOfWaterSpringWell: "eithel",
  star: "êl",
  StarSunFlower: "elanor",
  pimpernelFlower: "elanor",
  ElvesPeople: "Eledhrim",
  Elf: "elen",
  elfWoman: "elleth",
  elfMan: "ellon",
  singleFlower: "elloth",
  admirationExclamationOf: "elo!",
  ElvesPeople: "Elrim",
  paleBlue: "elu",
  Sindar: "Eluwaith",
  ElfFriend: "elvellon",
  mother: "emel",
  motherFingerIndex: "emig",
  yellowBirdYellowhammer: "emlin",
  sixth: "enchui",
  centerCoreMiddle: "enedh",
  midyear: "enedhin",
  six: "eneg",
  six: "engui",
  there: "ennas",
  soulSpirit: "fae",
  badPoorMean: "faeg",
  longYearValianYear: "ennin",
  MiddleEarth: "Ennor",
  landsOfMiddleEarth: "ennorath",
  encirclingFenceOuterFence: "ephel",
  loneAloneOne: "er-",
  singleFirstAlone: "er",
  prickle: "erch",
  prickPointStick: "ercha-",
  oneHanded: "erchamion",
  oneHanded: "erchammon",
  oneHanded: "erchammui",
  orkish: "erchion",
  isolatedLonely: "ereb",
  germSeed: "eredh",
  holly: "ereg",
  holly: "eregdos",
  riseArise: "eria-",
  aloneFirstSingle: "eriol",
  prince: "ernil",
  unite: "ertha-",
  union: "erthad",
  GodTheOne: "Eru",
  wasteTheOneNameOfGod: "eru",
  aloneFirstSingle: "erui",
  woodForest: "eryn",
  forestFire: "erynaur",
  coverVeilScreen: "escal",
  veilScreen: "esgal",
  bankShore: "esgar",
  waterFall: "espalass",
  callName: "esta-",
  faithHopeTrust: "estel",
  short: "estent",
  encampment: "estolad",
  spy: "ethir",
  estuaryMouthOrOutflowOfARiver: "ethir",
  spring: "ethuil",
  gleamingBrilliance: "fael",
  fairMindedJustGenerous: "fael",
  sparklingDragon: "faelug",
  radiant: "faen",
  spirit: "faer",
  white: "fain",
  mortalMan: "fair",
  beachShoreCoastStrandLineOfSurfFoamingShore: "falas",
  ofTheShore: "falathren",
  peopleOfTheFalas: "Falathrim",
  cleftRavine: "falch",
  breakerFoam: "falf",
  foam: "faltha-",
  cloudVeilManifestedBodyOfAVala: "fân",
  beard: "fang",
  cloudy: "fanui",
  enough: "far",
  hunt: "fara-",
  huntHunting: "farad",
  huntersPeople: "faradrim",
  huntHunting: "faras",
  enough: "farn",
  hunter: "faron",
  hunters: "faroth",
  shaggyHair: "fast",
  chokingGaspingThirsty: "faug",
  cloud: "faun",
  shoreBeach: "faur",
  suffice: "feiria-",
  cave: "fela",
  doorThreshold: "fend",
  gatewayDoor: "fennas",
  beechMast: "fêr",
  hunter: "feredir",
  dead: "fern",
  catch: "gad-",
  dungeonPrison: "gador",
  dreadFear: "gae",
  oceanSea: "gaear",
  GreatOcean: "gaearon",
  glitteringPale: "gael",
  dreadfulFearfulHoly: "gaer",
  sea: "gaer",
  reddishCopperColouredRuddy: "gaer",
  deadDeadPerson: "fern",
  northern: "fervain",
  birdSmall: "fileg",
  smallBird: "filigod",
  slimSlender: "fim",
  hairLockOfHairTress: "fîn",
  lockOfHairTress: "find",
  lockOfHair: "fing",
  braidedTressOfHair: "finnel",
  dieFade: "fir-",
  mortal: "fíreb",
  mortal: "fíreb",
  human: "firen",
  MortalHumains: "firiath",
  mortalMaiden: "fíriel",
  mortalWoman: "firieth",
  mortal: "firin",
  mortalMan: "firion",
  seasonOfFadingAutumn: "firith",
  skilledHandy: "flâd",
  northRight: "fôr",
  rightHanded: "forgam",
  north: "forod",
  NorthmenNorthfolk: "forodrim",
  NorthmenNorthfolkNorthRegions: "forodwaith",
  northDirection: "forven",
  rightHandRightSide: "forvo",
  abhor: "fuia-",
  darknessGloomNightDeadOfNight: "fuin",
  rightHandNorth: "fuir",
  seaWeed: "gaeruil",
  fish: "gail",
  lightBright: "gail",
  light: "gal-",
  grow: "gala-",
  lightBrightSunlightBrillianceRadianceGlitteringReflection: "galad",
  tree: "galadh",
  tangled: "galadhremmen",
    "people of the Trees, Elves of Lórien": "galadhrim",
    growth: "galas",
    "pipe-weed": "galenas",
    blessing: "galu",
    "black metal": "galvorn",
    "claw, hook, crook": "gamp",
    "harp, play a harp": "ganna",
    "harp, play a harp": "gannada",
    harp: "gannel",
    can: "gar",
    wolf: "garaf",
    "defined or bounded place": "gardh",
    own: "garn",
    defend: "gartha",
    hole: "gas",
    apostrophe: "gasdil",
    stopgap: "gasdil",
    cavern: "gath",
    "cave": "gathrod",
    "device": "gaud",
    "wolf-howl": "gaul",
    werewolf: "gaur",
    "werewolf-host": "gaurhoth",
    "outlaws": "gaurwaith",
    void: "gaw",
    howl: "gawa",
    howling: "gawad",
    learn: "gelia",
    merry: "gelir",
    "joy": "gell",
    delight: "gella",
    jubilation: "gellam",
    triumphant: "gellui",
    sickly: "gem",
    reckon: "genedia",
    "count": "genediad",
    worn: "gern",
    "star": "gîl",
    "silver": "gildin",
    starlight: "gilgalad",
    shudder: "gir",
    "horror": "girith",
    December: "Girithon",
    "wood": "glad",
    laugh: "gladha",
    grass: "glae",
    "narrative poem": "glaer",
    salve: "glaew",
    "din, uproar, tumult, shouting, confused noise, a body of Orcs": "glam",
    "yelling-horde": "glamhoth",
    orc: "glamog",
    echo: "glamor",
    echoing: "glamren",
    white: "glân",
    clear: "glân",
    border: "glân",
    boundary: "gland",
    "boundary marker": "glandagol",
    clear: "glanna",
    joy: "glass",
    "golden light": "glaur",
    babble: "glavra",
    babbling: "glavrol",
    radiance: "glaw",
    brilliance: "glaw",
    sunlight: "glawar",
    gold: "glawar",
    bound: "glenia",
    limit: "glenia",
    enclose: "glenia",
    honey: "glî",
    "glint of light": "glîn",
    glance: "glind",
    hanging: "gling",
    dangle: "glinga",
    hang: "glinga",
    glance: "glinna",
    Teler: "glinnel",
    recite: "glir",
    sing: "glir",
    "song": "glîr",
    "dazzling white, white as snow": "gloss",
    soap: "glûdh",
    together: "go",
    "enclosed dwelling": "gobel",
    historical: "gobenathren",
    history: "gobennas",
    "mass of ice": "gochel",
    Noldo: "gódhel",
    "Noldor (people)": "Gódhellim",
    through: "godref",
    together: "godref",
    "great fear, dread": "goe",
    "dire, terrible, fell": "goeol",
    forgive: "gohena",
    "collection of leaves, foliage": "golas",
    branch: "golf",
    wise: "goll",
    "wise man": "gollor",
    Noldo: "golodh",
    "Noldor (people)": "Golodhrim",
    fleurs: "goloth",
    "Noldo Jewel (Silmaril)": "Golovir",
    teach: "goltha",
    wisdom: "golu",
    "learned in deep arts, wise": "golwen",
    entangle: "gonathra",
    entanglement: "gonathras",
    "rock": "gond",
    "ridge": "gondrafn",
    "spike": "gondram",
    causeway: "gondrath",
    "made of stone, stony": "gondren",
    "Master of Stone, Dwarf": "Gonhir",
    count: "gonod",
    "of stone": "gonui",
    conceal: "gor",
    "horror, fear, dread": "gôr",
    vigour: "gôr",
    impetus: "gorf",
    "deadly fear": "gorgor",
    "hasty, vigorous, impetuous": "gorn",
    valour: "gorn",
    horror: "gorog",
    horror: "goroth",
    dead: "gorth",
    "dead person": "gorth",
    barrow: "gorthad",
    horrible: "gortheb",
    "Deads (group of)": "gorthrim",
    terror: "gost",
    fear: "gosta",
    enemy: "goth",
    meet: "govad",
    community: "govannas",
    met: "govannen",
    "compact, contract, treaty": "gowest",
    "creature powerful, hostile and terrible": "graug",
    bear: "graw",
    cave: "grôd",
    "fear": "groga",
    club: "grond",
    "cave, delving, large excavation": "groth",
    ruddy: "gruin",
    fury: "gruith",
    terrify: "gruitha",
    foe: "gûd",
    "evil knowledge, magic, sorcery, necromancy": "gûl",
    "dark sorcery": "guldur",
    "inner mind, heart": "gûr",
    death: "gûr",
    death: "gurth",
    death: "guruth",
    "death-horror, dread of death": "guruthos",
    together: "gwa",
    away: "gwachae",
    "palantir, seeing stone": "gwachaedir",
    "sworn brother": "gwador",
    enfold: "gwaeda",
    bond: "gwaedh",
    gull: "gwael",
    stained: "gwaen",
    windy: "gwaeren",
    March: "gwaeron",
    storm: "gwaew",
    new: "gwain",
    "able-bodied men (troop of), manhood, manpower, host, regiment, people, region, wilderness": "gwaith",
    blossom: "gwaloth",
    "death (act of dying)": "gwanath",
    dead: "gwann",
    depart: "gwanna",
    number: "gwanod",
    "death by fading": "gwanu",
    "pair of twins": "gwanûn",
    "twin": "gwanunig",
    "pair of twin": "gwanûr",
    "relative, brother": "gwanûr",
    "kinsman, kinswoman": "gwanur",
    "Elf of Aman": "gwanwel",
    "departed": "gwanwen",
    "Elve of Aman": "gwanwen",
    "betrayer": "gwarth",
    "stain": "gwass",
    "hummock": "gwastar",
    "shade, shadow, dim light": "gwâth",
    "soil, stain": "gwatha",
    "sister": "gwathel",
    "dim, overshadow, veil, obscure": "gwathra",
    "dim, shadowy": "gwathren",
    "shadowy": "gwathui",
    "Shadowy People (of Dunland)": "Gwathuirim",
    "goose": "gwaun",
    "clothe": "hab",
    "clothes": "hab",
    "shore": "habad",
    "hurl": "had",
    "Dwarf": "hadhod",
    "Khuzdûl": "Hadhodren",
    "Dwarfs (people)": "Hadhodrim",
    "sling": "hadlath",
    "thrower": "hador",
    "thrower of darts, hurler of darts": "hadron",
    "distant, far, on the other side, further": "hae",
    "far, remote, distant": "haer",
    "distance": "haered",
    "far, distant": "haeron",
    "custom, habit": "haew",
    "sit": "haf",
    "them (inanimates)": "hain",
    "left": "hair",
    "left hand": "hair",
    "lift": "hal",
    "clear, sparkling, light": "hâl",
    "dirty, soiled": "gwaur",
    "bind": "gwedh",
    "bond, bond of loyalty": "gwedh",
    "air (as substance)": "gwelu",
    "air (as a region)": "gwelwen",
    "maiden": "gwend",
    "bond of friendship": "gwend",
    "virginity": "gweneth",
    "pair of twin": "gwenyn",
    "betray, cheat": "gweria",
    "oath": "gwest",
    "swear": "gwesta",
    "host, army": "gweth",
    "net, web": "gwî",
    "air (as a region)": "gwilith",
    "butterfly": "gwilwileth",
    "vine, wine": "gwîn",
    "foam": "gwing",
     hello:"Ae",
    "baby, little finger": "gwinig",
    "April": "gwirith",
    "butterfly": "gwiwileth",
    "fish": "hâl",
    "seashell": "half",
    "hidden, veiled, shadowed": "hall",
    "exalted, high": "hall",
    "screen": "haltha",
    "chair": "ham",
    "clothe": "hamma",
    "clothing": "hammad",
    "garment": "hamp",
    "brother": "hanar",
    "intelligent": "hand",
    "understanding": "hannas",
    "left (direction)": "hâr",
    "south": "harad",
    "south, southern": "haradren",
    "People of the South": "haradrim",
    "left-handed": "hargam",
    "helmet": "harn",
    "wounded": "harn",
    "southern": "harn",
    "wound": "harna",
    "hope": "hartha",
    "hope": "harthad",
    "wound": "haru",
    "left hand, left side": "harvo",
    "axe-stroke": "hast",
    "hack through": "hasta",
    "blade (of a broadsword or axe)": "hathel",
    "axe, axe blade": "hathol",
    "burial mound, barrow, grave, tomb": "haudh",
    "bed": "haust",
    "sit": "hav",
    "she": "he, hen, hene",
    "keep, retain": "heb",
    "bitterly cold": "helch",
    "glass": "heledh",
    "kingfisher (bird)": "heledir",
    "ice": "heleg",
    "frozen": "helegnen",
    "fur": "heleth",
    "coat": "helf",
    "throat": "hell",
    "naked": "hell",
    "strip": "heltha",
    "child": "hên",
    "eye": "hend",
    "eyed": "heneb",
    "understand": "henia",
    "glance": "henn",
    "window": "henneth",
    "master": "herdir",
    "have an impulse, begin suddenly and vigorously": "heria",
    "master": "heron",
    "household, troop under a lord": "herth",
    "husband": "hervenn",
    "wife": "hervess",
    "lady": "heryn",
    "captain": "hest",
    "that": "i",
    "the": "i",
    "ago": "ia",
    "obscure, foggy, vague": "hethu",
    "heir": "hîl",
    "cool": "him",
    "abiding, steadfast": "him",
    "continually": "him",
    "find": "hir",
    "lord, master": "hîr",
    "Lady": "hiril",
    "fog, mist": "hîth",
    "mist, fog": "hithu",
    "November": "Hithui",
    "foggy": "hithui",
    "sticky": "hîw",
    "harborage": "hobas",
    "rest": "hoda",
    "close": "hol",
    "closed": "hollen",
    "he": "hon",
    "little brother, also the name of the middle finger": "honeg",
    "driven under compulsion": "horn",
    "speed, urge on": "hortha",
    "gross (144)": "host",
    "cold pool, lake": "hoth",
    "crowd, host, horde": "hoth",
    "dog": "hû",
    "dog (hunt)": "huan",
    "harbour, haven, small landlocked bay": "hûb",
    "assembly": "hûd",
    "cry of encouragement in battle": "hûl",
    "heart": "hûn",
    "action, readiness for, vigour, fiery spirit": "hûr",
    "fungus, sponge": "hwand",
    "breeze, puff": "hwest",
    "faintness, giddiness": "hwîn",
    "eddy": "hwind",
    "twirl, whirl, eddy": "hwinia",
    "fantastic": "hwiniol",
    "abyss, chasm, void, gulf": "iâ",
    "neck": "iaeth",
    "mocking, scorn": "iaew",
    "shout, cry": "ial",
    "call out": "ialla",
    "bridge": "iant",
    "bridge": "ianu",
    "blood": "iâr",
    "eldest": "iarwain",
    "where": "ias",
    "fence": "iâth",
    "People of Doriath": "Iathrim",
    "Doriath people": "iathrim",
    "Sinda (of Doriath)": "iathron",
    "fane, holy place, sanctuary": "iaun",
    "ancient, old, former": "iaur",
    "autumn": "iavas",
    "corn (not maize)": "iaw",
    "repose, rest": "îdh",
    "thoughtfulness": "idhor",
    "pondering, wise, thoughtful": "idhren",
    "year": "idhrinn",
    "daughter, girl, maid": "iell",
    "wish": "iest",
    "daily": "ilaurui",
    "I": "im",
    "between, within": "im",
    "between, within": "im-",
    "deep vale, dell": "im",
    "glen, deep valley": "imlad",
    "flowering valley": "imloth",
    "path": "imrad",
    "valley": "imrath",
    "hop": "laba",
    "hare": "laboth",
    "flame": "lacha",
    "flame-eyed, Elf who has lived in the Blessed Realm": "lachenn",
    "valley": "lâd",
    "cleared, plain, flat, wide, open": "laden",
    "great number": "lae",
    "fresh": "laeb",
    "fresh green": "laeg",
    "year": "în",
    "guess, idea, notion": "inc",
    "inner thought, mind, meaning, heart": "ind",
    "suppose": "inga",
    "year sick, old": "ingem",
    "annals": "ínias",
    "will": "innas",
    "female": "inu",
    "ago": "io",
    "flood-water, wash": "iôl",
    "son": "ion",
    "descendant, son": "iôn",
    "descendant, son (coll. pl)": "ionnath",
    "aged, long-lived": "iphant",
    "when": "ir",
    "sexual desire": "îr",
    "desire": "íra",
    "knowledge, lore": "ist",
    "have knowledge": "ista",
    "learned": "istui",
    "moon": "Ithil",
    "magic metal that only mirrors starlight and moonlight": "ithildin",
    "wizard": "ithron",
    "use": "iuith",
    "use": "iuitha",
    "embers": "iûl",
    "blood": "iûr",
    "September": "ivanneth",
    "crystal": "ivor",
    "of crystal": "ivorcheneb",
    "of crystal": "ivren",
    "acute, keen, sharp": "laeg",
    "Green Elf": "laegel",
    "Green Elves (people)": "laegrim",
    "song": "laer",
    "season of summer": "laer",
    "babe, also used in children's play as the name of the little finger": "laes",
    "frequent, many": "laew",
    "swift": "lagor",
    "thread": "lain",
    "free, freed": "lain",
    "lalaith": "laughter",
    "lalf": "elm tree",
    "lalorn": "elm tree",
    "lalven": "elm tree",
    "lalwen": "elm tree",
   "tongue, dialect, language": "lam",
    "echo": "lamath",
    "throat": "lanc",
    "sharp edge, sudden end, brink": "lanc",
    "naked": "lanc",
    "level, open space": "land",
    "cutlass, sword": "lang",
    "fall": "lant",
    "clearing in forest": "lant",
    "waterfall": "lanthir",
    "autumn": "lasbelin",
    "tea": "lasguil",
    "leaf": "lass",
    "listen": "lasta-",
    "thong": "lath",
    "eavesdrop": "lathra-",
    "warm": "laug",
    "ringlet": "laus",
    "lick": "lav-",
    "animal (quadrupedal mammal)": "lavan",
    "no! don't!": "law",
    "index finger": "lebdas",
    "finger": "leber",
    "five": "leben",
    "middle finger": "lebenedh",
    "ring finger": "lebent",
    "tree (sort of)": "lebethron",
    "small finger": "lebig",
    "left Behind": "lefn",
    "week of five days": "lefnor",
    "fifth": "lefnui",
    "rapid, swift": "legrin",
    "set free, release": "leithia-",
    "freeing, release": "leithian",
    "way-bread, journey-bread": "lembas",
    "tuneful, sweet": "lend",
    "journey, way": "lend",
    "boundary, lest, girdle": "lest",
    "eavesdropper (fem)": "lethril",
    "pick up, pick out": "leutha-",
    "ill, sick, sickly": "lhaew",
    "lean, thin, meager": "lhain",
    "pair of ears": "lhaw",
    "filament, spider filament": "lhê",
    "ear": "lhewig",
    "slender, fine": "lhind",
    "cobweb, spider, spider's web": "lhing",
    "disease, sickness": "lhîw",
    "rustling sound, whisper": "lhoss",
    "dragon, snake, serpent": "lhûg",
    "link, articulation": "lîf",
    "dance": "liltha-",
    "clear, sparkling": "lim",
    "fish": "lim",
    "sea serpent, fish dragon": "limlug",
    "moisten": "limmida-",
    "wet": "limp",
    "lake, pool": "lîn",
    "air (of music), song, tune, singer": "lind",
    "chant, sing": "linna-",
    "couplet": "linnod",
    "swift": "lint",
    "line, row": "lîr",
    "sing": "liria-",
    "reed": "lisc",
    "ash, sand, dust": "lith",
    "ashen, ashy": "lith",
    "shallow lake": "lô",
    "horse": "lobor",
    "ringlet": "loch",
    "float": "loda-",
    "pool": "loeg",
    "soaking wet": "loen",
    "weary": "lom",
    "haven, harbour, pass, strait": "lond",
    "heavy": "long",
    "anchorage, haven, harbour, quiet water": "lorn",
    "snow": "loss",
    "snowy": "lossen",
    "Snow Men (People)": "lossoth",
    "empty, void": "lost",
    "sleep": "losta-",
    "blossom, flower": "loth",
    "single flower": "lotheg",
    "waste, wild": "lothren",
    "May": "lothron",
    "time, occasion": "lû",
    "blue": "luin",
    "grasp, seize": "mab-",
    "hand": "mâb",
    "seize": "maba-",
    "eat": "mad-",
    "soft": "mae",
    "well": "mae",
    "dough": "maeas",
    "sharp-eyed": "maecheneb",
    "shapely": "maed",
    "handy, skilled": "maed",
    "sharp, penetrating": "maeg",
    "lust": "mael",
    "stain, stained": "mael",
    "lustful": "maelui",
    "clever, skilled": "maen",
    "art, craft, handcraft": "maenas",
    "fit, useful, good": "maer",
    "battle of two or a few": "maeth",
    "deal with, handle, wield, manage": "maetha-",
    "warrior": "maethor",
    "gull": "maew",
    "sword": "magol",
    "swordsman": "magor",
    "pale, fawn": "maidh",
    "dear": "mail",
    "chief, main, prime, prominent": "main",
    "pollen, yellow powder": "main",
    "gold (metal)": "malad",
    "yellow": "malen",
    "gold (color?)": "mall",
    "spell": "luith",
    "quench": "luithia-",
    "enchantress": "luithien",
    "shadow": "lum",
    "shady": "lumren",
    "boat": "lunt",
    "charm, enchantment, magic": "lûth",
    "charm, enchant": "lûth",
    "snake": "lýg",
    "golden": "mallen",
    "golden tree": "mallorn",
    "flower of gold": "mallos",
    "gold": "malt",
    "sunlight, radiance": "malt",
    "golden": "malthen",
    "fallow, pale": "malu",
    "departed spirit": "mân",
    "who? what?": "man",
    "final end, fate, fortune": "manadh",
    "food": "mann",
    "feel, stroke, handle, wield": "matha-",
    "gloom, night": "maur",
    "soil, stain": "maw",
    "bear": "medli",
    "bearish, of bear": "medlin",
    "last": "medui",
    "sharp, pointed, piercing": "megor",
    "love": "mel-",
    "greedy": "melch",
    "friend": "meldir",
    "friend (fem.)": "meldis",
    "love": "meleth",
    "lover (fem.)": "melethril",
    "lover (masc.)": "melethron",
    "dear": "mell",
    "incite": "meltha-",
    "sweet": "melui",
    "road, way": "mên",
    "thousand": "meneg",
    "heaven": "menel",
    "send": "menna-",
    "pointe": "ment",
    "festive, joyous": "meren",
    "feast, festival": "mereth",
    "rose": "meril",
    "nightingale": "merilin",
    "wet": "mesc",
    "end": "meth",
    "in": "mi",
    "kiss": "mib-",
    "little kiss": "mib",
    "dew": "midh",
    "affection, love, kindness": "mîl",
    "friendly, loving, kind": "milui",
    "towering": "mîn",
    "peak": "mîn",
    "one, number one": "mîn",
    "distinct, unique, single": "mîn",
    "city with watchtower": "minas",
    "river city": "minas-nim",
    "mirrors, seeing": "ming",
    "morning twilight": "minuial",
    "pear": "mir",
    "fruit": "mirda-",
    "jewel": "miriel",
    "precious": "miru",
    "month": "mis",
    "sea-breeze": "mistral",
    "silver": "mith",
    "true-silver": "mithril",
    "silver-haired": "mithrils",
    "beard": "mo",
    "nourished": "mod",
    "wealth": "mod",
    "enriched": "moden",
    "hill": "moeth",
    "shadow": "moth",
    "shadowy": "mothen",
    "dusk": "mothron",
    "water": "muin",
    "mud": "muld",
    "swine": "mur",
    "moon": "murth",
    "foal, young horse": "mûl",
    "speech": "mûl",
    "secrecy": "murtha",
    "black": "môr",
    "night": "mor",
    "black": "morn",
    "dark": "morn",
    "sorcery": "morr",
    "shadow": "moth",
    "nightshade": "mortha",
    "clot, blood-clot": "môrtha",
    "bear": "mug",
    "magic": "mul",
    "darkness": "múra",
    "dream": "múran",
    "hidden": "múrauth",
    "dark": "múrn",
    "light, lantern": "naur",
    "lamp": "naur",
    "fire": "naur",
    "torch": "naurgal",
    "light, fire": "naurim",
    "hearth": "naus",
    "cloud": "nef",
    "shade, shadow": "nefu",
    "darkness": "nef",
    "eclipse": "neffon",
    "cloudy": "nefrin",
    "shady, shadowy": "nefro",
    "shade, dark place": "nefu",
    "flame": "ngaur",
    "flame, fire": "ngauru",
    "shadowy": "ngaurûn",
    "shadow": "ngaust",
    "haunted place": "ngaurun",
    "black": "nibin",
    "night": "no",
    "darkness": "nod",
    "black": "nogor",
    "shadow": "núath",
    "night": "nuin",
    "blackness": "nûr",
    "shadow": "nûrath",
    "black": "núrod",
    "dark, black": "nûrû",
    "shady, shadowy": "núrûn",
    "shadow": "núrwath",
    "blackness, darkness": "nûrsûl",
    "night": "nusil",
    "nightshade": "nusiloth",
    "black": "nusûl",
    "darkness": "nûtho",
    "dark, shadowy": "nûrûn",
    "shadow": "núthl",
    "dark": "núthûn",
    "nightshade": "nuthus",
    "dark, black": "nyr",
    "shadow, dark place": "nyra",
    "shade": "nythl",
    "nightshade": "nythil",
    "blackness, shadow": "nythlûn",
    "night": "nythw",
    "shadow, black": "nûthlûn",
  "track": "râd",
  "walk": "pada-",
  "ten": "pae",
  "petrel": "paen",
  "theth": "paenen",
  "tenth": "paenui",
  "syrup": "paich",
  "juice": "paich",
  "far off": "palan-",
  "surface": "palath",
  "all": "pân",
  "plank": "pân",
  "board": "pân",
  "floor": "panas",
  "courtyard": "pand",
  "wide": "pann",
  "fill": "panna-",
  "enlarge": "panna-",
  "open": "panna-",
  "complete": "pant",
  "full": "pant",
  "whole": "pant",
  "shaven": "paran",
  "smooth": "paran",
  "book": "parf",
  "field": "parth",
  "enclosed grassland": "parth",
  "arrange": "partha-",
  "compose": "partha-",
  "fullness": "pathred",
  "sward": "pathu",
  "fist": "paur",
  "sickness": "paw",
  "say": "ped-",
  "speak": "ped-",
  "dot": "peg",
  "wither": "pel-",
  "fade": "pel-",
  "enclosure": "pêl",
  "garth": "pêl",
  "withering": "peleth",
  "fading": "pelin",
  "pivot": "pelthaes",
  "without": "pen",
  "anybody": "pen",
  "one": "pen",
  "somebody": "pen",
  "declivity": "pend",
  "slope": "pend",
  "stairway": "pendrath",
  "bow": "peng",
  "fix": "penia-",
  "set": "penia-",
  "slant down": "penna-",
  "history": "pennas",
  "last day of the year": "penninor",
  "story": "pent",
  "half": "per-",
  "Half-Elf": "peredhel",
  "Halfling": "perian",
  "Hobbit": "perian",
  "bitter": "saer",
  "poison": "saew",
  "new": "sain",
  "herb": "salab",
  "broth": "salph",
  "liquid food": "salph",
  "soup": "salph",
  "chamber": "sam",
  "neighbour": "sammar",
  "garden": "sant",
  "field": "sant",
  "yard": "sant",
  "grave": "sarch",
  "stone": "sarn",
  "cairn": "sarnas",
  "pile of stones": "sarnas",
  "drain": "sautha-",
  "juice": "saw",
  "rest": "sedh-",
  "set aside": "seidia-",
  "daughter": "sell",
  "girl": "sell",
  "maid": "sell",
  "this": "sen",
  "Grey-Elf": "send",
  "guesthouse": "sennas",
  "instead": "sennui",
  "rather": "sennui",
  "blood": "sereg",
  "burning": "ruin",
  "fiery red": "ruin",
  "blazing fire": "ruin",
  "slot": "ruin",
  "spoor": "ruin",
  "track": "ruin",
  "footprint": "ruin",
  "anger": "ruith",
  "fox": "rusc",
  "copper": "rust",
  "of copper": "rustui",
  "hound of chase": "rýn",
  "stonecrop (plant)": "seregon",
  "peeble-bank": "serni",
  "friend": "seron",
  "lover": "seron",
  "now": "si",
  "here": "sí",
  "peace": "sîdh",
  "necklace": "sigil",
  "dagger": "sigil",
  "knife": "sigil",
  "shine white": "síla-",
  "silima": "silef",
  "the crystal substance of the Silmarils": "silef",
  "Silmaril": "Silevril",
  "glittering white": "silivren",
  "these": "sin",
  "tidings": "siniath",
  "news": "siniath",
  "novel": "sinnarn",
  "tale": "sinnarn",
  "rill": "sîr",
  "river": "sîr",
  "today": "sîr",
  "flow": "siria-",
  "river": "sirion",
  "flowing": "sirith",
  "drink": "soga",
  "drunk": "sogannen",
  "close": "sol-",
  "root (edible)": "solch",
  "closed": "sollen",
  "as": "sui",
  "like": "sui",
  "hail": "suil",
  "goblet": "sûl",
  "wind": "sûl",
  "few": "sun",
  "brooch": "tachol",
  "pin": "tachol",
  "two": "tâd",
  "two-legged": "tad-dal",
  "double": "tadol",
  "second": "tadui",
  "boundary": "taeg",
  "boundary line": "taeg",
  "long and thin": "taen",
  "height": "taen",
  "summit of high mountain": "taen",
  "exact": "taer",
  "nail": "taes",
  "fasten": "taetha-",
  "tie": "taetha-",
  "clasp": "taew",
  "holder": "taew",
  "socket": "taew",
  "hasp": "taew",
  "staple": "taew",
  "blocked": "tafnen",
  "stopped": "tafnen",
  "closed": "tafnen",
  "mark": "tagol",
  "supporting": "taid",
  "second in command": "taid",
  "marking (a boundary)": "taig",
  "mark": "taith",
  "foot": "tâl",
  "incline": "talad",
  "floor": "talaf",
  "harper": "talagan",
  "floor": "talan",
  "flatlands": "talath",
  "flat surface": "talath",
  "plane": "talath",
  "plain": "talath",
  "low, flat field": "talf",
  "palm (hand)": "talf",
  "table": "talfin",
  "stirrup": "talraph",
  "falling": "talt",
  "slipping": "talt",
  "insecure": "talt",
  "flat": "talu",
  "forge": "tamin",
  "knock": "tamma-",
  "make": "tan-",
  "maker": "tân?",
  "firm": "tanc",
  "bowstring": "tang",
  "confirm": "tangada-",
  "make firm": "tangada-",
  "establish": "tangada-",
  "sign": "tann",
  "stiff": "tara",
  "tough": "tara",
  "steep mountain peak": "tarag",
  "robust": "tarch",
  "firm": "tarias",
  "difficulty": "tarias",
  "stiffness": "tarias",
  "toughness": "tarias",
  "obstinate": "tarlanc",
  "trouble": "tass",
  "willow": "tathar",
  "of willow": "tathren",
  "having willows": "tathren",
  "lofty": "taur",
  "high": "taur",
  "sublime": "taur",
  "noble": "taur",
  "king": "taur",
  "forest": "taur",
  "forester": "tauron",
  "thatch": "taus",
  "woodpecker": "tavor",
  "wool": "taw",
  "of wool": "taw",
  "woolen": "taw",
  "that": "taw?",
  "wood": "tawar",
  "forest": "tawar",
  "wooden": "tawaren",
  "Forest people (Silvan Elves)": "Tawarwaith",
  "line": "tê",
  "row": "tê",
  "pen": "tegil",
  "calligrapher": "tegilbor",
  "play": "teilia-",
  "sport": "teilien",
  "write": "teitha-",
  "stem": "telch",
  "hindmost part": "tele",
  "rear": "tele",
  "end": "tele",
  "Teler": "teler",
  "Teleri (People)": "Telerrim",
  "play": "telia-",
  "sole of the foot": "telluin",
  "dome": "telu",
  "verse (poetry)": "tenn",
  "fine pierced hole": "tess",
  "letter": "têw",
  "sign": "têw",
  "tengwa": "têw",
  "pillar (wood)": "thafn",
  "firm": "thala",
  "steady": "thala",
  "stalwart": "thala",
  "dauntless": "thalion",
  "steadfast": "thalion",
  "hero": "thalion",
  "dauntless": "thalion",
  "steadfast": "thalion",
  "hero": "thalion",
  "hall": "tham",
  "great hall": "thamas",
  "flame": "than-",
  "cleft": "thanc",
  "forked": "thanc",
  "split": "thanc",
  "true": "thand",
  "abiding": "thand",
  "shield": "thand",
  "compulsion": "thang",
  "duress": "thang",
  "need": "thang",
  "oppression": "thang",
  "tyranny": "thang",
  "shield wall": "thangail",
  "shield fence": "thangail",
  "across": "thar-",
  "over": "thar-",
  "beyond": "thar-",
  "stiff grass": "thâr",
  "footstool": "tharas",
  "hassock": "tharas",
  "crossway": "tharbad",
  "rigid": "tharn",
  "sapless": "tharn",
  "stiff": "tharn",
  "withered": "tharn",
  "pine-tree": "thaun",
  "enclosed": "thaur",
  "abhorrent": "thaur",
  "detestable": "thaur",
  "abominable": "thaur",
  "foul": "thaur",
  "builder": "thavron",
  "carpenter": "thavron",
  "wright": "thavron",
  "corrupt": "thaw",
  "rotten": "thaw",
  "mean": "thel-",
  "intend": "thel-",
  "resolve": "thel-",
  "purpose": "thel",
  "will": "thel",
  "sister": "thêl",
  "point of spear": "thela",
  "purpose": "thelion",
  "intention": "thelion",
  "short": "then",
  "strong": "thenid",
  "loyal": "thenid",
  "faithful": "thenid",
  "short": "thent",
  "appear": "thia-",
  "seem": "thia-",
  "glisten": "thilia-",
  "pale": "thind",
  "grey": "thind",
  "grow toward evening": "thinna-",
  "shortness": "thinnas",
  "look": "thîr",
  "face": "thîr",
  "expression": "thîr",
  "helm": "thôl",
  "pine-tree": "thôn",
  "root": "thond",
  "kindler (fem.)": "thoniel",
  "eagle": "thôr",
  "leaping down": "thôr",
  "swooping": "thôr",
  "fence": "thora-",
  "detestable": "thoren",
  "abhorrent": "thoren",
  "abominable": "thoren",
  "fenced": "thoren",
  "guarded": "thoren",
  "hidden": "thoren",
  "torrent": "thórod",
  "eagle": "thoron",
  "smell": "thost",
  "stink": "thosta-",
  "stench": "thû",
  "breathe": "thuia-",
  "breath": "thûl",
  "secret": "thurin",
  "hidden": "thurin",
  "row": "tî",
  "line": "tî",
  "tine": "till",
  "spike": "till",
  "point": "till",
  "sharp horn": "till",
  "metal": "tinc",
  "glint": "tinna-",
  "dusk": "tinnu",
  "twilight": "tinnu",
  "spark": "tint",
  "spark": "tinu",
  "nightingale": "tinúviel",
  "gaze": "tir-",
  "guard": "tir-",
  "watch": "tir-",
  "straight": "tîr",
  "glance": "tîr",
  "view": "tîr",
  "looking": "tîr",
  "watch": "tíra-",
  "vision": "tírad",
  "look toward": "tiria-",
  "watch": "tiria-",
  "guard": "tiria-",
  "gaze": "tiria-",
  "guard": "tirith",
  "horizon": "tiriw",
  "watcher": "tirn",
  "little": "tithen",
  "alphabet": "tiwdi",
  "roof": "toba-",
  "roof": "tobas",
  "deep": "tofn",
  "low": "tofn",
  "low-lying": "tofn",
  "bring": "tog-",
  "lead": "tog-",
  "come": "tol-",
  "middle finger": "toleg",
  "island": "toll",
  "eighth": "tollui",
  "trusty": "tolog",
  "eight": "toloth",
  "eighth": "tolothen",
  "fetch": "toltha-",
  "make come": "toltha-",
  "tall": "tond",
  "resonant (of strings)": "tong",
  "brother": "tôr",
  "hole": "torech",
  "lair": "torech",
  "excavation": "torech",
  "down": "torn",
  "troll": "torog",
  "control": "tortha-",
  "wield": "tortha-",
  "bush (low-growing)": "toss",
  "find": "tov-",
  "shire": "trann",
  "administrative district": "trann",
  "regional": "trannail",
  "local": "trannail",
  "doubt": "trass",
  "worry": "trass",
  "harass": "trasta-",
  "trouble": "trasta-",
  "through": "tre-",
  "recount": "trenar-",
  "tell to end": "trenar-",
  "account": "trenarn",
  "tale": "trenarn",
  "cross": "trevad-",
  "through": "trî",
  "slender": "trîw",
  "not": "ú",
  "without": "ú",
  "monster": "úan",
  "hideous": "uanui",
  "monstrous": "uanui",
  "denial": "ubed",
  "ill deed": "úgarth",
  "sin": "úgarth",
  "always": "ui",
  "everlasting": "ui",
  "eternal": "ui",
  "both": "ui-",
  "two": "ui-",
  "twi-": "ui-",
  "twilight": "uial",
  "closed": "uidafnen",
  "seaweed": "uil",
  "Oiolossë": "Uilos",
  "eternity": "uir",
  "eternal": "uireb",
  "everlasting": "uireb",
  "in": "vi",
  "girl": "wen",
  "virgin": "wen",
  "maiden": "wen",
  "muscle": "tû",
  "vigour": "tû",
  "physical strength": "tû",
  "fat": "tûg",
  "thick": "tûg",
  "bud": "tui",
  "sprout": "tui",
  "spring": "tuia-",
  "swell": "tuia-",
  "swallow": "tuilinn",
  "bud": "tuiw",
  "sprout": "tuiw",
  "support": "tulu",
  "poplar tree": "tulus",
  "deep valley": "tûm",
  "hump": "tump",
  "mound": "tund",
  "control": "tûr",
  "mastery": "tûr",
  "power": "tûr",
  "master": "tûr",
  "victor": "tûr",
  "lord": "tûr",
  "ugly": "ul-",
  "hideous": "ul-",
  "odor": "ûl",
  "bad": "ulug",
  "evil": "ulug",
  "unquenchable": "uluithiad",
  "deformed": "ulunn",
  "hideous creature": "ulunn",
  "monster": "ulunn",
  "bad": "um",
  "evil": "um",
  "creature": "ûn",
  "spider": "ungol",
  "heat": "ûr",
  "fire": "ûr",
  "fire-dragon": "urlug",
  "bogey": "urug",
  "monster": "urug",
  "orc": "urug",
  "hot": "úrui",
  "August": "úrui",
  "evil creature": "uruk",
  "temptation": "úthaes",
  "gulp": "yll",
  "drinking vessel": "ylf",
  "brand": "ylf",
  "twelve": "ýneg",
  "twelfth": "yngui",
  "course": "ýr",
  };
  
  export default elvishDictionary;