const elvishDictionary = {
  O: "interj.",
  and: "conj.",
  after: "ab",
  prohibition: "ablad eblaid",
  bornAfter: "Abonnen Ebennin",
  neck: "achad",
  vengeance: "acharn echern",
  dreadFear: "achas echais",
  againstAgain: "ad",
  againBackSecond: "ad-",
  daddy: "ada edai",
  buildingHouse: "adab edaib",
  Man: "adan",
  FatherOfMen: "adanadar edenedair",
  mortalWoman: "adaneth edenith",
  woman: "edenith",
  father: "adar edair",
  behind: "adel",
  reunite: "adertha-",
  reunion: "aderthad aderthaid",
  slopingTilted: "adlann",
  slantSlope: "adlanna-",
  slantingOblique: "adlant edlaint",
  freeRelease: "adleitha-",
  slopingTilted2: "adlod adloen",
  eveningTwilight: "aduial aduiail",
  if: "ae",
  oceanSea: "aear aeair",
  greatSeaOcean: "Aearon Aearyn? Gaearyn?",
  peakHorn: "aeg aeg",
  sharpPointed: "aeg aeg",
  mountainPeak: "aegas aegais",
  rangeOfMountainPeaks: "aeglir aeglir",
  icicle: "aeglos aeglys",
  gorse: "aeglos aeglys",
  lakePool: "ael aelin",
  sea: "aer aeair",
  hymn: "aerlinn aerlinn",
  seaweed: "aeruil aeruil",
  cookedFood: "aes aes",
  birdSmall: "aew aew",
  gloryBrillianceGlitter: "agar",
  bloodstain: "agarwaen agarwaen",
  glitterBrillianceGlory: "aglar eglair",
  glorious: "aglareb",
  defilePassBetweenHighWalls: "aglonn eglynn",
  narrow: "agor egyr",
  and2: "ah",
  hail: "ai",
  plantBush: "aiglos aiglys",
  pointOfSpear: "aith aith",
  not: "al-",
  Ah: "alae!",
  impetuousRushing: "alag elaig",
  stormOfWind: "alagos elegys",
  immortalNameOfFlower: "alfirin alfirin",
  swan: "alph eilph",
  goingUp: "am-",
  world: "amar emair",
  doom: "amarth emerth",
  fated: "amarthan emerthain",
  shieldWall: "amath emaith",
  uphill: "ambenn",
  hopeBasedOnReason: "amdir amdir",
  crestOfHelmet: "amloth emlyth",
  snakeSerpent: "amlug emlyg",
  why: "amman?",
  us: "ammen",
  hillSteepSidedMount: "amon emyn",
  OrientSunriseEast: "amrún emrŷn",
  for: "an",
  for2: "an-",
  longForALongTime: "anann",
  jawRowOfTeeth: "anc ainc",
  door: "and",
  long: "and",
  longMark: "andaith andaith",
  ageCycle: "andrann endrain",
  climbHighPass: "andrath endraith",
  LongbeardTribeOfDwarves: "Anfang Enfeng",
  LongbeardsPeople: "Anfangrim pl. coll.",
  iron: "ang",
  runicAlphabet: "angerthas",
  approach: "anglenna-",
  magicDeepLore: "angol engyl",
  horror: "angos engyl",
  ofIron: "angren engryn",
  chainIronBond: "angwedh engwidh",
  forMe: "anim",
  desire: "aníra-",
  jaw: "ank enk",
  give: "anna-",
  elephant: "annabon ennebyn",
  giving: "anneth ennith",
  gateDoor: "annon ennyn",
  west: "annû-",
  western: "annui annui",
  SunsetWest: "annûn ennŷn",
  Westron: "Annúnaid",
  Sun: "Anor Anoer",
  gift: "ant aint",
  male: "anu eny",
  awe: "anwar enwair",
  follow: "aphada-",
  follower: "aphadon ephedyn",
  followers: "aphadrim",
  and: "ar",
  outsideWithout: "ar-",
  nobleHighRoyal: "ar-",
  King: "âr êr?",
  nobleHighRoyal2: "ara-",
  day: "arad eraid",
  wolf: "araf eraif",
  king: "aran erain",
  kingdomRealm: "aranarth",
  deer: "aras erais",
  throne: "archam erchaim",
  realmRegion: "ardh erdh",
  provinceGreatRegion: "ardhon erdhyn",
  nobleRoyal: "arn",
  kingdom: "arnad ernaid",
  numberlessUnnumbered: "arnediad arnediaid?",
  royal2: "arnen ernin",
  noble: "arod aroed",
  countlessInnumerable: "aronoded erenedid",
  nobleMan: "arphen erphin",
  exaltedLoftyNoble: "arth erth",
  nobleLady: "arwen erwin",
  violentRushingImpetuous: "ascar escair",
  violentRushingImpetuous2: "asgar",
  dustSandAsh: "ast aist",
  onBothSides: "ath-",
  beyond: "athan",
  acrossBeyond: "athar",
  thumbLittleFather: "atheg ethig",
  kingsfoil: "athelas ethelais",
  cross: "athra-",
  debate: "athrabeth ethrebith",
  crossingFord: "athrad ethraid",
  traverseCross: "athrada-",
  wrongMistake: "athranna-",
  dayMorning: "aur oer",
  warBattle: "auth oeth",
  apparition: "auth oeth",
  dontDo: "av-",
  willNot: "ava-",
  refusalReluctance: "avad evaid",
  ElfOfBeleriand: "avar evair",
  dont: "avo!",
  staying: "avorn evyrn",
  abandonment: "awarth",
  abandon: "awartha-",
  articleForExchange: "bach baich",
  pedlar: "bachor bechyr",
  go: "bad-",
  pathwayBeatenTrack: "bâd baid",
  judge: "badhor bedhyr",
  judge: "badhron bedhryn",
  beautifulFair: "bain bain",
  divinityDivinePower: "bâl bsil",
  divine: "bâl bsil",
  ValaDivinity: "balan belain",
  cruel: "balch boeg",
  fireDemon: "balrog belryg?",
  custodyPrison: "band baind",
  beauty: "baneth",
  trade: "banga-",
  dwellingHouseHomeFamilyLandEarth: "bâr bair",
  eagerFiery: "bara berai",
  doomed: "barad beraid",
  fortressFortTower: "barad beraid",
  steep: "baradh beraidh",
  brownSwartDark: "baran berain",
  doom: "bartha-",
  loafRoundBread: "basgorn besgyrn",
  bread: "bass bais",
  breadGiverFeminine: "bassoneth bassonith",
  trample: "batha-",
  judgmentSentence: "baudh boedh",
  oppressiveCruelTyrannous: "baug boeg",
  constrainOppress: "baugla-",
  constrainerOppressorTyrant: "bauglir bauglir",
  constrainerOppressorTyrant2: "baugron baugryn",
  torment: "baul boel",
  need: "baur boer",
  noDont: "baw",
  accordingTo: "be",
  strength: "bel bil",
  greatMighty: "beleg belig",
  strongInBody: "bell bill",
  strength2: "bellas bellais",
  accordingTo2: "ben",
  manHusband: "benn binn",
  angle: "bennas bennais",
  bold: "beren",
  spouseQueen: "bereth berith",
  protect: "beria-",
  leap: "cab-",
  leap2: "cabed cebid",
  frog: "cabor cebyr",
  formedShaped: "cadu cedy",
  shapely: "cadwar cedwair",
  dare: "bertha-",
  womanWife: "bess biss",
  breadGiverFeminine2: "bessain bessain",
  beatWings: "blab-",
  on: "bo",
  banProhibit: "boda-",
  must: "boe",
  trustyManSteadfastMan: "bôr býr",
  trust: "bora-",
  hot: "born byrn",
  puddleSmallPool: "both byth",
  sudden: "bragol bragoel",
  fierceWild: "braig braig",
  fineHighLoftyNoble: "brand braind",
  lord: "brannon brennyn",
  whiteHeat: "brass brais",
  whiteHot: "brassen",
  livelySuddenQuick: "brêg brîg",
  suddenly: "breged bregid",
  suddennessViolence: "breged bregid",
  wildfire: "bregedúr bregedŷr",
  suddenViolent: "bregol bregoel",
  fierceness: "bregolas bregolais",
  breakOutSuddenly: "breitha-",
  endure: "brenia-",
  lady: "brennil brennil",
  birchTree: "brethil brethil",
  gravel: "brith brith",
  pebbly: "brithon brithoen",
  bear: "brôg brýg",
  lastSurvive: "brona-",
  survival: "bronad brenaid",
  enduring: "bronadui bronadui",
  endurance: "bronwe",
  loudNoisy: "brui brui",
  oldWorn: "brûn bruin",
  serveHoldAllegiance: "buia-",
  snoutNose: "bund bynd",
  vassalFollower: "býr",
  earth: "cae cae",
  lieOnTheGround: "caeda-",
  lyingInBedSickness: "cael cael",
  bedriddenSick: "caeleb caelib",
  ten: "caer",
  lair: "caew",
  hedge: "cai",
  fenceWithSpikes: "cail",
  ship: "cair",
  light: "calad",
  day: "calan",
  lamp: "calar",
  lampwright: "calardan",
  Elda: "calben",
  green: "calen",
  hero: "callon",
  vessel: "calph",
  hand: "cam",
  handsPalm: "camlann",
  callShoutCry: "can-",
  four: "canad",
  townCity: "canas",
  farthingFourthPart: "canath",
  bold: "cand",
  shaping: "cannas",
  fourth: "cannui",
  outlineShape: "cant",
  fourth: "canthui",
  buildMakeDo: "car-",
  buildingHouse: "car",
  hat: "carab",
  jawRowOfTeeth: "carach",
  hedgeOfSpikes: "caraes",
  spikeToothOfRock: "carag",
  red: "caran",
  townCity: "caras",
  fang: "carch",
  deedHouseBuilding: "cardh",
  doingMaking: "cared",
  headlandCape: "cast",
  tressureHairnet: "cathrae",
  afflictionHeavyBurden: "caul",
  clamourOutcry: "caun",
  top: "caw",
  stakeSpike: "ceber",
  soil: "cêf",
  earthen: "cefn",
  earthenware: "cefnas",
  streamLittleRiver: "cel",
  brilliant: "celair",
  silver: "celeb",
  likeSilver: "celebren",
  agileSwift: "celeg",
  streamFlowing: "celeth",
  ofSilver: "celevon",
  flowing: "cell",
  river: "celon",
  springWater: "celos",
  sourceSpring: "celu",
  see: "cen-",
  sightSeeing: "cened",
  mirror: "cenedril",
  potter: "cennan",
  sickle: "cerch",
  doerMaker: "ceredir",
  moundEnclosure: "cerin",
  rune: "certh",
  alphabetRunic: "certhas",
  July: "cerveth",
  earth: "ceven",
  choose: "cil-",
  renewal: "cîl",
  cleftPassBetweenHills: "cîl",
  haven: "círbann",
  shipbuilder: "círdan",
  sailorShipman: "cirion",
  cleftCuttingPass: "cirith",
  freshNew: "cîw",
  splendourGlory: "claur",
  bay: "côf",
  empty: "cofn",
  bearCarry: "col-",
  goldMetal: "côl",
  cloak: "coll",
  hollow: "coll",
  redScarlet: "coll",
  mayor: "condir",
  commanding: "conui",
  crow: "corch",
  smallRedApple: "cordof",
  ring: "corf",
  circle: "corn",
  circularRoundGlobed: "corn",
  ballGlobeMound: "coron",
  wilyCunning: "coru",
  quarrel: "cost",
  enmityEnemy: "coth",
  crow: "craban",
  cake: "caew",
  hedge: "cai",
  fenceWithSpikes: "cail",
  ship: "cair",
  light: "calad",
  day: "calan",
  lamp: "calar",
  lampwright: "calardan",
  Elda: "calben",
  green: "calen",
  hero: "callon",
  vessel: "calph",
  hand: "cam",
  handsPalm: "camlann",
  callShoutCry: "can-",
  four: "canad",
  townCity: "canas",
  farthingFourthPart: "canath",
  bold: "cand",
  shaping: "cannas",
  fourth: "cannui",
  outlineShape: "cant",
  fourth: "canthui",
  buildMakeDo: "car-",
  buildingHouse: "car",
  hat: "carab",
  jawRowOfTeeth: "carach",
  hedgeOfSpikes: "caraes",
  spikeToothOfRock: "carag",
  red: "caran",
  townCity: "caras",
  fang: "carch",
  deedHouseBuilding: "cardh",
  doingMaking: "cared",
  headlandCape: "cast",
  tressureHairnet: "cathrae",
  afflictionHeavyBurden: "caul",
  clamourOutcry: "caun",
  top: "caw",
  stakeSpike: "ceber",
  soil: "cêf",
  earthen: "cefn",
  earthenware: "cefnas",
  streamLittleRiver: "cel",
  brilliant: "celair",
  silver: "celeb",
  likeSilver: "celebren",
  agileSwift: "celeg",
  streamFlowing: "celeth",
  ofSilver: "celevon",
  flowing: "cell",
  river: "celon",
  springWater: "celos",
  sourceSpring: "celu",
  see: "cen-",
  sightSeeing: "cened",
  mirror: "cenedril",
  potter: "cennan",
  sickle: "cerch",
  doerMaker: "ceredir",
  moundEnclosure: "cerin",
  rune: "certh",
  alphabetRunic: "certhas",
  July: "cerveth",
  earth: "ceven",
  choose: "cil-",
  renewal: "cîl",
  cleftPassBetweenHills: "cîl",
  haven: "círbann",
  shipbuilder: "círdan",
  sailorShipman: "cirion",
  cleftCuttingPass: "cirith",
  freshNew: "cîw",
  splendourGlory: "claur",
  bay: "côf",
  empty: "cofn",
  bearCarry: "col-",
  goldMetal: "côl",
  cloak: "coll",
  hollow: "coll",
  redScarlet: "coll",
  mayor: "condir",
  commanding: "conui",
  crow: "corch",
  smallRedApple: "cordof",
  ring: "corf",
  circle: "corn",
  circularRoundGlobed: "corn",
  ballGlobeMound: "coron",
  wilyCunning: "coru",
  quarrel: "cost",
  enmityEnemy: "coth",
  crow: "craban",
  cake: "cram",
  ruddyOfFace: "crann",
  cleftGulfRavine: "criss",
  cleaverSword: "crist",
  reap: "critha-",
  left: "crom",
  leftHand: "crum",
  guiltyWilySinister: "crumguru",
  leftHanded: "crumui",
  archBowCrescent: "cû",
  dove: "cugu",
  live: "cuia-",
  down: "dad",
  slantDownInclined: "dadbenn",
  greatLarge: "dae",
  exceedinglyVery: "dae",
  shadowShade: "dae",
  canopy: "daedelu",
  corpse: "daen",
  bridegroom: "daer",
  large: "daer",
  permission: "dâf",
  slay: "dag-",
  bane: "dagnir",
  battle: "dagor",
  doBattleMakeWar: "dagra-",
  hammer: "dam",
  answerResponse: "dambeth",
  hammer: "damma-",
  butHowever: "dan",
  against: "dan",
  soundNoise: "dang",
  slain: "dangen",
  answerReply: "dangweth",
  fall: "danna-",
  autumn: "dannas",
  fallen: "dannen",
  ebb: "dannen",
  fallFalling: "dant",
  Nandor: "Danwaith",
  life: "cuil",
  alive: "cuin",
  beAlive: "cuina-",
  load: "cûl",
  heapMound: "cûm",
  bentBowShaped: "cûn",
  prince: "cund",
  crescentMoon: "cúron",
  cunningDevice: "curu",
  wizard: "curunír",
  bearer: "cyll",
  renewed: "cŷr",
  newMoon: "cýron",
  ransom: "danwedh",
  haltStop: "dar-",
  endureStayWaitRemainLast: "dartha-",
  abyssChasmVoidGulf: "dath",
  soldierOrkish: "daug",
  leaguePauseStop: "daur",
  gloomNighttime: "daw",
  victorWinner: "degil",
  disgust: "dêl",
  horribleLoathsome: "deleb",
  conceal: "delia-",
  abhorrenceFearHorrorDreadDetestationLoathing: "delos",
  deadlyHatefulFell: "delu",
  gloomySad: "dem",
  Nandor: "Denwaith",
  youngMaiden: "dess",
  under: "di-",
  brideLady: "dî",
  beneathInUnder: "dî",
  forgive: "dihena-",
  stopperStopping: "dîl",
  stopUp: "dilia-",
  stair: "dim",
  sadnessGloom: "dim",
  gapOpeningMountainPass: "dîn",
  silent: "dínen",
  bride: "dineth",
  maleAdultMale: "dîr",
  manSpearhead: "dírnaith",
  bride: "dîs",
  lowGloomy: "dofn",
  goUp: "dol-",
  headHill: "dôl",
  hiddenSecret: "dolen",
  darkDuskyMistyObscure: "doll",
  bossRoundKnob: "dolt",
  conceal: "doltha-",
  fist: "dond",
  blackSwartSwartyShadyShadowy: "donn",
  landDwellingPlaceRegion: "dôr",
  stiffTough: "dorn",
  TrawnFolkDwarfs: "Dornhoth",
  oakTree: "doron",
  dwell: "dortha-",
  burn: "dosta-",
  hewnLog: "drafn",
  blowHeavyStroke: "dram",
  clenchedFistBlowWithFist: "drambor",
  wolf: "draug",
  hew: "drava-",
  forthOutAway: "e-",
  spine: "ech",
  fashionMakeShape: "echad-",
  encampment: "echad",
  follower: "echil",
  outerRingCircle: "echor",
  awakening: "echui",
  wakeUp: "echuia-",
  seasonOfStirringSpring: "echuir",
  pointSpearPoint: "ecthel",
  forthOutAway: "ed-",
  double: "edaid",
  begunAgainNew: "eden",
  Elf: "edhel",
  berylElfStone: "edhelharn",
  elvish: "edhellen",
  anniversaryDay: "edinor",
  goToExile: "edledh-",
  flee: "dreg-",
  flee: "drega-",
  flee: "drego!",
  hammer: "dring",
  beat: "dringa-",
  WildMan: "Drúadan",
  WildMen: "Drúath",
  darknessNightNightfallDusk: "dû",
  riverLargeRiverWithCurrent: "duin",
  tide: "duinen",
  riverbank: "duirro",
  nightingale: "dúlinn",
  West: "dûn",
  NúmenóreanManOfTheWest: "dúnadan",
  ElfOfBeleriandWestElfIncludingNoldorAndSindar: "dúnedhel",
  dark: "dûr",
  west: "dúven",
  successor: "dŷr",
  goToExile: "edledhia-",
  Exiled: "Edledhron",
  exiled: "edlenn",
  blossom: "edlothia-",
  flower: "edlothia-",
  flowering: "edlothiad",
  beget: "edonna-",
  open: "edra-",
  border: "edrain",
  savingSalvation: "edraith",
  especially: "edregol",
  second: "edwen",
  thorn: "êg",
  ForsakenSindarFalathrim: "Egladhrim",
  forsaken: "eglan",
  manSpearhead: "dírnaith",
  bride: "dîs",
  lowGloomy: "dofn",
  goUp: "dol-",
  headHill: "dôl",
  hiddenSecret: "dolen",
  darkDuskyMistyObscure: "doll",
  bossRoundKnob: "dolt",
  conceal: "doltha-",
  fist: "dond",
  blackSwartSwartyShadyShadowy: "donn",
  landDwellingPlaceRegion: "dôr",
  stiffTough: "dorn",
  TrawnFolkDwarfs: "Dornhoth",
  oakTree: "doron",
  dwell: "dortha-",
  burn: "dosta-",
  hewnLog: "drafn",
  blowHeavyStroke: "dram",
  clenchedFistBlowWithFist: "drambor",
  wolf: "draug",
  hew: "drava-",
  forthOutAway: "e-",
  spine: "ech",
  fashionMakeShape: "echad-",
  encampment: "echad",
  follower: "echil",
  outerRingCircle: "echor",
  awakening: "echui",
  wakeUp: "echuia-",
  seasonOfStirringSpring: "echuir",
  pointSpearPoint: "ecthel",
  forthOutAway: "ed-",
  double: "edaid",
  begunAgainNew: "eden",
  Elf: "edhel",
  berylElfStone: "edhelharn",
  elvish: "edhellen",
  anniversaryDay: "edinor",
  goToExile: "edledh-",
  flee: "dreg-",
  flee: "drega-",
  flee: "drego!",
  hammer: "dring",
  beat: "dringa-",
  wildMan: "drû",
  WildMan: "Drúadan",
  WildMen: "Drúath",
  darknessNightNightfallDusk: "dû",
  riverLargeRiverWithCurrent: "duin",
  tide: "duinen",
  riverbank: "duirro",
  nightingale: "dúlinn",
  West: "dûn",
  NúmenóreanManOfTheWest: "dúnadan",
  ElfOfBeleriandWestElfIncludingNoldorAndSindar: "dúnedhel",
  dark: "dûr",
  west: "dúven",
  successor: "dŷr",
  goToExile: "edledhia-",
  Exiled: "Edledhron",
  exiled: "edlenn",
  blossom: "edlothia-",
  flower: "edlothia-",
  flowering: "edlothiad",
  beget: "edonna-",
  open: "edra-",
  border: "edrain",
  savingSalvation: "edraith",
  especially: "edregol",
  second: "edwen",
  thorn: "êg",
  ForsakenSindarFalathrim: "Egladhrim",
  forsaken: "eglan",
  glorifyPraise: "egleria-",
  sharpPoint: "egnas",
  beOff: "ego!",
  SindaOneOfTheForsaken: "egol",
  or: "egor",
  rain: "eilia-",
  rainbow: "eilian",
  rainBow: "eiliant",
  elder: "einior",
  daisy: "eirien",
  insultPrickWithSharpPoint: "eitha-",
  insult: "eithad",
  issueOfWaterSpringWell: "eithel",
  star: "êl",
  StarSunFlower: "elanor",
  pimpernelFlower: "elanor",
  ElvesPeople: "Eledhrim",
  Elf: "elen",
  elfWoman: "elleth",
  elfMan: "ellon",
  singleFlower: "elloth",
  admirationExclamationOf: "elo!",
  ElvesPeople: "Elrim",
  paleBlue: "elu",
  Sindar: "Eluwaith",
  ElfFriend: "elvellon",
  mother: "emel",
  motherFingerIndex: "emig",
  yellowBirdYellowhammer: "emlin",
  sixth: "enchui",
  centerCoreMiddle: "enedh",
  midyear: "enedhin",
  six: "eneg",
  six: "engui",
  there: "ennas",
  soulSpirit: "fae",
  badPoorMean: "faeg",
  longYearValianYear: "ennin",
  MiddleEarth: "Ennor",
  landsOfMiddleEarth: "ennorath",
  encirclingFenceOuterFence: "ephel",
  loneAloneOne: "er-",
  singleFirstAlone: "er",
  prickle: "erch",
  prickPointStick: "ercha-",
  oneHanded: "erchamion",
  oneHanded: "erchammon",
  oneHanded: "erchammui",
  orkish: "erchion",
  isolatedLonely: "ereb",
  germSeed: "eredh",
  holly: "ereg",
  holly: "eregdos",
  riseArise: "eria-",
  aloneFirstSingle: "eriol",
  prince: "ernil",
  unite: "ertha-",
  union: "erthad",
  GodTheOne: "Eru",
  wasteTheOneNameOfGod: "eru",
  aloneFirstSingle: "erui",
  woodForest: "eryn",
  forestFire: "erynaur",
  coverVeilScreen: "escal",
  veilScreen: "esgal",
  bankShore: "esgar",
  waterFall: "espalass",
  callName: "esta-",
  faithHopeTrust: "estel",
  short: "estent",
  encampment: "estolad",
  spy: "ethir",
  estuaryMouthOrOutflowOfARiver: "ethir",
  spring: "ethuil",
  gleamingBrilliance: "fael",
  fairMindedJustGenerous: "fael",
  sparklingDragon: "faelug",
  radiant: "faen",
  spirit: "faer",
  white: "fain",
  mortalMan: "fair",
  beachShoreCoastStrandLineOfSurfFoamingShore: "falas",
  ofTheShore: "falathren",
  peopleOfTheFalas: "Falathrim",
  cleftRavine: "falch",
  breakerFoam: "falf",
  foam: "faltha-",
  cloudVeilManifestedBodyOfAVala: "fân",
  beard: "fang",
  cloudy: "fanui",
  enough: "far",
  hunt: "fara-",
  huntHunting: "farad",
  huntersPeople: "faradrim",
  huntHunting: "faras",
  enough: "farn",
  hunter: "faron",
  hunters: "faroth",
  shaggyHair: "fast",
  chokingGaspingThirsty: "faug",
  cloud: "faun",
  shoreBeach: "faur",
  suffice: "feiria-",
  cave: "fela",
  doorThreshold: "fend",
  gatewayDoor: "fennas",
  beechMast: "fêr",
  hunter: "feredir",
  dead: "fern",
  catch: "gad-",
  dungeonPrison: "gador",
  dreadFear: "gae",
  oceanSea: "gaear",
  GreatOcean: "gaearon",
  glitteringPale: "gael",
  dreadfulFearfulHoly: "gaer",
  sea: "gaer",
  reddishCopperColouredRuddy: "gaer",
  deadDeadPerson: "fern",
  northern: "fervain",
  birdSmall: "fileg",
  smallBird: "filigod",
  slimSlender: "fim",
  hairLockOfHairTress: "fîn",
  lockOfHairTress: "find",
  lockOfHair: "fing",
  braidedTressOfHair: "finnel",
  dieFade: "fir-",
  mortal: "fíreb",
  mortal: "fíreb",
  human: "firen",
  MortalHumains: "firiath",
  mortalMaiden: "fíriel",
  mortalWoman: "firieth",
  mortal: "firin",
  mortalMan: "firion",
  seasonOfFadingAutumn: "firith",
  skilledHandy: "flâd",
  northRight: "fôr",
  rightHanded: "forgam",
  north: "forod",
  NorthmenNorthfolk: "forodrim",
  NorthmenNorthfolkNorthRegions: "forodwaith",
  northDirection: "forven",
  rightHandRightSide: "forvo",
  abhor: "fuia-",
  darknessGloomNightDeadOfNight: "fuin",
  rightHandNorth: "fuir",
  seaWeed: "gaeruil",
  fish: "gail",
  lightBright: "gail",
  light: "gal-",
  grow: "gala-",
  lightBrightSunlightBrillianceRadianceGlitteringReflection: "galad",
  tree: "galadh",
  tangled: "galadhremmen",
    "people of the Trees, Elves of Lórien": "galadhrim",
    growth: "galas",
    "pipe-weed": "galenas",
    blessing: "galu",
    "black metal": "galvorn",
    "claw, hook, crook": "gamp",
    "harp, play a harp": "ganna",
    "harp, play a harp": "gannada",
    harp: "gannel",
    can: "gar",
    wolf: "garaf",
    "defined or bounded place": "gardh",
    own: "garn",
    defend: "gartha",
    hole: "gas",
    apostrophe: "gasdil",
    stopgap: "gasdil",
    cavern: "gath",
    "cave": "gathrod",
    "device": "gaud",
    "wolf-howl": "gaul",
    werewolf: "gaur",
    "werewolf-host": "gaurhoth",
    "outlaws": "gaurwaith",
    void: "gaw",
    howl: "gawa",
    howling: "gawad",
    learn: "gelia",
    merry: "gelir",
    "joy": "gell",
    delight: "gella",
    jubilation: "gellam",
    triumphant: "gellui",
    sickly: "gem",
    reckon: "genedia",
    "count": "genediad",
    worn: "gern",
    "star": "gîl",
    "silver": "gildin",
    starlight: "gilgalad",
    shudder: "gir",
    "horror": "girith",
    December: "Girithon",
    "wood": "glad",
    laugh: "gladha",
    grass: "glae",
    "narrative poem": "glaer",
    salve: "glaew",
    "din, uproar, tumult, shouting, confused noise, a body of Orcs": "glam",
    "yelling-horde": "glamhoth",
    orc: "glamog",
    echo: "glamor",
    echoing: "glamren",
    white: "glân",
    clear: "glân",
    border: "glân",
    boundary: "gland",
    "boundary marker": "glandagol",
    clear: "glanna",
    joy: "glass",
    "golden light": "glaur",
    babble: "glavra",
    babbling: "glavrol",
    radiance: "glaw",
    brilliance: "glaw",
    sunlight: "glawar",
    gold: "glawar",
    bound: "glenia",
    limit: "glenia",
    enclose: "glenia",
    honey: "glî",
    "glint of light": "glîn",
    glance: "glind",
    hanging: "gling",
    dangle: "glinga",
    hang: "glinga",
    glance: "glinna",
    Teler: "glinnel",
    recite: "glir",
    sing: "glir",
    "song": "glîr",
    "dazzling white, white as snow": "gloss",
    soap: "glûdh",
    together: "go",
    "enclosed dwelling": "gobel",
    historical: "gobenathren",
    history: "gobennas",
    "mass of ice": "gochel",
    Noldo: "gódhel",
    "Noldor (people)": "Gódhellim",
    through: "godref",
    together: "godref",
    "great fear, dread": "goe",
    "dire, terrible, fell": "goeol",
    forgive: "gohena",
    "collection of leaves, foliage": "golas",
    branch: "golf",
    wise: "goll",
    "wise man": "gollor",
    Noldo: "golodh",
    "Noldor (people)": "Golodhrim",
    fleurs: "goloth",
    "Noldo Jewel (Silmaril)": "Golovir",
    teach: "goltha",
    wisdom: "golu",
    "learned in deep arts, wise": "golwen",
    entangle: "gonathra",
    entanglement: "gonathras",
    "rock": "gond",
    "ridge": "gondrafn",
    "spike": "gondram",
    causeway: "gondrath",
    "made of stone, stony": "gondren",
    "Master of Stone, Dwarf": "Gonhir",
    count: "gonod",
    "of stone": "gonui",
    conceal: "gor",
    "horror, fear, dread": "gôr",
    vigour: "gôr",
    impetus: "gorf",
    "deadly fear": "gorgor",
    "hasty, vigorous, impetuous": "gorn",
    valour: "gorn",
    horror: "gorog",
    horror: "goroth",
    dead: "gorth",
    "dead person": "gorth",
    barrow: "gorthad",
    horrible: "gortheb",
    "Deads (group of)": "gorthrim",
    terror: "gost",
    fear: "gosta",
    enemy: "goth",
    meet: "govad",
    community: "govannas",
    met: "govannen",
    "compact, contract, treaty": "gowest",
    "creature powerful, hostile and terrible": "graug",
    bear: "graw",
    cave: "grôd",
    "fear": "groga",
    club: "grond",
    "cave, delving, large excavation": "groth",
    ruddy: "gruin",
    fury: "gruith",
    terrify: "gruitha",
    foe: "gûd",
    "evil knowledge, magic, sorcery, necromancy": "gûl",
    "dark sorcery": "guldur",
    "inner mind, heart": "gûr",
    death: "gûr",
    death: "gurth",
    death: "guruth",
    "death-horror, dread of death": "guruthos",
    together: "gwa",
    away: "gwachae",
    "palantir, seeing stone": "gwachaedir",
    "sworn brother": "gwador",
    enfold: "gwaeda",
    bond: "gwaedh",
    gull: "gwael",
    stained: "gwaen",
    windy: "gwaeren",
    March: "gwaeron",
    storm: "gwaew",
    new: "gwain",
    "able-bodied men (troop of), manhood, manpower, host, regiment, people, region, wilderness": "gwaith",
    blossom: "gwaloth",
    "death (act of dying)": "gwanath",
    dead: "gwann",
    depart: "gwanna",
    number: "gwanod",
    "death by fading": "gwanu",
    "pair of twins": "gwanûn",
    "twin": "gwanunig",
    "pair of twin": "gwanûr",
    "relative, brother": "gwanûr",
    "kinsman, kinswoman": "gwanur",
    "Elf of Aman": "gwanwel",
    "departed": "gwanwen",
    "Elve of Aman": "gwanwen",
    "betrayer": "gwarth",
    "stain": "gwass",
    "hummock": "gwastar",
    "shade, shadow, dim light": "gwâth",
    "soil, stain": "gwatha",
    "sister": "gwathel",
    "dim, overshadow, veil, obscure": "gwathra",
    "dim, shadowy": "gwathren",
    "shadowy": "gwathui",
    "Shadowy People (of Dunland)": "Gwathuirim",
    "goose": "gwaun",
    "clothe": "hab",
    "clothes": "hab",
    "shore": "habad",
    "hurl": "had",
    "Dwarf": "hadhod",
    "Khuzdûl": "Hadhodren",
    "Dwarfs (people)": "Hadhodrim",
    "sling": "hadlath",
    "thrower": "hador",
    "thrower of darts, hurler of darts": "hadron",
    "distant, far, on the other side, further": "hae",
    "far, remote, distant": "haer",
    "distance": "haered",
    "far, distant": "haeron",
    "custom, habit": "haew",
    "sit": "haf",
    "them (inanimates)": "hain",
    "left": "hair",
    "left hand": "hair",
    "lift": "hal",
    "clear, sparkling, light": "hâl",
    "dirty, soiled": "gwaur",
    "bind": "gwedh",
    "bond, bond of loyalty": "gwedh",
    "air (as substance)": "gwelu",
    "air (as a region)": "gwelwen",
    "maiden": "gwend",
    "bond of friendship": "gwend",
    "virginity": "gweneth",
    "pair of twin": "gwenyn",
    "betray, cheat": "gweria",
    "oath": "gwest",
    "swear": "gwesta",
    "host, army": "gweth",
    "net, web": "gwî",
    "air (as a region)": "gwilith",
    "butterfly": "gwilwileth",
    "vine, wine": "gwîn",
    "foam": "gwing",
    "baby, little finger": "gwinig",
    "April": "gwirith",
    "butterfly": "gwiwileth",
    "fish": "hâl",
    "seashell": "half",
    "hidden, veiled, shadowed": "hall",
    "exalted, high": "hall",
    "screen": "haltha",
    "chair": "ham",
    "clothe": "hamma",
    "clothing": "hammad",
    "garment": "hamp",
    "brother": "hanar",
    "intelligent": "hand",
    "understanding": "hannas",
    "left (direction)": "hâr",
    "south": "harad",
    "south, southern": "haradren",
    "People of the South": "haradrim",
    "left-handed": "hargam",
    "helmet": "harn",
    "wounded": "harn",
    "southern": "harn",
    "wound": "harna",
    "hope": "hartha",
    "hope": "harthad",
    "wound": "haru",
    "left hand, left side": "harvo",
    "axe-stroke": "hast",
    "hack through": "hasta",
    "blade (of a broadsword or axe)": "hathel",
    "axe, axe blade": "hathol",
    "burial mound, barrow, grave, tomb": "haudh",
    "bed": "haust",
    "sit": "hav",
    "she": "he, hen, hene",
    "keep, retain": "heb",
    "bitterly cold": "helch",
    "glass": "heledh",
    "kingfisher (bird)": "heledir",
    "ice": "heleg",
    "frozen": "helegnen",
    "fur": "heleth",
    "coat": "helf",
    "throat": "hell",
    "naked": "hell",
    "strip": "heltha",
    "child": "hên",
    "eye": "hend",
    "eyed": "heneb",
    "understand": "henia",
    "glance": "henn",
    "window": "henneth",
    "master": "herdir",
    "have an impulse, begin suddenly and vigorously": "heria",
    "master": "heron",
    "household, troop under a lord": "herth",
    "husband": "hervenn",
    "wife": "hervess",
    "lady": "heryn",
    "captain": "hest",
    "that": "i",
    "the": "i",
    "ago": "ia",
    "obscure, foggy, vague": "hethu",
    "heir": "hîl",
    "cool": "him",
    "abiding, steadfast": "him",
    "continually": "him",
    "find": "hir",
    "lord, master": "hîr",
    "Lady": "hiril",
    "fog, mist": "hîth",
    "mist, fog": "hithu",
    "November": "Hithui",
    "foggy": "hithui",
    "sticky": "hîw",
    "harborage": "hobas",
    "rest": "hoda",
    "close": "hol",
    "closed": "hollen",
    "he": "hon",
    "little brother, also the name of the middle finger": "honeg",
    "driven under compulsion": "horn",
    "speed, urge on": "hortha",
    "gross (144)": "host",
    "cold pool, lake": "hoth",
    "crowd, host, horde": "hoth",
    "dog": "hû",
    "dog (hunt)": "huan",
    "harbour, haven, small landlocked bay": "hûb",
    "assembly": "hûd",
    "cry of encouragement in battle": "hûl",
    "heart": "hûn",
    "action, readiness for, vigour, fiery spirit": "hûr",
    "fungus, sponge": "hwand",
    "breeze, puff": "hwest",
    "faintness, giddiness": "hwîn",
    "eddy": "hwind",
    "twirl, whirl, eddy": "hwinia",
    "fantastic": "hwiniol",
    "abyss, chasm, void, gulf": "iâ",
    "neck": "iaeth",
    "mocking, scorn": "iaew",
    "shout, cry": "ial",
    "call out": "ialla",
    "bridge": "iant",
    "bridge": "ianu",
    "blood": "iâr",
    "eldest": "iarwain",
    "where": "ias",
    "fence": "iâth",
    "People of Doriath": "Iathrim",
    "Doriath people": "iathrim",
    "Sinda (of Doriath)": "iathron",
    "fane, holy place, sanctuary": "iaun",
    "ancient, old, former": "iaur",
    "autumn": "iavas",
    "corn (not maize)": "iaw",
    "repose, rest": "îdh",
    "thoughtfulness": "idhor",
    "pondering, wise, thoughtful": "idhren",
    "year": "idhrinn",
    "daughter, girl, maid": "iell",
    "wish": "iest",
    "daily": "ilaurui",
    "I": "im",
    "between, within": "im",
    "between, within": "im-",
    "deep vale, dell": "im",
    "glen, deep valley": "imlad",
    "flowering valley": "imloth",
    "path": "imrad",
    "valley": "imrath",
    "hop": "laba",
    "hare": "laboth",
    "flame": "lacha",
    "flame-eyed, Elf who has lived in the Blessed Realm": "lachenn",
    "valley": "lâd",
    "cleared, plain, flat, wide, open": "laden",
    "great number": "lae",
    "fresh": "laeb",
    "fresh green": "laeg",
    "year": "în",
    "guess, idea, notion": "inc",
    "inner thought, mind, meaning, heart": "ind",
    "suppose": "inga",
    "year sick, old": "ingem",
    "annals": "ínias",
    "will": "innas",
    "female": "inu",
    "ago": "io",
    "flood-water, wash": "iôl",
    "son": "ion",
    "descendant, son": "iôn",
    "descendant, son (coll. pl)": "ionnath",
    "aged, long-lived": "iphant",
    "when": "ir",
    "sexual desire": "îr",
    "desire": "íra",
    "knowledge, lore": "ist",
    "have knowledge": "ista",
    "learned": "istui",
    "moon": "Ithil",
    "magic metal that only mirrors starlight and moonlight": "ithildin",
    "wizard": "ithron",
    "use": "iuith",
    "use": "iuitha",
    "embers": "iûl",
    "blood": "iûr",
    "September": "ivanneth",
    "crystal": "ivor",
    "of crystal": "ivorcheneb",
    "of crystal": "ivren",
    "acute, keen, sharp": "laeg",
    "Green Elf": "laegel",
    "Green Elves (people)": "laegrim",
    "song": "laer",
    "season of summer": "laer",
    "babe, also used in children's play as the name of the little finger": "laes",
    "frequent, many": "laew",
    "swift": "lagor",
    "thread": "lain",
    "free, freed": "lain",
    "lalaith": "laughter",
    "lalf": "elm tree",
    "lalorn": "elm tree",
    "lalven": "elm tree",
    "lalwen": "elm tree",
    "lam": "tongue, dialect, language",
    "lamath": "echo",
    "lanc": [
        "throat",
        "sharp edge, sudden end, brink",
        "naked"
    ],
    "land": "level, open space",
    "lang": "cutlass, sword",
    "lant": [
        "fall",
        "clearing in forest"
    ],
    "lanthir": "waterfall",
    "lasbelin": "autumn",
    "lasguil": "tea",
    "lass": "leaf",
    "lasta-": "listen",
    "lath": "thong",
    "lathra-": [
        "eavesdrop",
        "listen in"
    ],
    "lathrada-": "eavesdrop, listen in",
    "lathron": "eavesdropper",
    "laug": "warm",
    "laus": "ringlet",
    "lav-": "lick",
    "lavan": "animal (quadrupedal mammal)",
    "law": "no! don't!",
    "lebdas": "index finger",
    "lebed": "finger",
    "leben": "five",
    "lebenedh": "middle finger",
    "lebent": "ring finger",
    "leber": "finger",
    "lebethron": "tree (sort of)",
    "lebig": "small finger",
    "lefn": "left Behind",
    "lefnor": "week of five days",
    "lefnui": "fifth",
    "legrin": "rapid, swift",
    "leithia-": "set free, release",
    "leithian": "freeing, release",
    "lembas": "way-bread, journey-bread",
    "lend": [
        "tuneful, sweet",
        "journey, way"
    ],
    "lest": "boundary, lest, girdle",
    "lethril": "eavesdropper (fem)",
    "leutha-": "pick up, pick out",
    "lhaew": "ill, sick, sickly",
    "lhain": [
        "lean, thin, meager",
        "lean, thin, meager"
    ],
    "lhaw": "pair of ears",
    "lhê": "filament, spider filament",
    "lhewig": "ear",
    "lhind": "slender, fine",
    "lhing": [
        "cobweb, spider, spider's web",
        "spider"
    ],
    "lhîw": "disease, sickness",
    "lhoss": "rustling sound, whisper",
    "lhûg": "dragon, snake, serpent",
    "lîf": "link, articulation",
    "liltha-": "dance",
    "lim": [
        "clear, sparkling",
        "fish"
    ],
    "limlug": "sea serpent, fish dragon",
    "limmida-": "moisten",
    "limp": "wet",
    "lîn": [
        "lake, pool",
        "wet"
    ],
    "lind": [
        "air (of music), song, tune, singer",
        "journey, way"
    ],
    "linna-": "chant, sing",
    "linnod": "couplet",
    "lint": "swift",
    "lîr": "line, row",
    "liria-": "sing",
    "lisc": "reed",
    "lith": [
        "ash, sand, dust",
        "ashen, ashy"
    ],
    "lô": "shallow lake",
    "lobor": "horse",
    "loch": "ringlet",
    "loda-": "float",
    "loeg": "pool",
    "loen": "soaking wet",
    "lom": "weary",
    "lond": [
        "haven, harbour, pass, strait",
        "heavy"
    ],
    "long": "heavy",
    "lorn": "anchorage, haven, harbour, quiet water",
    "loss": "snow",
    "lossen": "snowy",
    "lossoth": "Snow Men (People)",
    "lost": "empty, void",
    "losta-": "sleep",
    "loth": "blossom, flower",
    "lotheg": "single flower",
    "lothod": "single flower",
    "lothren": "waste, wild",
    "lothron": "May",
    "lû": "time, occasion",
    "luin": "blue",
    "mab-": "grasp, seize",
    "mâb": "hand",
    "maba-": "seize",
    "mad-": "eat",
    "mae": [
        "soft",
        "well"
    ],
    "maeas": "dough",
    "maecheneb": "sharp-eyed",
    "maed": [
        "shapely",
        "handy, skilled"
    ],
    "maeg": "sharp, penetrating",
    "mael": [
        "lust",
        "stain, stained"
    ],
    "maelui": "lustful",
    "maen": "clever, skilled",
    "maenas": "art, craft, handcraft",
    "maer": "fit, useful, good",
    "maeth": "battle of two or a few",
    "maetha-": "deal with, handle, wield, manage",
    "maethor": "warrior",
    "maew": "gull",
    "magol": "sword",
    "magor": "swordsman",
    "maidh": "pale, fawn",
    "mail": "dear",
    "main": [
        "chief, main, prime, prominent",
        "pollen, yellow powder"
    ],
    "malad": "gold (metal)",
    "malen": "yellow",
    "mall": "gold (color?)",
    "luith": "spell",
    "luithia-": "quench",
    "luithien": "enchantress",
    "lum": "shadow",
    "lumren": "shady",
    "lunt": "boat",
    "lûth": [
        "charm, enchantment, magic",
        "charm, enchant"
    ],
    "lýg": "snake",
    "mallen": "golden",
    "mallorn": "golden tree",
    "mallos": "flower of gold",
    "malt": [
        "gold",
        "sunlight, radiance"
    ],
    "malthen": "golden",
    "malu": "fallow, pale",
    "mân": "departed spirit",
    "man": "who? what?",
    "manadh": "final end, fate, fortune",
    "mann": "food",
    "matha-": "feel, stroke, handle, wield",
    "maur": "gloom, night",
    "maw": "soil, stain",
    "medli": "bear",
    "medlin": "bearish, of bear",
    "medui": "last",
    "megil": "sword",
    "megor": [
        "sharp, pointed, piercing",
        "sharp, pointed"
    ],
    "mel-": [
        "love",
        "love"
    ],
    "mela-": "love",
    "melch": "greedy",
    "meldir": "friend",
    "meldis": "friend (fem.)",
    "meleth": "love",
    "melethril": "lover (fem.)",
    "melethron": "lover (masc.)",
    "mell": "dear",
    "mellon": "friend",
    "meltha-": "incite",
    "melui": "sweet",
    "mên": "road, way",
    "meneg": "thousand",
    "menel": "heaven",
    "menna-": "send",
    "ment": "pointe",
    "meren": "festive, joyous",
    "mereth": "feast, festival",
    "meril": "rose",
    "merilin": "nightingale",
    "mesc": "wet",
    "mesg": "wet",
    "meth": [
        "end",
        "end"
    ],
    "methed": "end",
    "methen": "end",
    "mi": "in",
    "mib-": "kiss",
    "mib": "little kiss",
    "midh": "dew",
    "mil-": "love",
    "mîl": [
        "affection, love, kindness",
        "affection, love"
    ],
    "milui": "friendly, loving, kind",
    "mîn": [
        "towering",
        "peak",
        "one, number one",
        "distinct, unique, single"
    ],
    "minas": "city with watchtower",
    "minas-nim": "river city",
    "ming": "mirrors, seeing",
    "minuial": "morning twilight",
    "mir": "pear",
    "mirda-": "fruit",
    "miriel": "jewel",
    "miru": "precious",
    "mis": "month",
    "mistral": "sea-breeze",
    "mith": "silver",
    "mithril": "true-silver",
    "mithrils": "silver-haired",
    "mo": "beard",
    "mod": [
        "nourished",
        "wealth"
    ],
    "moden": "enriched",
    "moeth": "hill",
    "moth": "shadow",
    "mothen": "shadowy",
    "mothron": "dusk",
    "mothoth": "shadow",
    "mothrim": "shadowy",
    "muin": "water",
    "muld": "mud",
    "mur": "swine",
    "murth": "moon",
    "mus": "foal, young horse",
    "musg": "musky",
    "mûr": "bear",
    "myr": "berry",
    "na": "be",
    "na-": "within",
    "na-f": "in",
    "na-io": "inside",
    "nagor": "foal, colt",
    "naith": "brook",
    "naithad": "a basin",
    "naithoth": "spring",
    "nal": "dear, beloved",
    "nalda-": "be fond of",
    "namad": "father",
    "namaron": "begetter, father",
    "nandar": "homestead",
    "nandor": "wandering people",
    "nanduin": "river",
    "naugl": "jewel",
    "naul": "clay",
    "naur": "fire",
    "nauru": "burn",
    "nauth": "cold",
    "nauthad": "frost",
    "neledh": "friend",
    "neth": "mist, fog",
    "nether": "mist",
    "nethor": "misty",
    "nib": "nib",
    "niol": "valley",
    "niri": "jewel",
    "nis": "daughter",
    "nith": "thorn",
    "nithad": "thorn",
    "no": "no",
    "noas": "bread",
    "noble": "crowned",
    "noor": "morrow",
    "nor": "people, race, nation",
    "noroth": "language, speech",
    "noth": "valley",
    "nov": "horn",
    "nual": "beard",
    "numen": "gift",
    "nuth": "new",
    "nûr": "shadow",
    "núrë": "fire",
    "nurr": "fire",
    "nyn": "nine",
    "oa": "sweet",
    "oar": "spindle",
    "oath": "sworn",
    "ob": "bone",
    "oc": "small",
    "od": "beyond",
    "odhron": "poet",
    "og": "old",
    "ogad": "noble",
    "ogeth": "gift",
    "ogol": "thick, stout",
    "oi": "wool",
    "oith": "tender",
    "oma-": "flow",
    "omor": "great, mighty",
    "one": "river",
    "or": "mountain",
    "orad": "east",
    "orba": "water",
    "orc": "demon, goblin",
    "orcu": "scream",
    "org": "dark",
    "orm": "hill",
    "orn": "horn",
    "orod": "mountain",
    "orodrim": "mountain-dweller",
    "oront": "beast",
    "oron": "mountain",
    "orui": "great, mighty",
    "os": "bone",
    "oth": "sword",
    "otran": "thorn",
    "ou": "great",
    "pa": "beetle",
    "peth": "small",
    "phor": "stout",
    "ra": "sharp",
    "rad": "go, wander",
    "rag": "wolf",
    "ram": "horn",
    "rath": "swift",
    "rathar": "child",
    "rathe-": "forge",
    "rathren": "swift",
    "rith": "whirlwind",
    "rim": "breath",
    "rín": "rain",
    "riw": "spring",
    "ro": "wolf",
    "rod": "thick",
    "ron": "hill",
    "ronin": "hill-people",
    "ronna": "horn",
    "rond": "good",
    "rot": "rich",
    "ru": "river",
    "ruc": "rhombus",
    "rul": "friend",
    "rum": "deep",
    "rûn": "moon",
    "rûna": "moon",
    "ruv": "river",
    "sag": "dear",
    "sal": "long",
    "sam": "soft",
    "san": "wave",
    "sar": "spear",
    "sarn": "stone",
    "sat": "moon",
    "sau": "horn",
    "saur": "horn",
    "sauros": "lizard",
    "se": "flesh",
    "sel": "thirst",
    "ser": "charm",
    "sil": "moonlight",
    "silm": "moonlight",
    "silmar": "moon",
    "silma": "moonlight",
    "silna": "moonlight",
    "sin": "east",
    "sind": "grey",
    "sing": "song",
    "sith": "shadow",
    "sîr": "river",
    "sîra": "river",
    "sithen": "dusk",
    "sithen": "dusk",
    "sithron": "dragon",
    "sly": "swift",
    "sô": "harsh",
    "som": "fire",
    "sor": "forest",
    "sul": "gold",
    "sur": "sea",
    "súr": "wind",
    "súra": "wind",
    "súri": "storm",
    "tarn": "horn",
    "tarnath": "horn",
    "tath": "fall",
    "tâth": "moist",
    "tathron": "thirst",
    "thar": "north",
    "thal": "hail",
    "tharan": "hill",
    "thaur": "beast",
    "thê": "cloud",
    "thor": "great",
    "thorin": "strong",
    "thron": "beast",
    "thros": "clay",
    "tú": "thorn",
    "tul": "day",
    "tulâ": "moon",
    "tulh": "sun",
    "tulon": "sea",
    "ul": "hill",
    "ulf": "wolf",
    "ur": "home",
    "urth": "earth",
    "urg": "wolf",
    "urulóki": "dragon",
    "uth": "horn",
    "uthra": "horn",
    "vag": "spindle",
    "val": "stump",
    "vas": "branch",
    "vat": "spear",
    "ver": "song",
    "veth": "wing",
    "vid": "beetle",
    "vil": "white",
    "vîn": "moon",
    "vó": "river",
    "wë": "mist",
    "weth": "fog",
    "wethil": "light",
    "wî": "sun",
    "wîl": "storm",
    "wi-": "storm",
    "win": "water",
    "wing": "water",
    "winn": "swarm",
    "withe": "mist",
    "path": "pâd",
  "track": "râd",
  "walk": "pada-",
  "ten": "pae",
  "petrel": "paen",
  "theth": "paenen",
  "tenth": "paenui",
  "syrup": "paich",
  "juice": "paich",
  "far off": "palan-",
  "surface": "palath",
  "all": "pân",
  "plank": "pân",
  "board": "pân",
  "floor": "panas",
  "courtyard": "pand",
  "wide": "pann",
  "fill": "panna-",
  "enlarge": "panna-",
  "open": "panna-",
  "complete": "pant",
  "full": "pant",
  "whole": "pant",
  "shaven": "paran",
  "smooth": "paran",
  "book": "parf",
  "field": "parth",
  "enclosed grassland": "parth",
  "arrange": "partha-",
  "compose": "partha-",
  "fullness": "pathred",
  "sward": "pathu",
  "fist": "paur",
  "sickness": "paw",
  "say": "ped-",
  "speak": "ped-",
  "dot": "peg",
  "wither": "pel-",
  "fade": "pel-",
  "enclosure": "pêl",
  "garth": "pêl",
  "withering": "peleth",
  "fading": "pelin",
  "pivot": "pelthaes",
  "without": "pen",
  "anybody": "pen",
  "one": "pen",
  "somebody": "pen",
  "declivity": "pend",
  "slope": "pend",
  "stairway": "pendrath",
  "bow": "peng",
  "fix": "penia-",
  "set": "penia-",
  "slant down": "penna-",
  "history": "pennas",
  "last day of the year": "penninor",
  "story": "pent",
  "half": "per-",
  "Half-Elf": "peredhel",
  "Halfling": "perian",
  "Hobbit": "perian",
  "bitter": "saer",
  "poison": "saew",
  "new": "sain",
  "herb": "salab",
  "broth": "salph",
  "liquid food": "salph",
  "soup": "salph",
  "chamber": "sam",
  "neighbour": "sammar",
  "garden": "sant",
  "field": "sant",
  "yard": "sant",
  "grave": "sarch",
  "stone": "sarn",
  "cairn": "sarnas",
  "pile of stones": "sarnas",
  "drain": "sautha-",
  "juice": "saw",
  "rest": "sedh-",
  "set aside": "seidia-",
  "daughter": "sell",
  "girl": "sell",
  "maid": "sell",
  "this": "sen",
  "Grey-Elf": "send",
  "guesthouse": "sennas",
  "instead": "sennui",
  "rather": "sennui",
  "blood": "sereg",
  "burning": "ruin",
  "fiery red": "ruin",
  "blazing fire": "ruin",
  "slot": "ruin",
  "spoor": "ruin",
  "track": "ruin",
  "footprint": "ruin",
  "anger": "ruith",
  "fox": "rusc",
  "copper": "rust",
  "of copper": "rustui",
  "hound of chase": "rýn",
  "stonecrop (plant)": "seregon",
  "peeble-bank": "serni",
  "friend": "seron",
  "lover": "seron",
  "now": "si",
  "here": "sí",
  "peace": "sîdh",
  "necklace": "sigil",
  "dagger": "sigil",
  "knife": "sigil",
  "shine white": "síla-",
  "silima": "silef",
  "the crystal substance of the Silmarils": "silef",
  "Silmaril": "Silevril",
  "glittering white": "silivren",
  "these": "sin",
  "tidings": "siniath",
  "news": "siniath",
  "novel": "sinnarn",
  "tale": "sinnarn",
  "rill": "sîr",
  "river": "sîr",
  "today": "sîr",
  "flow": "siria-",
  "river": "sirion",
  "flowing": "sirith",
  "drink": "soga",
  "drunk": "sogannen",
  "close": "sol-",
  "root (edible)": "solch",
  "closed": "sollen",
  "as": "sui",
  "like": "sui",
  "hail": "suil",
  "goblet": "sûl",
  "wind": "sûl",
  "few": "sun",
  "brooch": "tachol",
  "pin": "tachol",
  "two": "tâd",
  "two-legged": "tad-dal",
  "double": "tadol",
  "second": "tadui",
  "boundary": "taeg",
  "boundary line": "taeg",
  "long and thin": "taen",
  "height": "taen",
  "summit of high mountain": "taen",
  "exact": "taer",
  "nail": "taes",
  "fasten": "taetha-",
  "tie": "taetha-",
  "clasp": "taew",
  "holder": "taew",
  "socket": "taew",
  "hasp": "taew",
  "staple": "taew",
  "blocked": "tafnen",
  "stopped": "tafnen",
  "closed": "tafnen",
  "mark": "tagol",
  "supporting": "taid",
  "second in command": "taid",
  "marking (a boundary)": "taig",
  "mark": "taith",
  "foot": "tâl",
  "incline": "talad",
  "floor": "talaf",
  "harper": "talagan",
  "floor": "talan",
  "flatlands": "talath",
  "flat surface": "talath",
  "plane": "talath",
  "plain": "talath",
  "low, flat field": "talf",
  "palm (hand)": "talf",
  "table": "talfin",
  "stirrup": "talraph",
  "falling": "talt",
  "slipping": "talt",
  "insecure": "talt",
  "flat": "talu",
  "forge": "tamin",
  "knock": "tamma-",
  "make": "tan-",
  "maker": "tân?",
  "firm": "tanc",
  "bowstring": "tang",
  "confirm": "tangada-",
  "make firm": "tangada-",
  "establish": "tangada-",
  "sign": "tann",
  "stiff": "tara",
  "tough": "tara",
  "steep mountain peak": "tarag",
  "robust": "tarch",
  "firm": "tarias",
  "difficulty": "tarias",
  "stiffness": "tarias",
  "toughness": "tarias",
  "obstinate": "tarlanc",
  "trouble": "tass",
  "willow": "tathar",
  "of willow": "tathren",
  "having willows": "tathren",
  "lofty": "taur",
  "high": "taur",
  "sublime": "taur",
  "noble": "taur",
  "king": "taur",
  "forest": "taur",
  "forester": "tauron",
  "thatch": "taus",
  "woodpecker": "tavor",
  "wool": "taw",
  "of wool": "taw",
  "woolen": "taw",
  "that": "taw?",
  "wood": "tawar",
  "forest": "tawar",
  "wooden": "tawaren",
  "Forest people (Silvan Elves)": "Tawarwaith",
  "line": "tê",
  "row": "tê",
  "pen": "tegil",
  "calligrapher": "tegilbor",
  "play": "teilia-",
  "sport": "teilien",
  "write": "teitha-",
  "stem": "telch",
  "hindmost part": "tele",
  "rear": "tele",
  "end": "tele",
  "Teler (member of the Third Clan of the Elves)": "teler",
  "Teleri (People)": "Telerrim",
  "play": "telia-",
  "sole of the foot": "telluin",
  "dome": "telu",
  "verse (poetry)": "tenn",
  "fine pierced hole": "tess",
  "letter": "têw",
  "sign": "têw",
  "tengwa": "têw",
  "pillar (wood)": "thafn",
  "firm": "thala",
  "steady": "thala",
  "stalwart": "thala",
  "dauntless": "thalion",
  "steadfast": "thalion",
  "hero": "thalion",
  "dauntless": "thalion",
  "steadfast": "thalion",
  "hero": "thalion",
  "hall": "tham",
  "great hall": "thamas",
  "flame": "than-",
  "cleft": "thanc",
  "forked": "thanc",
  "split": "thanc",
  "true": "thand",
  "abiding": "thand",
  "shield": "thand",
  "compulsion": "thang",
  "duress": "thang",
  "need": "thang",
  "oppression": "thang",
  "tyranny": "thang",
  "shield wall": "thangail",
  "shield fence": "thangail",
  "across": "thar-",
  "over": "thar-",
  "beyond": "thar-",
  "stiff grass": "thâr",
  "footstool": "tharas",
  "hassock": "tharas",
  "crossway": "tharbad",
  "rigid": "tharn",
  "sapless": "tharn",
  "stiff": "tharn",
  "withered": "tharn",
  "pine-tree": "thaun",
  "enclosed": "thaur",
  "abhorrent": "thaur",
  "detestable": "thaur",
  "abominable": "thaur",
  "foul": "thaur",
  "builder": "thavron",
  "carpenter": "thavron",
  "wright": "thavron",
  "corrupt": "thaw",
  "rotten": "thaw",
  "mean": "thel-",
  "intend": "thel-",
  "resolve": "thel-",
  "purpose": "thel",
  "will": "thel",
  "sister": "thêl",
  "point of spear": "thela",
  "purpose": "thelion",
  "intention": "thelion",
  "short": "then",
  "strong": "thenid",
  "loyal": "thenid",
  "faithful": "thenid",
  "short": "thent",
  "appear": "thia-",
  "seem": "thia-",
  "glisten": "thilia-",
  "pale": "thind",
  "grey": "thind",
  "grow toward evening": "thinna-",
  "shortness": "thinnas",
  "look": "thîr",
  "face": "thîr",
  "expression": "thîr",
  "helm": "thôl",
  "pine-tree": "thôn",
  "root": "thond",
  "kindler (fem.)": "thoniel",
  "eagle": "thôr",
  "leaping down": "thôr",
  "swooping": "thôr",
  "fence": "thora-",
  "detestable": "thoren",
  "abhorrent": "thoren",
  "abominable": "thoren",
  "fenced": "thoren",
  "guarded": "thoren",
  "hidden": "thoren",
  "torrent": "thórod",
  "eagle": "thoron",
  "smell": "thost",
  "stink": "thosta-",
  "stench": "thû",
  "breathe": "thuia-",
  "breath": "thûl",
  "secret": "thurin",
  "hidden": "thurin",
  "row": "tî",
  "line": "tî",
  "tine": "till",
  "spike": "till",
  "point": "till",
  "sharp horn": "till",
  "metal": "tinc",
  "glint": "tinna-",
  "dusk": "tinnu",
  "twilight": "tinnu",
  "spark": "tint",
  "spark": "tinu",
  "nightingale": "tinúviel",
  "gaze": "tir-",
  "guard": "tir-",
  "watch": "tir-",
  "straight": "tîr",
  "glance": "tîr",
  "view": "tîr",
  "looking": "tîr",
  "watch": "tíra-",
  "vision": "tírad",
  "look toward": "tiria-",
  "watch": "tiria-",
  "guard": "tiria-",
  "gaze": "tiria-",
  "guard": "tirith",
  "horizon": "tiriw",
  "watcher": "tirn",
  "little": "tithen",
  "alphabet": "tiwdi",
  "roof": "toba-",
  "roof": "tobas",
  "deep": "tofn",
  "low": "tofn",
  "low-lying": "tofn",
  "bring": "tog-",
  "lead": "tog-",
  "come": "tol-",
  "middle finger": "toleg",
  "island": "toll",
  "eighth": "tollui",
  "trusty": "tolog",
  "eight": "toloth",
  "eighth": "tolothen",
  "fetch": "toltha-",
  "make come": "toltha-",
  "tall": "tond",
  "resonant (of strings)": "tong",
  "brother": "tôr",
  "hole": "torech",
  "lair": "torech",
  "excavation": "torech",
  "down": "torn",
  "troll": "torog",
  "control": "tortha-",
  "wield": "tortha-",
  "bush (low-growing)": "toss",
  "find": "tov-",
  "shire": "trann",
  "administrative district": "trann",
  "regional": "trannail",
  "local": "trannail",
  "doubt": "trass",
  "worry": "trass",
  "harass": "trasta-",
  "trouble": "trasta-",
  "through": "tre-",
  "recount": "trenar-",
  "tell to end": "trenar-",
  "account": "trenarn",
  "tale": "trenarn",
  "cross": "trevad-",
  "through": "trî",
  "slender": "trîw",
  "not": "ú",
  "without": "ú",
  "monster": "úan",
  "hideous": "uanui",
  "monstrous": "uanui",
  "denial": "ubed",
  "ill deed": "úgarth",
  "sin": "úgarth",
  "always": "ui",
  "everlasting": "ui",
  "eternal": "ui",
  "both": "ui-",
  "two": "ui-",
  "twi-": "ui-",
  "twilight": "uial",
  "closed": "uidafnen",
  "seaweed": "uil",
  "Oiolossë": "Uilos",
  "eternity": "uir",
  "eternal": "uireb",
  "everlasting": "uireb",
  "in": "vi",
  "girl": "wen",
  "virgin": "wen",
  "maiden": "wen",
  "muscle": "tû",
  "vigour": "tû",
  "physical strength": "tû",
  "fat": "tûg",
  "thick": "tûg",
  "bud": "tui",
  "sprout": "tui",
  "spring": "tuia-",
  "swell": "tuia-",
  "swallow": "tuilinn",
  "bud": "tuiw",
  "sprout": "tuiw",
  "support": "tulu",
  "poplar tree": "tulus",
  "deep valley": "tûm",
  "hump": "tump",
  "mound": "tund",
  "control": "tûr",
  "mastery": "tûr",
  "power": "tûr",
  "master": "tûr",
  "victor": "tûr",
  "lord": "tûr",
  "ugly": "ul-",
  "hideous": "ul-",
  "odor": "ûl",
  "bad": "ulug",
  "evil": "ulug",
  "unquenchable": "uluithiad",
  "deformed": "ulunn",
  "hideous creature": "ulunn",
  "monster": "ulunn",
  "bad": "um",
  "evil": "um",
  "creature": "ûn",
  "spider": "ungol",
  "heat": "ûr",
  "fire": "ûr",
  "fire-dragon": "urlug",
  "bogey": "urug",
  "monster": "urug",
  "orc": "urug",
  "hot": "úrui",
  "August": "úrui",
  "evil creature": "uruk",
  "temptation": "úthaes",
  "gulp": "yll",
  "drinking vessel": "ylf",
  "brand": "ylf",
  "twelve": "ýneg",
  "twelfth": "yngui",
  "course": "ýr",
  };
  
  export default elvishDictionary;